-- Conflict Converge - Premake5 Configuration
-- Build system for raylib-based RTS game
-- Generated by premake5

workspace "ConflictConverge"
    configurations { "Debug", "Release" }

    -- Output directory
    location "prj"

    -- M15: /FS serializes PDB writes. The protobuf generated headers are
    -- huge; without this, parallel CL instances lock vc143.pdb (MSVC C1041).
    buildoptions { "/FS" }

-- M1 Goal 7: build profiles shared by every project below.
-- Debug keeps assertions enabled (no NDEBUG) with full symbols;
-- Release defines NDEBUG (compiles out CC_ASSERT, see Assert.h) and optimizes.
filter "configurations:Debug"
    defines { "CC_DEBUG" }
    symbols "On"

filter "configurations:Release"
    defines { "NDEBUG" }
    optimize "On"

filter {}

-- Project to build raylib as static library from deps/
project "raylib-static"
    kind "StaticLib"
    cppdialect "C++20"

    -- raylib's platform-specific and third-party sources under platforms/ and
    -- external/ are #included directly by the top-level .c files (rcore.c,
    -- raudio.c, rglfw.c, ...) and must not be compiled as separate translation
    -- units, so only the top-level src/*.c files are picked up here.
    files {
        "deps/raylib/src/*.c",
        "deps/raylib/src/**.h",
        "deps/raylib/src/**.inl"
    }

    -- Select the desktop (GLFW) platform backend
    defines { "PLATFORM_DESKTOP" }

    -- Include directories for raylib's own dependencies
    includedirs {
        "deps/raylib/src",
        "deps/raylib/src/external/glfw/include",
        "deps/glm"
    }

-- Project to build raygui as static library from deps/
project "raygui-static"
    kind "StaticLib"
    cppdialect "C++20"
    
    -- raygui is a header-only library (single raygui.h), so the actual
    -- implementation translation unit lives in src/thirdparty and defines
    -- RAYGUI_IMPLEMENTATION before including it.
    files {
        "src/thirdparty/raygui_impl.c",
        "deps/raygui/src/**.h",
        "deps/raygui/src/**.inl"
    }

    -- Include directories for raygui's dependencies (raylib and glm)
    includedirs {
        "deps/raygui/src",
        "deps/raylib/src",
        "deps/glm"
    }

-- Main game project
project "conflict-converge"
    kind "ConsoleApp"
    cppdialect "C++20"
    
    -- Source files from src/ folder
    files {
        "src/**.cpp",
        "src/**.cc",
        "src/**.h",
        "src/**.inl"
    }
    
    -- Include directories (subsystem dirs keep includes bare: #include "Unit.h"
    -- works from any TU, same as when the folders were flat)
    includedirs {
        "deps/raylib/src",
        "deps/raygui/src",
        "deps/glm",
        "deps/protobuf/src",
        "..",
        "src/game",
        "src/game/public",
        "src/game/private",
        "src/game/public/core",
        "src/game/public/world",
        "src/game/public/units",
        "src/game/public/economy",
        "src/game/public/app",
        "src/game/private/core",
        "src/game/private/world",
        "src/game/private/units",
        "src/game/private/economy",
        "src/game/private/app"
    }
    
    -- Link with raylib and raygui static libraries, plus the Windows system
    -- libraries raylib's desktop (GLFW) backend needs
    links {
        "raylib-static",
        "raygui-static",
        "opengl32",
        "gdi32",
        "winmm",
        "shell32"
    }

    -- M15: CMake-built protobuf static lib (Release: libprotobuf.lib in
    -- build/Release, Debug: libprotobufd.lib in build/Debug). Shared CRT
    -- (/MD) matches these projects; do not flip protobuf_MSVC_STATIC_RUNTIME.
    filter "configurations:Debug"
        libdirs { "deps/protobuf/build/Debug" }
        links { "libprotobufd" }
    filter "configurations:Release"
        libdirs { "deps/protobuf/build/Release" }
        links { "libprotobuf" }
    filter {}

    -- Runtime data staging (game project only): the game resolves data/,
    -- settings, and quicksaves relative to CWD, which under VS F5 is the
    -- project dir (prj/), not the repo root -- hence the empty setup map
    -- list. The postbuild copy covers direct exe runs; debugdir covers VS
    -- F5 (working dir = repo root, where data/ lives). NOTE: debugdir is
    -- resolved against the workspace root, so ".." alone would land one
    -- level too high -- always anchor it at the project dir like this.
    debugdir "%{wks.location}/.."
    postbuildcommands {
        "{COPYDIR} %{wks.location}/../data %{cfg.buildtarget.directory}/data"
    }

-- Test project
project "conflict-converge-test"
    kind "ConsoleApp"
    cppdialect "C++20"
    
    -- Depend on conflict-converge project (build order dependency)
    dependson { "conflict-converge" }
    
    -- Source files from tests/ folder, plus the game implementation TUs under
    -- test (the game entry point src/game/main.cpp is excluded: this project
    -- provides its own main in tests/main.cpp).
    files {
        "tests/**.cpp",
        "tests/**.h",
        "tests/**.inl",
        "src/game/private/**.cpp",
        "src/game/private/**.cc"
    }

    -- Tier-1 e2e lives in its own binary below (own main + a real window),
    -- so it must not compile into the headless runner.
    removefiles {
        "tests/e2e/**"
    }
    
    -- Include directories (same subsystem dirs as the game project)
    includedirs {
        "deps/raylib/src",
        "deps/raygui/src",
        "deps/glm",
        "deps/protobuf/src",
        "..",
        "src/game/public",
        "src/game/public/core",
        "src/game/public/world",
        "src/game/public/units",
        "src/game/public/economy",
        "src/game/public/app"
    }
    
    -- Link with raylib and raygui static libraries, plus the Windows system
    -- libraries raylib's desktop (GLFW) backend needs
    links {
        "raylib-static",
        "raygui-static",
        "opengl32",
        "gdi32",
        "winmm",
        "shell32"
    }

    -- M15: same CMake-built protobuf lib as the game project (see above).
    filter "configurations:Debug"
        libdirs { "deps/protobuf/build/Debug" }
        links { "libprotobufd" }
    filter "configurations:Release"
        libdirs { "deps/protobuf/build/Release" }
        links { "libprotobuf" }
    filter {}

-- Tier-1 end-to-end project: the real Game loop in a hidden window
-- (tests/e2e/e2e_main.cpp). Own binary, excluded from the default test run:
-- it needs a GPU context and real time, so it is a local pre-commit gate.
project "conflict-converge-e2e"
    kind "ConsoleApp"
    cppdialect "C++20"

    dependson { "conflict-converge" }

    files {
        "tests/e2e/**.cpp",
        "tests/e2e/**.h",
        "tests/e2e/**.inl",
        "src/game/private/**.cpp",
        "src/game/private/**.cc"
    }

    includedirs {
        "deps/raylib/src",
        "deps/raygui/src",
        "deps/glm",
        "deps/protobuf/src",
        "..",
        "src/game/public",
        "src/game/public/core",
        "src/game/public/world",
        "src/game/public/units",
        "src/game/public/economy",
        "src/game/public/app",
        "tests/unit-tests"
    }

    links {
        "raylib-static",
        "raygui-static",
        "opengl32",
        "gdi32",
        "winmm",
        "shell32"
    }

    filter "configurations:Debug"
        libdirs { "deps/protobuf/build/Debug" }
        links { "libprotobufd" }
    filter "configurations:Release"
        libdirs { "deps/protobuf/build/Release" }
        links { "libprotobuf" }
    filter {}

    -- Same staging as the game: data/ beside the exe for direct runs,
    -- repo root as the VS debugger working dir.
    debugdir "%{wks.location}/.."
    postbuildcommands {
        "{COPYDIR} %{wks.location}/../data %{cfg.buildtarget.directory}/data"
    }
