-- Conflict Converge - Premake5 Configuration
-- Build system for raylib-based RTS game
-- Generated by premake5

workspace "ConflictConverge"
    -- ASan mirrors Debug (assertions on, symbols) plus MSVC
    -- AddressSanitizer on compile AND link. Needs the ASan runtime DLLs
    -- on PATH to run (VS Developer prompt, or the MSVC bin dir holding
    -- clang_rt.asan_dbg_dynamic-<arch>.dll). Incompatible with /RTC and
    -- incremental linking, so both are switched off here explicitly.
    configurations { "Debug", "Release", "ASan" }

    -- 64-bit only: Win32/32-bit is dropped (2GB limit, WOW64, weaker
    -- optimizer). Single platform so /p:Platform=x64 everywhere.
    platforms { "x64" }

    -- Output directory
    location "prj"

    -- Flat output layout (x64-only, so no platform segment is needed):
    -- prj/bin/<Cfg> and prj/obj/<Cfg>/<project>. Keeps the documented
    -- `prj/bin/<Cfg>/conflict-converge-test.exe` paths stable. (Paths are
    -- resolved against the workspace root, hence the prj/ prefix.)
    targetdir "prj/bin/%{cfg.buildcfg}"
    objdir "prj/obj/%{cfg.buildcfg}/%{prj.name}"

    -- /FS serializes PDB writes. The header-heavy TUs (cereal templates)
    -- are huge; without this, parallel CL instances lock vc143.pdb (MSVC C1041).
    buildoptions { "/FS" }

-- Build profiles shared by every project below.
-- Debug keeps assertions enabled (no NDEBUG) with full symbols;
-- Release defines NDEBUG (compiles out CC_ASSERT, see Assert.h) and optimizes.
filter "configurations:Debug"
    defines { "CC_DEBUG" }
    symbols "On"

filter "configurations:Release"
    defines { "NDEBUG" }
    optimize "On"

filter "configurations:ASan"
    defines { "CC_DEBUG" }
    symbols "On"
    sanitize { "Address" }
    editandcontinue "Off" -- /ZI is incompatible with /fsanitize=address
    linkoptions { "/INCREMENTAL:NO" }

filter {}

-- Third-party single-TU implementations use their own idioms (fopen, ...):
-- silence MSVC's CRT-deprecation warnings for those files only.
filter { "files:src/thirdparty/rini_impl.cpp" }
    defines { "_CRT_SECURE_NO_WARNINGS" }
filter {}

-- Project to build raylib as static library from deps/
project "raylib-static"
    kind "StaticLib"
    cppdialect "C++20"

    -- raylib's platform-specific and third-party sources under platforms/ and
    -- external/ are #included directly by the top-level .c files (rcore.c,
    -- raudio.c, rglfw.c, ...) and must not be compiled as separate translation
    -- units, so only the top-level src/*.c files are picked up here.
    files {
        "deps/raylib/src/*.c",
        "deps/raylib/src/**.h",
        "deps/raylib/src/**.inl"
    }

    -- Select the desktop (GLFW) platform backend
    defines { "PLATFORM_DESKTOP" }

    -- Include directories for raylib's own dependencies
    includedirs {
        "deps/raylib/src",
        "deps/raylib/src/external/glfw/include",
        "deps/glm"
    }

project "imgui-static"
    kind "StaticLib"
    cppdialect "C++20"
    files {
        "deps/imgui/imgui.cpp",
        "deps/imgui/imgui_draw.cpp",
        "deps/imgui/imgui_tables.cpp",
        "deps/imgui/imgui_widgets.cpp",
        "deps/rlImGui/rlImGui.cpp",
        "deps/imgui/**.h",
        "deps/rlImGui/**.h"
    }
    includedirs {
        "deps/imgui",
        "deps/rlImGui",
        "deps/raylib/src"
    }
    defines {
        "IMGUI_DISABLE_OBSOLETE_FUNCTIONS",
        "IMGUI_DISABLE_OBSOLETE_KEYIO",
        "NO_FONT_AWESOME"
    }

-- Project to build raygui as static library from deps/
project "raygui-static"
    kind "StaticLib"
    cppdialect "C++20"
    
    -- raygui is a header-only library (single raygui.h), so the actual
    -- implementation translation unit lives in src/thirdparty and defines
    -- RAYGUI_IMPLEMENTATION before including it.
    files {
        "src/thirdparty/raygui_impl.c",
        "deps/raygui/src/**.h",
        "deps/raygui/src/**.inl"
    }

    -- Include directories for raygui's dependencies (raylib and glm)
    includedirs {
        "deps/raygui/src",
        "deps/raylib/src",
        "deps/glm"
    }

-- Main game project
project "conflict-converge"
    kind "ConsoleApp"
    cppdialect "C++20"

    -- x64 link order: sibling static libs must be searched BEFORE the Windows
    -- system libs. raylib defines CloseWindow/PlaySound, which also exist in
    -- user32.lib/winmm.lib; x64 has no stdcall name decoration to tell them
    -- apart (unlike Win32), so MSVC reports LNK2005 if a system lib wins the
    -- race. NoImplicitLink emits the sibling .libs as explicit ordered paths
    -- first in AdditionalDependencies; ProjectReference items are still
    -- emitted, preserving solution build ordering.
    flags { "NoImplicitLink" }
    
    -- Source files from src/ folder
    files {
        "src/**.cpp",
        "src/**.cc",
        "src/**.h",
        "src/**.inl"
    }
    
    includedirs {
        "deps/raylib/src",
        "deps/raygui/src",
        "deps/imgui",
        "deps/rlImGui",
        "deps/glm",
        "deps/reasings/src",
        "deps/rini/src",
        "deps/cereal/include",
        "deps/RmlUi/Include",
        "..",
        "src/game/public",
        "src/game/private"
    }
    
    -- Link with raylib, raygui and RmlUi static libraries, plus the Windows
    -- system libraries raylib's desktop (GLFW) backend needs
    links {
        "raylib-static",
        "raygui-static",
        "rmlui-static",
        "freetype-static",
        "opengl32",
        "gdi32",
        "winmm",
        "shell32"
    }

    -- Runtime data staging (game project only): the game resolves data/,
    -- settings, and quicksaves relative to CWD, which under VS F5 is the
    -- project dir (prj/), not the repo root -- hence the empty setup map
    -- list. The postbuild copy covers direct exe runs; debugdir covers VS
    -- F5 (working dir = repo root, where data/ lives). NOTE: debugdir is
    -- resolved against the workspace root, so ".." alone would land one
    -- level too high -- always anchor it at the project dir like this.
    debugdir "%{wks.location}/.."
    postbuildcommands {
        "{COPYDIR} %{wks.location}/../data %{cfg.buildtarget.directory}/data"
    }
    defines { "NO_FONT_AWESOME", "RMLUI_STATIC_LIB" }
    filter "configurations:Debug or ASan"
        links { "imgui-static" }
    filter {}

-- Test project
project "conflict-converge-test"
    kind "ConsoleApp"
    cppdialect "C++20"

    -- x64 link order: sibling static libs must be searched BEFORE the Windows
    -- system libs. raylib defines CloseWindow/PlaySound, which also exist in
    -- user32.lib/winmm.lib; x64 has no stdcall name decoration to tell them
    -- apart (unlike Win32), so MSVC reports LNK2005 if a system lib wins the
    -- race. NoImplicitLink emits the sibling .libs as explicit ordered paths
    -- first in AdditionalDependencies; ProjectReference items are still
    -- emitted, preserving solution build ordering.
    flags { "NoImplicitLink" }
    
    -- Depend on conflict-converge project (build order dependency)
    dependson { "conflict-converge" }
    
    -- Source files from tests/ folder, plus the game implementation TUs under
    -- test (the game entry point src/game/main.cpp is excluded: this project
    -- provides its own main in tests/main.cpp).
    files {
        "tests/**.cpp",
        "tests/**.h",
        "tests/**.inl",
        "src/game/private/**.cpp",
        "src/game/private/**.cc",
        "src/thirdparty/rini_impl.cpp"
    }

    -- Tier-1 e2e lives in its own binary below (own main + a real window),
    -- so it must not compile into the headless runner.
    removefiles {
        "tests/e2e/**"
    }
    
    includedirs {
        "deps/raylib/src",
        "deps/raygui/src",
        "deps/imgui",
        "deps/rlImGui",
        "deps/glm",
        "deps/reasings/src",
        "deps/rini/src",
        "deps/cereal/include",
        "deps/RmlUi/Include",
        "..",
        "src/game/public"
    }
    
    -- Link with raylib and raygui static libraries, plus the Windows system
    -- libraries raylib's desktop (GLFW) backend needs
    links {
        "raylib-static",
        "raygui-static",
        "rmlui-static",
        "freetype-static",
        "opengl32",
        "gdi32",
        "winmm",
        "shell32"
    }
    defines { "NO_FONT_AWESOME", "RMLUI_STATIC_LIB" }
    filter "configurations:Debug or ASan"
        links { "imgui-static" }
    filter {}

-- Tier-1 end-to-end project: the real Game loop in a hidden window
-- (tests/e2e/e2e_main.cpp). Own binary, excluded from the default test run:
-- it needs a GPU context and real time, so it is a local pre-commit gate.
project "conflict-converge-e2e"
    kind "ConsoleApp"
    cppdialect "C++20"

    -- x64 link order: sibling static libs must be searched BEFORE the Windows
    -- system libs. raylib defines CloseWindow/PlaySound, which also exist in
    -- user32.lib/winmm.lib; x64 has no stdcall name decoration to tell them
    -- apart (unlike Win32), so MSVC reports LNK2005 if a system lib wins the
    -- race. NoImplicitLink emits the sibling .libs as explicit ordered paths
    -- first in AdditionalDependencies; ProjectReference items are still
    -- emitted, preserving solution build ordering.
    flags { "NoImplicitLink" }

    dependson { "conflict-converge" }

    files {
        "tests/e2e/**.cpp",
        "tests/e2e/**.h",
        "tests/e2e/**.inl",
        "src/game/private/**.cpp",
        "src/game/private/**.cc",
        "src/thirdparty/rini_impl.cpp"
    }

    includedirs {
        "deps/raylib/src",
        "deps/raygui/src",
        "deps/imgui",
        "deps/rlImGui",
        "deps/glm",
        "deps/reasings/src",
        "deps/rini/src",
        "deps/cereal/include",
        "..",
        "src/game/public",
        "tests/unit-tests",
        "deps/RmlUi/Include"
    }

    links {
        "raylib-static",
        "raygui-static",
        "rmlui-static",
        "freetype-static",
        "opengl32",
        "gdi32",
        "winmm",
        "shell32"
    }

    -- Same staging as the game: data/ beside the exe for direct runs,
    -- repo root as the VS debugger working dir.
    debugdir "%{wks.location}/.."
    postbuildcommands {
        "{COPYDIR} %{wks.location}/../data %{cfg.buildtarget.directory}/data"
    }
    defines { "NO_FONT_AWESOME", "RMLUI_STATIC_LIB" }
    filter "configurations:Debug or ASan"
        links { "imgui-static" }
    filter {}

-- Standalone unit-config editor: its own windowed binary sharing only the
-- data-layer + art TUs (UnitStats/UnitConfig/SpriteData + Art for the live
-- preview), never Game.cpp or the test runner.
project "conflict-converge-editor"
    kind "ConsoleApp"
    cppdialect "C++20"

    -- x64 link order: sibling static libs must be searched BEFORE the Windows
    -- system libs. raylib defines CloseWindow/PlaySound, which also exist in
    -- user32.lib/winmm.lib; x64 has no stdcall name decoration to tell them
    -- apart (unlike Win32), so MSVC reports LNK2005 if a system lib wins the
    -- race. NoImplicitLink emits the sibling .libs as explicit ordered paths
    -- first in AdditionalDependencies; ProjectReference items are still
    -- emitted, preserving solution build ordering.
    flags { "NoImplicitLink" }

    files {
        "tools/unit_editor/**.cpp",
        "tools/unit_editor/**.h",
        "src/game/private/core/MathUtils.cpp",
        "src/game/private/units/UnitStats.cpp",
        "src/game/private/app/UnitConfig.cpp",
        "src/game/private/app/SpriteData.cpp",
        "src/game/private/app/Art.cpp"
    }

    includedirs {
        "deps/raylib/src",
        "deps/raygui/src",
        "deps/glm",
        "deps/reasings/src",
        "deps/cereal/include",
        "..",
        "src/game/public",
        "tools/unit_editor"
    }

    links {
        "raylib-static",
        "raygui-static",
        "opengl32",
        "gdi32",
        "winmm",
        "shell32"
    }

    -- Same staging as the game: data/configs resolves beside the exe for
    -- direct runs, repo root as the VS debugger working dir.
    debugdir "%{wks.location}/.."
    postbuildcommands {
        "{COPYDIR} %{wks.location}/../data %{cfg.buildtarget.directory}/data"
    }

-- ===== FreeType (RmlUi default font engine) =====
project "freetype-static"
    kind "StaticLib"
    cppdialect "C++20"
    files {
        "deps/freetype/src/base/ftsystem.c",
        "deps/freetype/src/base/ftinit.c",
        "deps/freetype/src/base/ftdebug.c",
        "deps/freetype/src/base/ftbase.c",
        "deps/freetype/src/base/ftbbox.c",
        "deps/freetype/src/base/ftglyph.c",
        "deps/freetype/src/base/ftbitmap.c",
        "deps/freetype/src/base/ftstroke.c",
        "deps/freetype/src/base/ftsynth.c",
        "deps/freetype/src/base/fttype1.c",
        "deps/freetype/src/base/ftmm.c",
        "deps/freetype/src/autofit/autofit.c",
        "deps/freetype/src/bdf/bdf.c",
        "deps/freetype/src/cff/cff.c",
        "deps/freetype/src/cid/type1cid.c",
        "deps/freetype/src/pcf/pcf.c",
        "deps/freetype/src/pfr/pfr.c",
        "deps/freetype/src/sfnt/sfnt.c",
        "deps/freetype/src/truetype/truetype.c",
        "deps/freetype/src/type1/type1.c",
        "deps/freetype/src/type42/type42.c",
        "deps/freetype/src/winfonts/winfnt.c",
        "deps/freetype/src/raster/raster.c",
        "deps/freetype/src/smooth/smooth.c",
        "deps/freetype/src/sdf/sdf.c",
        "deps/freetype/src/psaux/psaux.c",
        "deps/freetype/src/pshinter/pshinter.c",
        "deps/freetype/src/psnames/psnames.c",
        "deps/freetype/src/gzip/ftgzip.c",
        "deps/freetype/src/lzw/ftlzw.c",
        "deps/freetype/src/svg/svg.c"
    }
    includedirs { "deps/freetype/include" }
    defines { "FT2_BUILD_LIBRARY" }
filter { "files:deps/freetype/**.c" }
    defines { "_CRT_SECURE_NO_WARNINGS" }
filter {}

-- ===== RmlUi (permanent) =====
project "rmlui-static"
    kind "StaticLib"
    cppdialect "C++20"
    files {
        "deps/RmlUi/Source/Core/**.cpp",
        "deps/RmlUi/Source/Core/**.h",
        "deps/RmlUi/Source/Debugger/**.cpp",
        "deps/RmlUi/Source/Debugger/**.h"
    }
    includedirs {
        "deps/RmlUi/Include",
        "deps/freetype/include"
    }
    defines {
        "RMLUI_STATIC_LIB",
        "RMLUI_FONT_ENGINE_FREETYPE"
    }
    links {
        "freetype-static"
    }

filter { "files:deps/RmlUi/**.cpp" }
    defines { "_CRT_SECURE_NO_WARNINGS" }
filter {}
