// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: spritedata.proto

#include "spritedata.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace cc {
namespace sprites {
PROTOBUF_CONSTEXPR SpriteBounds::SpriteBounds(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.left_)*/0
  , /*decltype(_impl_.top_)*/0
  , /*decltype(_impl_.right_)*/0
  , /*decltype(_impl_.bottom_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SpriteBoundsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SpriteBoundsDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SpriteBoundsDefaultTypeInternal() {}
  union {
    SpriteBounds _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SpriteBoundsDefaultTypeInternal _SpriteBounds_default_instance_;
PROTOBUF_CONSTEXPR SpriteOrigin::SpriteOrigin(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.x_)*/0
  , /*decltype(_impl_.y_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SpriteOriginDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SpriteOriginDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SpriteOriginDefaultTypeInternal() {}
  union {
    SpriteOrigin _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SpriteOriginDefaultTypeInternal _SpriteOrigin_default_instance_;
PROTOBUF_CONSTEXPR SpriteTexture::SpriteTexture(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.file_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.id_)*/0
  , /*decltype(_impl_.width_)*/0
  , /*decltype(_impl_.height_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SpriteTextureDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SpriteTextureDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SpriteTextureDefaultTypeInternal() {}
  union {
    SpriteTexture _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SpriteTextureDefaultTypeInternal _SpriteTexture_default_instance_;
PROTOBUF_CONSTEXPR SpriteDef::SpriteDef(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.bounds_)*/nullptr
  , /*decltype(_impl_.origin_)*/nullptr
  , /*decltype(_impl_.id_)*/0
  , /*decltype(_impl_.texture_)*/0
  , /*decltype(_impl_.mask_sprite_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SpriteDefDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SpriteDefDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SpriteDefDefaultTypeInternal() {}
  union {
    SpriteDef _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SpriteDefDefaultTypeInternal _SpriteDef_default_instance_;
PROTOBUF_CONSTEXPR SpriteGrid::SpriteGrid(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.prefix_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.origin_)*/nullptr
  , /*decltype(_impl_.texture_)*/0
  , /*decltype(_impl_.start_id_)*/0
  , /*decltype(_impl_.rows_)*/0
  , /*decltype(_impl_.cols_)*/0
  , /*decltype(_impl_.cell_w_)*/0
  , /*decltype(_impl_.cell_h_)*/0
  , /*decltype(_impl_.mask_grid_start_id_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SpriteGridDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SpriteGridDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SpriteGridDefaultTypeInternal() {}
  union {
    SpriteGrid _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SpriteGridDefaultTypeInternal _SpriteGrid_default_instance_;
PROTOBUF_CONSTEXPR AnimFrame::AnimFrame(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.sprite_)*/0
  , /*decltype(_impl_.duration_ms_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct AnimFrameDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AnimFrameDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~AnimFrameDefaultTypeInternal() {}
  union {
    AnimFrame _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AnimFrameDefaultTypeInternal _AnimFrame_default_instance_;
PROTOBUF_CONSTEXPR SpriteAnim::SpriteAnim(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.frames_)*/{}
  , /*decltype(_impl_.name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.id_)*/0
  , /*decltype(_impl_.loop_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SpriteAnimDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SpriteAnimDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SpriteAnimDefaultTypeInternal() {}
  union {
    SpriteAnim _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SpriteAnimDefaultTypeInternal _SpriteAnim_default_instance_;
PROTOBUF_CONSTEXPR SpriteSheet::SpriteSheet(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.textures_)*/{}
  , /*decltype(_impl_.sprites_)*/{}
  , /*decltype(_impl_.grids_)*/{}
  , /*decltype(_impl_.animations_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SpriteSheetDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SpriteSheetDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SpriteSheetDefaultTypeInternal() {}
  union {
    SpriteSheet _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SpriteSheetDefaultTypeInternal _SpriteSheet_default_instance_;
}  // namespace sprites
}  // namespace cc
static ::_pb::Metadata file_level_metadata_spritedata_2eproto[8];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_spritedata_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_spritedata_2eproto = nullptr;

const uint32_t TableStruct_spritedata_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::cc::sprites::SpriteBounds, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::cc::sprites::SpriteBounds, _impl_.left_),
  PROTOBUF_FIELD_OFFSET(::cc::sprites::SpriteBounds, _impl_.top_),
  PROTOBUF_FIELD_OFFSET(::cc::sprites::SpriteBounds, _impl_.right_),
  PROTOBUF_FIELD_OFFSET(::cc::sprites::SpriteBounds, _impl_.bottom_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::cc::sprites::SpriteOrigin, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::cc::sprites::SpriteOrigin, _impl_.x_),
  PROTOBUF_FIELD_OFFSET(::cc::sprites::SpriteOrigin, _impl_.y_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::cc::sprites::SpriteTexture, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::cc::sprites::SpriteTexture, _impl_.id_),
  PROTOBUF_FIELD_OFFSET(::cc::sprites::SpriteTexture, _impl_.file_),
  PROTOBUF_FIELD_OFFSET(::cc::sprites::SpriteTexture, _impl_.width_),
  PROTOBUF_FIELD_OFFSET(::cc::sprites::SpriteTexture, _impl_.height_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::cc::sprites::SpriteDef, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::cc::sprites::SpriteDef, _impl_.name_),
  PROTOBUF_FIELD_OFFSET(::cc::sprites::SpriteDef, _impl_.id_),
  PROTOBUF_FIELD_OFFSET(::cc::sprites::SpriteDef, _impl_.texture_),
  PROTOBUF_FIELD_OFFSET(::cc::sprites::SpriteDef, _impl_.bounds_),
  PROTOBUF_FIELD_OFFSET(::cc::sprites::SpriteDef, _impl_.origin_),
  PROTOBUF_FIELD_OFFSET(::cc::sprites::SpriteDef, _impl_.mask_sprite_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::cc::sprites::SpriteGrid, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::cc::sprites::SpriteGrid, _impl_.texture_),
  PROTOBUF_FIELD_OFFSET(::cc::sprites::SpriteGrid, _impl_.prefix_),
  PROTOBUF_FIELD_OFFSET(::cc::sprites::SpriteGrid, _impl_.start_id_),
  PROTOBUF_FIELD_OFFSET(::cc::sprites::SpriteGrid, _impl_.rows_),
  PROTOBUF_FIELD_OFFSET(::cc::sprites::SpriteGrid, _impl_.cols_),
  PROTOBUF_FIELD_OFFSET(::cc::sprites::SpriteGrid, _impl_.cell_w_),
  PROTOBUF_FIELD_OFFSET(::cc::sprites::SpriteGrid, _impl_.cell_h_),
  PROTOBUF_FIELD_OFFSET(::cc::sprites::SpriteGrid, _impl_.origin_),
  PROTOBUF_FIELD_OFFSET(::cc::sprites::SpriteGrid, _impl_.mask_grid_start_id_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::cc::sprites::AnimFrame, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::cc::sprites::AnimFrame, _impl_.sprite_),
  PROTOBUF_FIELD_OFFSET(::cc::sprites::AnimFrame, _impl_.duration_ms_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::cc::sprites::SpriteAnim, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::cc::sprites::SpriteAnim, _impl_.name_),
  PROTOBUF_FIELD_OFFSET(::cc::sprites::SpriteAnim, _impl_.id_),
  PROTOBUF_FIELD_OFFSET(::cc::sprites::SpriteAnim, _impl_.loop_),
  PROTOBUF_FIELD_OFFSET(::cc::sprites::SpriteAnim, _impl_.frames_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::cc::sprites::SpriteSheet, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::cc::sprites::SpriteSheet, _impl_.textures_),
  PROTOBUF_FIELD_OFFSET(::cc::sprites::SpriteSheet, _impl_.sprites_),
  PROTOBUF_FIELD_OFFSET(::cc::sprites::SpriteSheet, _impl_.grids_),
  PROTOBUF_FIELD_OFFSET(::cc::sprites::SpriteSheet, _impl_.animations_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::cc::sprites::SpriteBounds)},
  { 10, -1, -1, sizeof(::cc::sprites::SpriteOrigin)},
  { 18, -1, -1, sizeof(::cc::sprites::SpriteTexture)},
  { 28, -1, -1, sizeof(::cc::sprites::SpriteDef)},
  { 40, -1, -1, sizeof(::cc::sprites::SpriteGrid)},
  { 55, -1, -1, sizeof(::cc::sprites::AnimFrame)},
  { 63, -1, -1, sizeof(::cc::sprites::SpriteAnim)},
  { 73, -1, -1, sizeof(::cc::sprites::SpriteSheet)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::cc::sprites::_SpriteBounds_default_instance_._instance,
  &::cc::sprites::_SpriteOrigin_default_instance_._instance,
  &::cc::sprites::_SpriteTexture_default_instance_._instance,
  &::cc::sprites::_SpriteDef_default_instance_._instance,
  &::cc::sprites::_SpriteGrid_default_instance_._instance,
  &::cc::sprites::_AnimFrame_default_instance_._instance,
  &::cc::sprites::_SpriteAnim_default_instance_._instance,
  &::cc::sprites::_SpriteSheet_default_instance_._instance,
};

const char descriptor_table_protodef_spritedata_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\020spritedata.proto\022\ncc.sprites\"H\n\014Sprite"
  "Bounds\022\014\n\004left\030\001 \001(\005\022\013\n\003top\030\002 \001(\005\022\r\n\005rig"
  "ht\030\003 \001(\005\022\016\n\006bottom\030\004 \001(\005\"$\n\014SpriteOrigin"
  "\022\t\n\001x\030\001 \001(\005\022\t\n\001y\030\002 \001(\005\"H\n\rSpriteTexture\022"
  "\n\n\002id\030\001 \001(\005\022\014\n\004file\030\002 \001(\t\022\r\n\005width\030\003 \001(\005"
  "\022\016\n\006height\030\004 \001(\005\"\237\001\n\tSpriteDef\022\014\n\004name\030\001"
  " \001(\t\022\n\n\002id\030\002 \001(\005\022\017\n\007texture\030\003 \001(\005\022(\n\006bou"
  "nds\030\004 \001(\0132\030.cc.sprites.SpriteBounds\022(\n\006o"
  "rigin\030\005 \001(\0132\030.cc.sprites.SpriteOrigin\022\023\n"
  "\013mask_sprite\030\006 \001(\005\"\301\001\n\nSpriteGrid\022\017\n\007tex"
  "ture\030\001 \001(\005\022\016\n\006prefix\030\002 \001(\t\022\020\n\010start_id\030\003"
  " \001(\005\022\014\n\004rows\030\004 \001(\005\022\014\n\004cols\030\005 \001(\005\022\016\n\006cell"
  "_w\030\006 \001(\005\022\016\n\006cell_h\030\007 \001(\005\022(\n\006origin\030\010 \001(\013"
  "2\030.cc.sprites.SpriteOrigin\022\032\n\022mask_grid_"
  "start_id\030\t \001(\005\"0\n\tAnimFrame\022\016\n\006sprite\030\001 "
  "\001(\005\022\023\n\013duration_ms\030\002 \001(\005\"[\n\nSpriteAnim\022\014"
  "\n\004name\030\001 \001(\t\022\n\n\002id\030\002 \001(\005\022\014\n\004loop\030\003 \001(\010\022%"
  "\n\006frames\030\004 \003(\0132\025.cc.sprites.AnimFrame\"\265\001"
  "\n\013SpriteSheet\022+\n\010textures\030\001 \003(\0132\031.cc.spr"
  "ites.SpriteTexture\022&\n\007sprites\030\002 \003(\0132\025.cc"
  ".sprites.SpriteDef\022%\n\005grids\030\003 \003(\0132\026.cc.s"
  "prites.SpriteGrid\022*\n\nanimations\030\004 \003(\0132\026."
  "cc.sprites.SpriteAnimb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_spritedata_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_spritedata_2eproto = {
    false, false, 909, descriptor_table_protodef_spritedata_2eproto,
    "spritedata.proto",
    &descriptor_table_spritedata_2eproto_once, nullptr, 0, 8,
    schemas, file_default_instances, TableStruct_spritedata_2eproto::offsets,
    file_level_metadata_spritedata_2eproto, file_level_enum_descriptors_spritedata_2eproto,
    file_level_service_descriptors_spritedata_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_spritedata_2eproto_getter() {
  return &descriptor_table_spritedata_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_spritedata_2eproto(&descriptor_table_spritedata_2eproto);
namespace cc {
namespace sprites {

// ===================================================================

class SpriteBounds::_Internal {
 public:
};

SpriteBounds::SpriteBounds(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:cc.sprites.SpriteBounds)
}
SpriteBounds::SpriteBounds(const SpriteBounds& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SpriteBounds* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.left_){}
    , decltype(_impl_.top_){}
    , decltype(_impl_.right_){}
    , decltype(_impl_.bottom_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.left_, &from._impl_.left_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.bottom_) -
    reinterpret_cast<char*>(&_impl_.left_)) + sizeof(_impl_.bottom_));
  // @@protoc_insertion_point(copy_constructor:cc.sprites.SpriteBounds)
}

inline void SpriteBounds::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.left_){0}
    , decltype(_impl_.top_){0}
    , decltype(_impl_.right_){0}
    , decltype(_impl_.bottom_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

SpriteBounds::~SpriteBounds() {
  // @@protoc_insertion_point(destructor:cc.sprites.SpriteBounds)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SpriteBounds::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void SpriteBounds::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SpriteBounds::Clear() {
// @@protoc_insertion_point(message_clear_start:cc.sprites.SpriteBounds)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.left_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.bottom_) -
      reinterpret_cast<char*>(&_impl_.left_)) + sizeof(_impl_.bottom_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SpriteBounds::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 left = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.left_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 top = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.top_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 right = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.right_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 bottom = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.bottom_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SpriteBounds::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:cc.sprites.SpriteBounds)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 left = 1;
  if (this->_internal_left() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_left(), target);
  }

  // int32 top = 2;
  if (this->_internal_top() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_top(), target);
  }

  // int32 right = 3;
  if (this->_internal_right() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(3, this->_internal_right(), target);
  }

  // int32 bottom = 4;
  if (this->_internal_bottom() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(4, this->_internal_bottom(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cc.sprites.SpriteBounds)
  return target;
}

size_t SpriteBounds::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:cc.sprites.SpriteBounds)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 left = 1;
  if (this->_internal_left() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_left());
  }

  // int32 top = 2;
  if (this->_internal_top() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_top());
  }

  // int32 right = 3;
  if (this->_internal_right() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_right());
  }

  // int32 bottom = 4;
  if (this->_internal_bottom() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_bottom());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SpriteBounds::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SpriteBounds::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SpriteBounds::GetClassData() const { return &_class_data_; }


void SpriteBounds::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SpriteBounds*>(&to_msg);
  auto& from = static_cast<const SpriteBounds&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:cc.sprites.SpriteBounds)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_left() != 0) {
    _this->_internal_set_left(from._internal_left());
  }
  if (from._internal_top() != 0) {
    _this->_internal_set_top(from._internal_top());
  }
  if (from._internal_right() != 0) {
    _this->_internal_set_right(from._internal_right());
  }
  if (from._internal_bottom() != 0) {
    _this->_internal_set_bottom(from._internal_bottom());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SpriteBounds::CopyFrom(const SpriteBounds& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cc.sprites.SpriteBounds)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SpriteBounds::IsInitialized() const {
  return true;
}

void SpriteBounds::InternalSwap(SpriteBounds* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SpriteBounds, _impl_.bottom_)
      + sizeof(SpriteBounds::_impl_.bottom_)
      - PROTOBUF_FIELD_OFFSET(SpriteBounds, _impl_.left_)>(
          reinterpret_cast<char*>(&_impl_.left_),
          reinterpret_cast<char*>(&other->_impl_.left_));
}

::PROTOBUF_NAMESPACE_ID::Metadata SpriteBounds::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_spritedata_2eproto_getter, &descriptor_table_spritedata_2eproto_once,
      file_level_metadata_spritedata_2eproto[0]);
}

// ===================================================================

class SpriteOrigin::_Internal {
 public:
};

SpriteOrigin::SpriteOrigin(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:cc.sprites.SpriteOrigin)
}
SpriteOrigin::SpriteOrigin(const SpriteOrigin& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SpriteOrigin* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.x_){}
    , decltype(_impl_.y_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.x_, &from._impl_.x_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.y_) -
    reinterpret_cast<char*>(&_impl_.x_)) + sizeof(_impl_.y_));
  // @@protoc_insertion_point(copy_constructor:cc.sprites.SpriteOrigin)
}

inline void SpriteOrigin::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.x_){0}
    , decltype(_impl_.y_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

SpriteOrigin::~SpriteOrigin() {
  // @@protoc_insertion_point(destructor:cc.sprites.SpriteOrigin)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SpriteOrigin::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void SpriteOrigin::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SpriteOrigin::Clear() {
// @@protoc_insertion_point(message_clear_start:cc.sprites.SpriteOrigin)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.x_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.y_) -
      reinterpret_cast<char*>(&_impl_.x_)) + sizeof(_impl_.y_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SpriteOrigin::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 x = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.x_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 y = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.y_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SpriteOrigin::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:cc.sprites.SpriteOrigin)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 x = 1;
  if (this->_internal_x() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_x(), target);
  }

  // int32 y = 2;
  if (this->_internal_y() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_y(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cc.sprites.SpriteOrigin)
  return target;
}

size_t SpriteOrigin::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:cc.sprites.SpriteOrigin)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 x = 1;
  if (this->_internal_x() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_x());
  }

  // int32 y = 2;
  if (this->_internal_y() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_y());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SpriteOrigin::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SpriteOrigin::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SpriteOrigin::GetClassData() const { return &_class_data_; }


void SpriteOrigin::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SpriteOrigin*>(&to_msg);
  auto& from = static_cast<const SpriteOrigin&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:cc.sprites.SpriteOrigin)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_x() != 0) {
    _this->_internal_set_x(from._internal_x());
  }
  if (from._internal_y() != 0) {
    _this->_internal_set_y(from._internal_y());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SpriteOrigin::CopyFrom(const SpriteOrigin& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cc.sprites.SpriteOrigin)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SpriteOrigin::IsInitialized() const {
  return true;
}

void SpriteOrigin::InternalSwap(SpriteOrigin* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SpriteOrigin, _impl_.y_)
      + sizeof(SpriteOrigin::_impl_.y_)
      - PROTOBUF_FIELD_OFFSET(SpriteOrigin, _impl_.x_)>(
          reinterpret_cast<char*>(&_impl_.x_),
          reinterpret_cast<char*>(&other->_impl_.x_));
}

::PROTOBUF_NAMESPACE_ID::Metadata SpriteOrigin::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_spritedata_2eproto_getter, &descriptor_table_spritedata_2eproto_once,
      file_level_metadata_spritedata_2eproto[1]);
}

// ===================================================================

class SpriteTexture::_Internal {
 public:
};

SpriteTexture::SpriteTexture(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:cc.sprites.SpriteTexture)
}
SpriteTexture::SpriteTexture(const SpriteTexture& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SpriteTexture* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.file_){}
    , decltype(_impl_.id_){}
    , decltype(_impl_.width_){}
    , decltype(_impl_.height_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.file_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.file_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_file().empty()) {
    _this->_impl_.file_.Set(from._internal_file(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.id_, &from._impl_.id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.height_) -
    reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.height_));
  // @@protoc_insertion_point(copy_constructor:cc.sprites.SpriteTexture)
}

inline void SpriteTexture::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.file_){}
    , decltype(_impl_.id_){0}
    , decltype(_impl_.width_){0}
    , decltype(_impl_.height_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.file_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.file_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

SpriteTexture::~SpriteTexture() {
  // @@protoc_insertion_point(destructor:cc.sprites.SpriteTexture)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SpriteTexture::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.file_.Destroy();
}

void SpriteTexture::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SpriteTexture::Clear() {
// @@protoc_insertion_point(message_clear_start:cc.sprites.SpriteTexture)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.file_.ClearToEmpty();
  ::memset(&_impl_.id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.height_) -
      reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.height_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SpriteTexture::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string file = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_file();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "cc.sprites.SpriteTexture.file"));
        } else
          goto handle_unusual;
        continue;
      // int32 width = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.width_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 height = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.height_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SpriteTexture::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:cc.sprites.SpriteTexture)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 id = 1;
  if (this->_internal_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_id(), target);
  }

  // string file = 2;
  if (!this->_internal_file().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_file().data(), static_cast<int>(this->_internal_file().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "cc.sprites.SpriteTexture.file");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_file(), target);
  }

  // int32 width = 3;
  if (this->_internal_width() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(3, this->_internal_width(), target);
  }

  // int32 height = 4;
  if (this->_internal_height() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(4, this->_internal_height(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cc.sprites.SpriteTexture)
  return target;
}

size_t SpriteTexture::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:cc.sprites.SpriteTexture)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string file = 2;
  if (!this->_internal_file().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_file());
  }

  // int32 id = 1;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_id());
  }

  // int32 width = 3;
  if (this->_internal_width() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_width());
  }

  // int32 height = 4;
  if (this->_internal_height() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_height());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SpriteTexture::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SpriteTexture::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SpriteTexture::GetClassData() const { return &_class_data_; }


void SpriteTexture::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SpriteTexture*>(&to_msg);
  auto& from = static_cast<const SpriteTexture&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:cc.sprites.SpriteTexture)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_file().empty()) {
    _this->_internal_set_file(from._internal_file());
  }
  if (from._internal_id() != 0) {
    _this->_internal_set_id(from._internal_id());
  }
  if (from._internal_width() != 0) {
    _this->_internal_set_width(from._internal_width());
  }
  if (from._internal_height() != 0) {
    _this->_internal_set_height(from._internal_height());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SpriteTexture::CopyFrom(const SpriteTexture& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cc.sprites.SpriteTexture)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SpriteTexture::IsInitialized() const {
  return true;
}

void SpriteTexture::InternalSwap(SpriteTexture* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.file_, lhs_arena,
      &other->_impl_.file_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SpriteTexture, _impl_.height_)
      + sizeof(SpriteTexture::_impl_.height_)
      - PROTOBUF_FIELD_OFFSET(SpriteTexture, _impl_.id_)>(
          reinterpret_cast<char*>(&_impl_.id_),
          reinterpret_cast<char*>(&other->_impl_.id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata SpriteTexture::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_spritedata_2eproto_getter, &descriptor_table_spritedata_2eproto_once,
      file_level_metadata_spritedata_2eproto[2]);
}

// ===================================================================

class SpriteDef::_Internal {
 public:
  static const ::cc::sprites::SpriteBounds& bounds(const SpriteDef* msg);
  static const ::cc::sprites::SpriteOrigin& origin(const SpriteDef* msg);
};

const ::cc::sprites::SpriteBounds&
SpriteDef::_Internal::bounds(const SpriteDef* msg) {
  return *msg->_impl_.bounds_;
}
const ::cc::sprites::SpriteOrigin&
SpriteDef::_Internal::origin(const SpriteDef* msg) {
  return *msg->_impl_.origin_;
}
SpriteDef::SpriteDef(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:cc.sprites.SpriteDef)
}
SpriteDef::SpriteDef(const SpriteDef& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SpriteDef* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.name_){}
    , decltype(_impl_.bounds_){nullptr}
    , decltype(_impl_.origin_){nullptr}
    , decltype(_impl_.id_){}
    , decltype(_impl_.texture_){}
    , decltype(_impl_.mask_sprite_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_name().empty()) {
    _this->_impl_.name_.Set(from._internal_name(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_bounds()) {
    _this->_impl_.bounds_ = new ::cc::sprites::SpriteBounds(*from._impl_.bounds_);
  }
  if (from._internal_has_origin()) {
    _this->_impl_.origin_ = new ::cc::sprites::SpriteOrigin(*from._impl_.origin_);
  }
  ::memcpy(&_impl_.id_, &from._impl_.id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.mask_sprite_) -
    reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.mask_sprite_));
  // @@protoc_insertion_point(copy_constructor:cc.sprites.SpriteDef)
}

inline void SpriteDef::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.name_){}
    , decltype(_impl_.bounds_){nullptr}
    , decltype(_impl_.origin_){nullptr}
    , decltype(_impl_.id_){0}
    , decltype(_impl_.texture_){0}
    , decltype(_impl_.mask_sprite_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

SpriteDef::~SpriteDef() {
  // @@protoc_insertion_point(destructor:cc.sprites.SpriteDef)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SpriteDef::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.name_.Destroy();
  if (this != internal_default_instance()) delete _impl_.bounds_;
  if (this != internal_default_instance()) delete _impl_.origin_;
}

void SpriteDef::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SpriteDef::Clear() {
// @@protoc_insertion_point(message_clear_start:cc.sprites.SpriteDef)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.name_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && _impl_.bounds_ != nullptr) {
    delete _impl_.bounds_;
  }
  _impl_.bounds_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.origin_ != nullptr) {
    delete _impl_.origin_;
  }
  _impl_.origin_ = nullptr;
  ::memset(&_impl_.id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.mask_sprite_) -
      reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.mask_sprite_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SpriteDef::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "cc.sprites.SpriteDef.name"));
        } else
          goto handle_unusual;
        continue;
      // int32 id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 texture = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.texture_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .cc.sprites.SpriteBounds bounds = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_bounds(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .cc.sprites.SpriteOrigin origin = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_origin(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 mask_sprite = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _impl_.mask_sprite_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SpriteDef::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:cc.sprites.SpriteDef)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_name().data(), static_cast<int>(this->_internal_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "cc.sprites.SpriteDef.name");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_name(), target);
  }

  // int32 id = 2;
  if (this->_internal_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_id(), target);
  }

  // int32 texture = 3;
  if (this->_internal_texture() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(3, this->_internal_texture(), target);
  }

  // .cc.sprites.SpriteBounds bounds = 4;
  if (this->_internal_has_bounds()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, _Internal::bounds(this),
        _Internal::bounds(this).GetCachedSize(), target, stream);
  }

  // .cc.sprites.SpriteOrigin origin = 5;
  if (this->_internal_has_origin()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(5, _Internal::origin(this),
        _Internal::origin(this).GetCachedSize(), target, stream);
  }

  // int32 mask_sprite = 6;
  if (this->_internal_mask_sprite() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(6, this->_internal_mask_sprite(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cc.sprites.SpriteDef)
  return target;
}

size_t SpriteDef::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:cc.sprites.SpriteDef)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_name());
  }

  // .cc.sprites.SpriteBounds bounds = 4;
  if (this->_internal_has_bounds()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.bounds_);
  }

  // .cc.sprites.SpriteOrigin origin = 5;
  if (this->_internal_has_origin()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.origin_);
  }

  // int32 id = 2;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_id());
  }

  // int32 texture = 3;
  if (this->_internal_texture() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_texture());
  }

  // int32 mask_sprite = 6;
  if (this->_internal_mask_sprite() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_mask_sprite());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SpriteDef::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SpriteDef::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SpriteDef::GetClassData() const { return &_class_data_; }


void SpriteDef::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SpriteDef*>(&to_msg);
  auto& from = static_cast<const SpriteDef&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:cc.sprites.SpriteDef)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  if (from._internal_has_bounds()) {
    _this->_internal_mutable_bounds()->::cc::sprites::SpriteBounds::MergeFrom(
        from._internal_bounds());
  }
  if (from._internal_has_origin()) {
    _this->_internal_mutable_origin()->::cc::sprites::SpriteOrigin::MergeFrom(
        from._internal_origin());
  }
  if (from._internal_id() != 0) {
    _this->_internal_set_id(from._internal_id());
  }
  if (from._internal_texture() != 0) {
    _this->_internal_set_texture(from._internal_texture());
  }
  if (from._internal_mask_sprite() != 0) {
    _this->_internal_set_mask_sprite(from._internal_mask_sprite());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SpriteDef::CopyFrom(const SpriteDef& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cc.sprites.SpriteDef)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SpriteDef::IsInitialized() const {
  return true;
}

void SpriteDef::InternalSwap(SpriteDef* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.name_, lhs_arena,
      &other->_impl_.name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SpriteDef, _impl_.mask_sprite_)
      + sizeof(SpriteDef::_impl_.mask_sprite_)
      - PROTOBUF_FIELD_OFFSET(SpriteDef, _impl_.bounds_)>(
          reinterpret_cast<char*>(&_impl_.bounds_),
          reinterpret_cast<char*>(&other->_impl_.bounds_));
}

::PROTOBUF_NAMESPACE_ID::Metadata SpriteDef::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_spritedata_2eproto_getter, &descriptor_table_spritedata_2eproto_once,
      file_level_metadata_spritedata_2eproto[3]);
}

// ===================================================================

class SpriteGrid::_Internal {
 public:
  static const ::cc::sprites::SpriteOrigin& origin(const SpriteGrid* msg);
};

const ::cc::sprites::SpriteOrigin&
SpriteGrid::_Internal::origin(const SpriteGrid* msg) {
  return *msg->_impl_.origin_;
}
SpriteGrid::SpriteGrid(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:cc.sprites.SpriteGrid)
}
SpriteGrid::SpriteGrid(const SpriteGrid& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SpriteGrid* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.prefix_){}
    , decltype(_impl_.origin_){nullptr}
    , decltype(_impl_.texture_){}
    , decltype(_impl_.start_id_){}
    , decltype(_impl_.rows_){}
    , decltype(_impl_.cols_){}
    , decltype(_impl_.cell_w_){}
    , decltype(_impl_.cell_h_){}
    , decltype(_impl_.mask_grid_start_id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.prefix_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.prefix_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_prefix().empty()) {
    _this->_impl_.prefix_.Set(from._internal_prefix(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_origin()) {
    _this->_impl_.origin_ = new ::cc::sprites::SpriteOrigin(*from._impl_.origin_);
  }
  ::memcpy(&_impl_.texture_, &from._impl_.texture_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.mask_grid_start_id_) -
    reinterpret_cast<char*>(&_impl_.texture_)) + sizeof(_impl_.mask_grid_start_id_));
  // @@protoc_insertion_point(copy_constructor:cc.sprites.SpriteGrid)
}

inline void SpriteGrid::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.prefix_){}
    , decltype(_impl_.origin_){nullptr}
    , decltype(_impl_.texture_){0}
    , decltype(_impl_.start_id_){0}
    , decltype(_impl_.rows_){0}
    , decltype(_impl_.cols_){0}
    , decltype(_impl_.cell_w_){0}
    , decltype(_impl_.cell_h_){0}
    , decltype(_impl_.mask_grid_start_id_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.prefix_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.prefix_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

SpriteGrid::~SpriteGrid() {
  // @@protoc_insertion_point(destructor:cc.sprites.SpriteGrid)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SpriteGrid::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.prefix_.Destroy();
  if (this != internal_default_instance()) delete _impl_.origin_;
}

void SpriteGrid::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SpriteGrid::Clear() {
// @@protoc_insertion_point(message_clear_start:cc.sprites.SpriteGrid)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.prefix_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && _impl_.origin_ != nullptr) {
    delete _impl_.origin_;
  }
  _impl_.origin_ = nullptr;
  ::memset(&_impl_.texture_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.mask_grid_start_id_) -
      reinterpret_cast<char*>(&_impl_.texture_)) + sizeof(_impl_.mask_grid_start_id_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SpriteGrid::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 texture = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.texture_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string prefix = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_prefix();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "cc.sprites.SpriteGrid.prefix"));
        } else
          goto handle_unusual;
        continue;
      // int32 start_id = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.start_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 rows = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.rows_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 cols = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.cols_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 cell_w = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _impl_.cell_w_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 cell_h = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 56)) {
          _impl_.cell_h_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .cc.sprites.SpriteOrigin origin = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 66)) {
          ptr = ctx->ParseMessage(_internal_mutable_origin(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 mask_grid_start_id = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 72)) {
          _impl_.mask_grid_start_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SpriteGrid::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:cc.sprites.SpriteGrid)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 texture = 1;
  if (this->_internal_texture() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_texture(), target);
  }

  // string prefix = 2;
  if (!this->_internal_prefix().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_prefix().data(), static_cast<int>(this->_internal_prefix().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "cc.sprites.SpriteGrid.prefix");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_prefix(), target);
  }

  // int32 start_id = 3;
  if (this->_internal_start_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(3, this->_internal_start_id(), target);
  }

  // int32 rows = 4;
  if (this->_internal_rows() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(4, this->_internal_rows(), target);
  }

  // int32 cols = 5;
  if (this->_internal_cols() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(5, this->_internal_cols(), target);
  }

  // int32 cell_w = 6;
  if (this->_internal_cell_w() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(6, this->_internal_cell_w(), target);
  }

  // int32 cell_h = 7;
  if (this->_internal_cell_h() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(7, this->_internal_cell_h(), target);
  }

  // .cc.sprites.SpriteOrigin origin = 8;
  if (this->_internal_has_origin()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(8, _Internal::origin(this),
        _Internal::origin(this).GetCachedSize(), target, stream);
  }

  // int32 mask_grid_start_id = 9;
  if (this->_internal_mask_grid_start_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(9, this->_internal_mask_grid_start_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cc.sprites.SpriteGrid)
  return target;
}

size_t SpriteGrid::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:cc.sprites.SpriteGrid)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string prefix = 2;
  if (!this->_internal_prefix().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_prefix());
  }

  // .cc.sprites.SpriteOrigin origin = 8;
  if (this->_internal_has_origin()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.origin_);
  }

  // int32 texture = 1;
  if (this->_internal_texture() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_texture());
  }

  // int32 start_id = 3;
  if (this->_internal_start_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_start_id());
  }

  // int32 rows = 4;
  if (this->_internal_rows() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_rows());
  }

  // int32 cols = 5;
  if (this->_internal_cols() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_cols());
  }

  // int32 cell_w = 6;
  if (this->_internal_cell_w() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_cell_w());
  }

  // int32 cell_h = 7;
  if (this->_internal_cell_h() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_cell_h());
  }

  // int32 mask_grid_start_id = 9;
  if (this->_internal_mask_grid_start_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_mask_grid_start_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SpriteGrid::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SpriteGrid::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SpriteGrid::GetClassData() const { return &_class_data_; }


void SpriteGrid::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SpriteGrid*>(&to_msg);
  auto& from = static_cast<const SpriteGrid&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:cc.sprites.SpriteGrid)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_prefix().empty()) {
    _this->_internal_set_prefix(from._internal_prefix());
  }
  if (from._internal_has_origin()) {
    _this->_internal_mutable_origin()->::cc::sprites::SpriteOrigin::MergeFrom(
        from._internal_origin());
  }
  if (from._internal_texture() != 0) {
    _this->_internal_set_texture(from._internal_texture());
  }
  if (from._internal_start_id() != 0) {
    _this->_internal_set_start_id(from._internal_start_id());
  }
  if (from._internal_rows() != 0) {
    _this->_internal_set_rows(from._internal_rows());
  }
  if (from._internal_cols() != 0) {
    _this->_internal_set_cols(from._internal_cols());
  }
  if (from._internal_cell_w() != 0) {
    _this->_internal_set_cell_w(from._internal_cell_w());
  }
  if (from._internal_cell_h() != 0) {
    _this->_internal_set_cell_h(from._internal_cell_h());
  }
  if (from._internal_mask_grid_start_id() != 0) {
    _this->_internal_set_mask_grid_start_id(from._internal_mask_grid_start_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SpriteGrid::CopyFrom(const SpriteGrid& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cc.sprites.SpriteGrid)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SpriteGrid::IsInitialized() const {
  return true;
}

void SpriteGrid::InternalSwap(SpriteGrid* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.prefix_, lhs_arena,
      &other->_impl_.prefix_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SpriteGrid, _impl_.mask_grid_start_id_)
      + sizeof(SpriteGrid::_impl_.mask_grid_start_id_)
      - PROTOBUF_FIELD_OFFSET(SpriteGrid, _impl_.origin_)>(
          reinterpret_cast<char*>(&_impl_.origin_),
          reinterpret_cast<char*>(&other->_impl_.origin_));
}

::PROTOBUF_NAMESPACE_ID::Metadata SpriteGrid::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_spritedata_2eproto_getter, &descriptor_table_spritedata_2eproto_once,
      file_level_metadata_spritedata_2eproto[4]);
}

// ===================================================================

class AnimFrame::_Internal {
 public:
};

AnimFrame::AnimFrame(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:cc.sprites.AnimFrame)
}
AnimFrame::AnimFrame(const AnimFrame& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  AnimFrame* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.sprite_){}
    , decltype(_impl_.duration_ms_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.sprite_, &from._impl_.sprite_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.duration_ms_) -
    reinterpret_cast<char*>(&_impl_.sprite_)) + sizeof(_impl_.duration_ms_));
  // @@protoc_insertion_point(copy_constructor:cc.sprites.AnimFrame)
}

inline void AnimFrame::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.sprite_){0}
    , decltype(_impl_.duration_ms_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

AnimFrame::~AnimFrame() {
  // @@protoc_insertion_point(destructor:cc.sprites.AnimFrame)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void AnimFrame::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void AnimFrame::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void AnimFrame::Clear() {
// @@protoc_insertion_point(message_clear_start:cc.sprites.AnimFrame)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.sprite_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.duration_ms_) -
      reinterpret_cast<char*>(&_impl_.sprite_)) + sizeof(_impl_.duration_ms_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* AnimFrame::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 sprite = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.sprite_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 duration_ms = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.duration_ms_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* AnimFrame::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:cc.sprites.AnimFrame)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 sprite = 1;
  if (this->_internal_sprite() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_sprite(), target);
  }

  // int32 duration_ms = 2;
  if (this->_internal_duration_ms() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_duration_ms(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cc.sprites.AnimFrame)
  return target;
}

size_t AnimFrame::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:cc.sprites.AnimFrame)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 sprite = 1;
  if (this->_internal_sprite() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_sprite());
  }

  // int32 duration_ms = 2;
  if (this->_internal_duration_ms() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_duration_ms());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData AnimFrame::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    AnimFrame::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*AnimFrame::GetClassData() const { return &_class_data_; }


void AnimFrame::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<AnimFrame*>(&to_msg);
  auto& from = static_cast<const AnimFrame&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:cc.sprites.AnimFrame)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_sprite() != 0) {
    _this->_internal_set_sprite(from._internal_sprite());
  }
  if (from._internal_duration_ms() != 0) {
    _this->_internal_set_duration_ms(from._internal_duration_ms());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void AnimFrame::CopyFrom(const AnimFrame& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cc.sprites.AnimFrame)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AnimFrame::IsInitialized() const {
  return true;
}

void AnimFrame::InternalSwap(AnimFrame* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(AnimFrame, _impl_.duration_ms_)
      + sizeof(AnimFrame::_impl_.duration_ms_)
      - PROTOBUF_FIELD_OFFSET(AnimFrame, _impl_.sprite_)>(
          reinterpret_cast<char*>(&_impl_.sprite_),
          reinterpret_cast<char*>(&other->_impl_.sprite_));
}

::PROTOBUF_NAMESPACE_ID::Metadata AnimFrame::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_spritedata_2eproto_getter, &descriptor_table_spritedata_2eproto_once,
      file_level_metadata_spritedata_2eproto[5]);
}

// ===================================================================

class SpriteAnim::_Internal {
 public:
};

SpriteAnim::SpriteAnim(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:cc.sprites.SpriteAnim)
}
SpriteAnim::SpriteAnim(const SpriteAnim& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SpriteAnim* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.frames_){from._impl_.frames_}
    , decltype(_impl_.name_){}
    , decltype(_impl_.id_){}
    , decltype(_impl_.loop_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_name().empty()) {
    _this->_impl_.name_.Set(from._internal_name(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.id_, &from._impl_.id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.loop_) -
    reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.loop_));
  // @@protoc_insertion_point(copy_constructor:cc.sprites.SpriteAnim)
}

inline void SpriteAnim::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.frames_){arena}
    , decltype(_impl_.name_){}
    , decltype(_impl_.id_){0}
    , decltype(_impl_.loop_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

SpriteAnim::~SpriteAnim() {
  // @@protoc_insertion_point(destructor:cc.sprites.SpriteAnim)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SpriteAnim::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.frames_.~RepeatedPtrField();
  _impl_.name_.Destroy();
}

void SpriteAnim::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SpriteAnim::Clear() {
// @@protoc_insertion_point(message_clear_start:cc.sprites.SpriteAnim)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.frames_.Clear();
  _impl_.name_.ClearToEmpty();
  ::memset(&_impl_.id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.loop_) -
      reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.loop_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SpriteAnim::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "cc.sprites.SpriteAnim.name"));
        } else
          goto handle_unusual;
        continue;
      // int32 id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool loop = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.loop_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .cc.sprites.AnimFrame frames = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_frames(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<34>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SpriteAnim::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:cc.sprites.SpriteAnim)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_name().data(), static_cast<int>(this->_internal_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "cc.sprites.SpriteAnim.name");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_name(), target);
  }

  // int32 id = 2;
  if (this->_internal_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_id(), target);
  }

  // bool loop = 3;
  if (this->_internal_loop() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(3, this->_internal_loop(), target);
  }

  // repeated .cc.sprites.AnimFrame frames = 4;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_frames_size()); i < n; i++) {
    const auto& repfield = this->_internal_frames(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(4, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cc.sprites.SpriteAnim)
  return target;
}

size_t SpriteAnim::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:cc.sprites.SpriteAnim)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .cc.sprites.AnimFrame frames = 4;
  total_size += 1UL * this->_internal_frames_size();
  for (const auto& msg : this->_impl_.frames_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // string name = 1;
  if (!this->_internal_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_name());
  }

  // int32 id = 2;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_id());
  }

  // bool loop = 3;
  if (this->_internal_loop() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SpriteAnim::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SpriteAnim::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SpriteAnim::GetClassData() const { return &_class_data_; }


void SpriteAnim::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SpriteAnim*>(&to_msg);
  auto& from = static_cast<const SpriteAnim&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:cc.sprites.SpriteAnim)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.frames_.MergeFrom(from._impl_.frames_);
  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  if (from._internal_id() != 0) {
    _this->_internal_set_id(from._internal_id());
  }
  if (from._internal_loop() != 0) {
    _this->_internal_set_loop(from._internal_loop());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SpriteAnim::CopyFrom(const SpriteAnim& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cc.sprites.SpriteAnim)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SpriteAnim::IsInitialized() const {
  return true;
}

void SpriteAnim::InternalSwap(SpriteAnim* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.frames_.InternalSwap(&other->_impl_.frames_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.name_, lhs_arena,
      &other->_impl_.name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SpriteAnim, _impl_.loop_)
      + sizeof(SpriteAnim::_impl_.loop_)
      - PROTOBUF_FIELD_OFFSET(SpriteAnim, _impl_.id_)>(
          reinterpret_cast<char*>(&_impl_.id_),
          reinterpret_cast<char*>(&other->_impl_.id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata SpriteAnim::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_spritedata_2eproto_getter, &descriptor_table_spritedata_2eproto_once,
      file_level_metadata_spritedata_2eproto[6]);
}

// ===================================================================

class SpriteSheet::_Internal {
 public:
};

SpriteSheet::SpriteSheet(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:cc.sprites.SpriteSheet)
}
SpriteSheet::SpriteSheet(const SpriteSheet& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SpriteSheet* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.textures_){from._impl_.textures_}
    , decltype(_impl_.sprites_){from._impl_.sprites_}
    , decltype(_impl_.grids_){from._impl_.grids_}
    , decltype(_impl_.animations_){from._impl_.animations_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:cc.sprites.SpriteSheet)
}

inline void SpriteSheet::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.textures_){arena}
    , decltype(_impl_.sprites_){arena}
    , decltype(_impl_.grids_){arena}
    , decltype(_impl_.animations_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

SpriteSheet::~SpriteSheet() {
  // @@protoc_insertion_point(destructor:cc.sprites.SpriteSheet)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SpriteSheet::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.textures_.~RepeatedPtrField();
  _impl_.sprites_.~RepeatedPtrField();
  _impl_.grids_.~RepeatedPtrField();
  _impl_.animations_.~RepeatedPtrField();
}

void SpriteSheet::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SpriteSheet::Clear() {
// @@protoc_insertion_point(message_clear_start:cc.sprites.SpriteSheet)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.textures_.Clear();
  _impl_.sprites_.Clear();
  _impl_.grids_.Clear();
  _impl_.animations_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SpriteSheet::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .cc.sprites.SpriteTexture textures = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_textures(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      // repeated .cc.sprites.SpriteDef sprites = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_sprites(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else
          goto handle_unusual;
        continue;
      // repeated .cc.sprites.SpriteGrid grids = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_grids(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else
          goto handle_unusual;
        continue;
      // repeated .cc.sprites.SpriteAnim animations = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_animations(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<34>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SpriteSheet::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:cc.sprites.SpriteSheet)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .cc.sprites.SpriteTexture textures = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_textures_size()); i < n; i++) {
    const auto& repfield = this->_internal_textures(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  // repeated .cc.sprites.SpriteDef sprites = 2;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_sprites_size()); i < n; i++) {
    const auto& repfield = this->_internal_sprites(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(2, repfield, repfield.GetCachedSize(), target, stream);
  }

  // repeated .cc.sprites.SpriteGrid grids = 3;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_grids_size()); i < n; i++) {
    const auto& repfield = this->_internal_grids(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(3, repfield, repfield.GetCachedSize(), target, stream);
  }

  // repeated .cc.sprites.SpriteAnim animations = 4;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_animations_size()); i < n; i++) {
    const auto& repfield = this->_internal_animations(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(4, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cc.sprites.SpriteSheet)
  return target;
}

size_t SpriteSheet::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:cc.sprites.SpriteSheet)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .cc.sprites.SpriteTexture textures = 1;
  total_size += 1UL * this->_internal_textures_size();
  for (const auto& msg : this->_impl_.textures_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .cc.sprites.SpriteDef sprites = 2;
  total_size += 1UL * this->_internal_sprites_size();
  for (const auto& msg : this->_impl_.sprites_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .cc.sprites.SpriteGrid grids = 3;
  total_size += 1UL * this->_internal_grids_size();
  for (const auto& msg : this->_impl_.grids_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .cc.sprites.SpriteAnim animations = 4;
  total_size += 1UL * this->_internal_animations_size();
  for (const auto& msg : this->_impl_.animations_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SpriteSheet::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SpriteSheet::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SpriteSheet::GetClassData() const { return &_class_data_; }


void SpriteSheet::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SpriteSheet*>(&to_msg);
  auto& from = static_cast<const SpriteSheet&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:cc.sprites.SpriteSheet)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.textures_.MergeFrom(from._impl_.textures_);
  _this->_impl_.sprites_.MergeFrom(from._impl_.sprites_);
  _this->_impl_.grids_.MergeFrom(from._impl_.grids_);
  _this->_impl_.animations_.MergeFrom(from._impl_.animations_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SpriteSheet::CopyFrom(const SpriteSheet& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cc.sprites.SpriteSheet)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SpriteSheet::IsInitialized() const {
  return true;
}

void SpriteSheet::InternalSwap(SpriteSheet* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.textures_.InternalSwap(&other->_impl_.textures_);
  _impl_.sprites_.InternalSwap(&other->_impl_.sprites_);
  _impl_.grids_.InternalSwap(&other->_impl_.grids_);
  _impl_.animations_.InternalSwap(&other->_impl_.animations_);
}

::PROTOBUF_NAMESPACE_ID::Metadata SpriteSheet::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_spritedata_2eproto_getter, &descriptor_table_spritedata_2eproto_once,
      file_level_metadata_spritedata_2eproto[7]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace sprites
}  // namespace cc
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::cc::sprites::SpriteBounds*
Arena::CreateMaybeMessage< ::cc::sprites::SpriteBounds >(Arena* arena) {
  return Arena::CreateMessageInternal< ::cc::sprites::SpriteBounds >(arena);
}
template<> PROTOBUF_NOINLINE ::cc::sprites::SpriteOrigin*
Arena::CreateMaybeMessage< ::cc::sprites::SpriteOrigin >(Arena* arena) {
  return Arena::CreateMessageInternal< ::cc::sprites::SpriteOrigin >(arena);
}
template<> PROTOBUF_NOINLINE ::cc::sprites::SpriteTexture*
Arena::CreateMaybeMessage< ::cc::sprites::SpriteTexture >(Arena* arena) {
  return Arena::CreateMessageInternal< ::cc::sprites::SpriteTexture >(arena);
}
template<> PROTOBUF_NOINLINE ::cc::sprites::SpriteDef*
Arena::CreateMaybeMessage< ::cc::sprites::SpriteDef >(Arena* arena) {
  return Arena::CreateMessageInternal< ::cc::sprites::SpriteDef >(arena);
}
template<> PROTOBUF_NOINLINE ::cc::sprites::SpriteGrid*
Arena::CreateMaybeMessage< ::cc::sprites::SpriteGrid >(Arena* arena) {
  return Arena::CreateMessageInternal< ::cc::sprites::SpriteGrid >(arena);
}
template<> PROTOBUF_NOINLINE ::cc::sprites::AnimFrame*
Arena::CreateMaybeMessage< ::cc::sprites::AnimFrame >(Arena* arena) {
  return Arena::CreateMessageInternal< ::cc::sprites::AnimFrame >(arena);
}
template<> PROTOBUF_NOINLINE ::cc::sprites::SpriteAnim*
Arena::CreateMaybeMessage< ::cc::sprites::SpriteAnim >(Arena* arena) {
  return Arena::CreateMessageInternal< ::cc::sprites::SpriteAnim >(arena);
}
template<> PROTOBUF_NOINLINE ::cc::sprites::SpriteSheet*
Arena::CreateMaybeMessage< ::cc::sprites::SpriteSheet >(Arena* arena) {
  return Arena::CreateMessageInternal< ::cc::sprites::SpriteSheet >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
