// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: spritedata.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_spritedata_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_spritedata_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_spritedata_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_spritedata_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_spritedata_2eproto;
namespace cc {
namespace sprites {
class AnimFrame;
struct AnimFrameDefaultTypeInternal;
extern AnimFrameDefaultTypeInternal _AnimFrame_default_instance_;
class SpriteAnim;
struct SpriteAnimDefaultTypeInternal;
extern SpriteAnimDefaultTypeInternal _SpriteAnim_default_instance_;
class SpriteBounds;
struct SpriteBoundsDefaultTypeInternal;
extern SpriteBoundsDefaultTypeInternal _SpriteBounds_default_instance_;
class SpriteDef;
struct SpriteDefDefaultTypeInternal;
extern SpriteDefDefaultTypeInternal _SpriteDef_default_instance_;
class SpriteGrid;
struct SpriteGridDefaultTypeInternal;
extern SpriteGridDefaultTypeInternal _SpriteGrid_default_instance_;
class SpriteOrigin;
struct SpriteOriginDefaultTypeInternal;
extern SpriteOriginDefaultTypeInternal _SpriteOrigin_default_instance_;
class SpriteSheet;
struct SpriteSheetDefaultTypeInternal;
extern SpriteSheetDefaultTypeInternal _SpriteSheet_default_instance_;
class SpriteTexture;
struct SpriteTextureDefaultTypeInternal;
extern SpriteTextureDefaultTypeInternal _SpriteTexture_default_instance_;
}  // namespace sprites
}  // namespace cc
PROTOBUF_NAMESPACE_OPEN
template<> ::cc::sprites::AnimFrame* Arena::CreateMaybeMessage<::cc::sprites::AnimFrame>(Arena*);
template<> ::cc::sprites::SpriteAnim* Arena::CreateMaybeMessage<::cc::sprites::SpriteAnim>(Arena*);
template<> ::cc::sprites::SpriteBounds* Arena::CreateMaybeMessage<::cc::sprites::SpriteBounds>(Arena*);
template<> ::cc::sprites::SpriteDef* Arena::CreateMaybeMessage<::cc::sprites::SpriteDef>(Arena*);
template<> ::cc::sprites::SpriteGrid* Arena::CreateMaybeMessage<::cc::sprites::SpriteGrid>(Arena*);
template<> ::cc::sprites::SpriteOrigin* Arena::CreateMaybeMessage<::cc::sprites::SpriteOrigin>(Arena*);
template<> ::cc::sprites::SpriteSheet* Arena::CreateMaybeMessage<::cc::sprites::SpriteSheet>(Arena*);
template<> ::cc::sprites::SpriteTexture* Arena::CreateMaybeMessage<::cc::sprites::SpriteTexture>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace cc {
namespace sprites {

// ===================================================================

class SpriteBounds final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:cc.sprites.SpriteBounds) */ {
 public:
  inline SpriteBounds() : SpriteBounds(nullptr) {}
  ~SpriteBounds() override;
  explicit PROTOBUF_CONSTEXPR SpriteBounds(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SpriteBounds(const SpriteBounds& from);
  SpriteBounds(SpriteBounds&& from) noexcept
    : SpriteBounds() {
    *this = ::std::move(from);
  }

  inline SpriteBounds& operator=(const SpriteBounds& from) {
    CopyFrom(from);
    return *this;
  }
  inline SpriteBounds& operator=(SpriteBounds&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SpriteBounds& default_instance() {
    return *internal_default_instance();
  }
  static inline const SpriteBounds* internal_default_instance() {
    return reinterpret_cast<const SpriteBounds*>(
               &_SpriteBounds_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(SpriteBounds& a, SpriteBounds& b) {
    a.Swap(&b);
  }
  inline void Swap(SpriteBounds* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SpriteBounds* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SpriteBounds* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SpriteBounds>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SpriteBounds& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SpriteBounds& from) {
    SpriteBounds::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SpriteBounds* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "cc.sprites.SpriteBounds";
  }
  protected:
  explicit SpriteBounds(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLeftFieldNumber = 1,
    kTopFieldNumber = 2,
    kRightFieldNumber = 3,
    kBottomFieldNumber = 4,
  };
  // int32 left = 1;
  void clear_left();
  int32_t left() const;
  void set_left(int32_t value);
  private:
  int32_t _internal_left() const;
  void _internal_set_left(int32_t value);
  public:

  // int32 top = 2;
  void clear_top();
  int32_t top() const;
  void set_top(int32_t value);
  private:
  int32_t _internal_top() const;
  void _internal_set_top(int32_t value);
  public:

  // int32 right = 3;
  void clear_right();
  int32_t right() const;
  void set_right(int32_t value);
  private:
  int32_t _internal_right() const;
  void _internal_set_right(int32_t value);
  public:

  // int32 bottom = 4;
  void clear_bottom();
  int32_t bottom() const;
  void set_bottom(int32_t value);
  private:
  int32_t _internal_bottom() const;
  void _internal_set_bottom(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:cc.sprites.SpriteBounds)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t left_;
    int32_t top_;
    int32_t right_;
    int32_t bottom_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_spritedata_2eproto;
};
// -------------------------------------------------------------------

class SpriteOrigin final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:cc.sprites.SpriteOrigin) */ {
 public:
  inline SpriteOrigin() : SpriteOrigin(nullptr) {}
  ~SpriteOrigin() override;
  explicit PROTOBUF_CONSTEXPR SpriteOrigin(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SpriteOrigin(const SpriteOrigin& from);
  SpriteOrigin(SpriteOrigin&& from) noexcept
    : SpriteOrigin() {
    *this = ::std::move(from);
  }

  inline SpriteOrigin& operator=(const SpriteOrigin& from) {
    CopyFrom(from);
    return *this;
  }
  inline SpriteOrigin& operator=(SpriteOrigin&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SpriteOrigin& default_instance() {
    return *internal_default_instance();
  }
  static inline const SpriteOrigin* internal_default_instance() {
    return reinterpret_cast<const SpriteOrigin*>(
               &_SpriteOrigin_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(SpriteOrigin& a, SpriteOrigin& b) {
    a.Swap(&b);
  }
  inline void Swap(SpriteOrigin* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SpriteOrigin* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SpriteOrigin* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SpriteOrigin>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SpriteOrigin& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SpriteOrigin& from) {
    SpriteOrigin::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SpriteOrigin* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "cc.sprites.SpriteOrigin";
  }
  protected:
  explicit SpriteOrigin(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
  };
  // int32 x = 1;
  void clear_x();
  int32_t x() const;
  void set_x(int32_t value);
  private:
  int32_t _internal_x() const;
  void _internal_set_x(int32_t value);
  public:

  // int32 y = 2;
  void clear_y();
  int32_t y() const;
  void set_y(int32_t value);
  private:
  int32_t _internal_y() const;
  void _internal_set_y(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:cc.sprites.SpriteOrigin)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t x_;
    int32_t y_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_spritedata_2eproto;
};
// -------------------------------------------------------------------

class SpriteTexture final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:cc.sprites.SpriteTexture) */ {
 public:
  inline SpriteTexture() : SpriteTexture(nullptr) {}
  ~SpriteTexture() override;
  explicit PROTOBUF_CONSTEXPR SpriteTexture(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SpriteTexture(const SpriteTexture& from);
  SpriteTexture(SpriteTexture&& from) noexcept
    : SpriteTexture() {
    *this = ::std::move(from);
  }

  inline SpriteTexture& operator=(const SpriteTexture& from) {
    CopyFrom(from);
    return *this;
  }
  inline SpriteTexture& operator=(SpriteTexture&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SpriteTexture& default_instance() {
    return *internal_default_instance();
  }
  static inline const SpriteTexture* internal_default_instance() {
    return reinterpret_cast<const SpriteTexture*>(
               &_SpriteTexture_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(SpriteTexture& a, SpriteTexture& b) {
    a.Swap(&b);
  }
  inline void Swap(SpriteTexture* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SpriteTexture* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SpriteTexture* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SpriteTexture>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SpriteTexture& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SpriteTexture& from) {
    SpriteTexture::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SpriteTexture* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "cc.sprites.SpriteTexture";
  }
  protected:
  explicit SpriteTexture(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFileFieldNumber = 2,
    kIdFieldNumber = 1,
    kWidthFieldNumber = 3,
    kHeightFieldNumber = 4,
  };
  // string file = 2;
  void clear_file();
  const std::string& file() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_file(ArgT0&& arg0, ArgT... args);
  std::string* mutable_file();
  PROTOBUF_NODISCARD std::string* release_file();
  void set_allocated_file(std::string* file);
  private:
  const std::string& _internal_file() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_file(const std::string& value);
  std::string* _internal_mutable_file();
  public:

  // int32 id = 1;
  void clear_id();
  int32_t id() const;
  void set_id(int32_t value);
  private:
  int32_t _internal_id() const;
  void _internal_set_id(int32_t value);
  public:

  // int32 width = 3;
  void clear_width();
  int32_t width() const;
  void set_width(int32_t value);
  private:
  int32_t _internal_width() const;
  void _internal_set_width(int32_t value);
  public:

  // int32 height = 4;
  void clear_height();
  int32_t height() const;
  void set_height(int32_t value);
  private:
  int32_t _internal_height() const;
  void _internal_set_height(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:cc.sprites.SpriteTexture)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr file_;
    int32_t id_;
    int32_t width_;
    int32_t height_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_spritedata_2eproto;
};
// -------------------------------------------------------------------

class SpriteDef final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:cc.sprites.SpriteDef) */ {
 public:
  inline SpriteDef() : SpriteDef(nullptr) {}
  ~SpriteDef() override;
  explicit PROTOBUF_CONSTEXPR SpriteDef(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SpriteDef(const SpriteDef& from);
  SpriteDef(SpriteDef&& from) noexcept
    : SpriteDef() {
    *this = ::std::move(from);
  }

  inline SpriteDef& operator=(const SpriteDef& from) {
    CopyFrom(from);
    return *this;
  }
  inline SpriteDef& operator=(SpriteDef&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SpriteDef& default_instance() {
    return *internal_default_instance();
  }
  static inline const SpriteDef* internal_default_instance() {
    return reinterpret_cast<const SpriteDef*>(
               &_SpriteDef_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(SpriteDef& a, SpriteDef& b) {
    a.Swap(&b);
  }
  inline void Swap(SpriteDef* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SpriteDef* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SpriteDef* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SpriteDef>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SpriteDef& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SpriteDef& from) {
    SpriteDef::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SpriteDef* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "cc.sprites.SpriteDef";
  }
  protected:
  explicit SpriteDef(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 1,
    kBoundsFieldNumber = 4,
    kOriginFieldNumber = 5,
    kIdFieldNumber = 2,
    kTextureFieldNumber = 3,
    kMaskSpriteFieldNumber = 6,
  };
  // string name = 1;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // .cc.sprites.SpriteBounds bounds = 4;
  bool has_bounds() const;
  private:
  bool _internal_has_bounds() const;
  public:
  void clear_bounds();
  const ::cc::sprites::SpriteBounds& bounds() const;
  PROTOBUF_NODISCARD ::cc::sprites::SpriteBounds* release_bounds();
  ::cc::sprites::SpriteBounds* mutable_bounds();
  void set_allocated_bounds(::cc::sprites::SpriteBounds* bounds);
  private:
  const ::cc::sprites::SpriteBounds& _internal_bounds() const;
  ::cc::sprites::SpriteBounds* _internal_mutable_bounds();
  public:
  void unsafe_arena_set_allocated_bounds(
      ::cc::sprites::SpriteBounds* bounds);
  ::cc::sprites::SpriteBounds* unsafe_arena_release_bounds();

  // .cc.sprites.SpriteOrigin origin = 5;
  bool has_origin() const;
  private:
  bool _internal_has_origin() const;
  public:
  void clear_origin();
  const ::cc::sprites::SpriteOrigin& origin() const;
  PROTOBUF_NODISCARD ::cc::sprites::SpriteOrigin* release_origin();
  ::cc::sprites::SpriteOrigin* mutable_origin();
  void set_allocated_origin(::cc::sprites::SpriteOrigin* origin);
  private:
  const ::cc::sprites::SpriteOrigin& _internal_origin() const;
  ::cc::sprites::SpriteOrigin* _internal_mutable_origin();
  public:
  void unsafe_arena_set_allocated_origin(
      ::cc::sprites::SpriteOrigin* origin);
  ::cc::sprites::SpriteOrigin* unsafe_arena_release_origin();

  // int32 id = 2;
  void clear_id();
  int32_t id() const;
  void set_id(int32_t value);
  private:
  int32_t _internal_id() const;
  void _internal_set_id(int32_t value);
  public:

  // int32 texture = 3;
  void clear_texture();
  int32_t texture() const;
  void set_texture(int32_t value);
  private:
  int32_t _internal_texture() const;
  void _internal_set_texture(int32_t value);
  public:

  // int32 mask_sprite = 6;
  void clear_mask_sprite();
  int32_t mask_sprite() const;
  void set_mask_sprite(int32_t value);
  private:
  int32_t _internal_mask_sprite() const;
  void _internal_set_mask_sprite(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:cc.sprites.SpriteDef)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    ::cc::sprites::SpriteBounds* bounds_;
    ::cc::sprites::SpriteOrigin* origin_;
    int32_t id_;
    int32_t texture_;
    int32_t mask_sprite_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_spritedata_2eproto;
};
// -------------------------------------------------------------------

class SpriteGrid final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:cc.sprites.SpriteGrid) */ {
 public:
  inline SpriteGrid() : SpriteGrid(nullptr) {}
  ~SpriteGrid() override;
  explicit PROTOBUF_CONSTEXPR SpriteGrid(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SpriteGrid(const SpriteGrid& from);
  SpriteGrid(SpriteGrid&& from) noexcept
    : SpriteGrid() {
    *this = ::std::move(from);
  }

  inline SpriteGrid& operator=(const SpriteGrid& from) {
    CopyFrom(from);
    return *this;
  }
  inline SpriteGrid& operator=(SpriteGrid&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SpriteGrid& default_instance() {
    return *internal_default_instance();
  }
  static inline const SpriteGrid* internal_default_instance() {
    return reinterpret_cast<const SpriteGrid*>(
               &_SpriteGrid_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(SpriteGrid& a, SpriteGrid& b) {
    a.Swap(&b);
  }
  inline void Swap(SpriteGrid* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SpriteGrid* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SpriteGrid* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SpriteGrid>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SpriteGrid& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SpriteGrid& from) {
    SpriteGrid::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SpriteGrid* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "cc.sprites.SpriteGrid";
  }
  protected:
  explicit SpriteGrid(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPrefixFieldNumber = 2,
    kOriginFieldNumber = 8,
    kTextureFieldNumber = 1,
    kStartIdFieldNumber = 3,
    kRowsFieldNumber = 4,
    kColsFieldNumber = 5,
    kCellWFieldNumber = 6,
    kCellHFieldNumber = 7,
    kMaskGridStartIdFieldNumber = 9,
  };
  // string prefix = 2;
  void clear_prefix();
  const std::string& prefix() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_prefix(ArgT0&& arg0, ArgT... args);
  std::string* mutable_prefix();
  PROTOBUF_NODISCARD std::string* release_prefix();
  void set_allocated_prefix(std::string* prefix);
  private:
  const std::string& _internal_prefix() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_prefix(const std::string& value);
  std::string* _internal_mutable_prefix();
  public:

  // .cc.sprites.SpriteOrigin origin = 8;
  bool has_origin() const;
  private:
  bool _internal_has_origin() const;
  public:
  void clear_origin();
  const ::cc::sprites::SpriteOrigin& origin() const;
  PROTOBUF_NODISCARD ::cc::sprites::SpriteOrigin* release_origin();
  ::cc::sprites::SpriteOrigin* mutable_origin();
  void set_allocated_origin(::cc::sprites::SpriteOrigin* origin);
  private:
  const ::cc::sprites::SpriteOrigin& _internal_origin() const;
  ::cc::sprites::SpriteOrigin* _internal_mutable_origin();
  public:
  void unsafe_arena_set_allocated_origin(
      ::cc::sprites::SpriteOrigin* origin);
  ::cc::sprites::SpriteOrigin* unsafe_arena_release_origin();

  // int32 texture = 1;
  void clear_texture();
  int32_t texture() const;
  void set_texture(int32_t value);
  private:
  int32_t _internal_texture() const;
  void _internal_set_texture(int32_t value);
  public:

  // int32 start_id = 3;
  void clear_start_id();
  int32_t start_id() const;
  void set_start_id(int32_t value);
  private:
  int32_t _internal_start_id() const;
  void _internal_set_start_id(int32_t value);
  public:

  // int32 rows = 4;
  void clear_rows();
  int32_t rows() const;
  void set_rows(int32_t value);
  private:
  int32_t _internal_rows() const;
  void _internal_set_rows(int32_t value);
  public:

  // int32 cols = 5;
  void clear_cols();
  int32_t cols() const;
  void set_cols(int32_t value);
  private:
  int32_t _internal_cols() const;
  void _internal_set_cols(int32_t value);
  public:

  // int32 cell_w = 6;
  void clear_cell_w();
  int32_t cell_w() const;
  void set_cell_w(int32_t value);
  private:
  int32_t _internal_cell_w() const;
  void _internal_set_cell_w(int32_t value);
  public:

  // int32 cell_h = 7;
  void clear_cell_h();
  int32_t cell_h() const;
  void set_cell_h(int32_t value);
  private:
  int32_t _internal_cell_h() const;
  void _internal_set_cell_h(int32_t value);
  public:

  // int32 mask_grid_start_id = 9;
  void clear_mask_grid_start_id();
  int32_t mask_grid_start_id() const;
  void set_mask_grid_start_id(int32_t value);
  private:
  int32_t _internal_mask_grid_start_id() const;
  void _internal_set_mask_grid_start_id(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:cc.sprites.SpriteGrid)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr prefix_;
    ::cc::sprites::SpriteOrigin* origin_;
    int32_t texture_;
    int32_t start_id_;
    int32_t rows_;
    int32_t cols_;
    int32_t cell_w_;
    int32_t cell_h_;
    int32_t mask_grid_start_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_spritedata_2eproto;
};
// -------------------------------------------------------------------

class AnimFrame final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:cc.sprites.AnimFrame) */ {
 public:
  inline AnimFrame() : AnimFrame(nullptr) {}
  ~AnimFrame() override;
  explicit PROTOBUF_CONSTEXPR AnimFrame(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AnimFrame(const AnimFrame& from);
  AnimFrame(AnimFrame&& from) noexcept
    : AnimFrame() {
    *this = ::std::move(from);
  }

  inline AnimFrame& operator=(const AnimFrame& from) {
    CopyFrom(from);
    return *this;
  }
  inline AnimFrame& operator=(AnimFrame&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AnimFrame& default_instance() {
    return *internal_default_instance();
  }
  static inline const AnimFrame* internal_default_instance() {
    return reinterpret_cast<const AnimFrame*>(
               &_AnimFrame_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(AnimFrame& a, AnimFrame& b) {
    a.Swap(&b);
  }
  inline void Swap(AnimFrame* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AnimFrame* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AnimFrame* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AnimFrame>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AnimFrame& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AnimFrame& from) {
    AnimFrame::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AnimFrame* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "cc.sprites.AnimFrame";
  }
  protected:
  explicit AnimFrame(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSpriteFieldNumber = 1,
    kDurationMsFieldNumber = 2,
  };
  // int32 sprite = 1;
  void clear_sprite();
  int32_t sprite() const;
  void set_sprite(int32_t value);
  private:
  int32_t _internal_sprite() const;
  void _internal_set_sprite(int32_t value);
  public:

  // int32 duration_ms = 2;
  void clear_duration_ms();
  int32_t duration_ms() const;
  void set_duration_ms(int32_t value);
  private:
  int32_t _internal_duration_ms() const;
  void _internal_set_duration_ms(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:cc.sprites.AnimFrame)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t sprite_;
    int32_t duration_ms_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_spritedata_2eproto;
};
// -------------------------------------------------------------------

class SpriteAnim final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:cc.sprites.SpriteAnim) */ {
 public:
  inline SpriteAnim() : SpriteAnim(nullptr) {}
  ~SpriteAnim() override;
  explicit PROTOBUF_CONSTEXPR SpriteAnim(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SpriteAnim(const SpriteAnim& from);
  SpriteAnim(SpriteAnim&& from) noexcept
    : SpriteAnim() {
    *this = ::std::move(from);
  }

  inline SpriteAnim& operator=(const SpriteAnim& from) {
    CopyFrom(from);
    return *this;
  }
  inline SpriteAnim& operator=(SpriteAnim&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SpriteAnim& default_instance() {
    return *internal_default_instance();
  }
  static inline const SpriteAnim* internal_default_instance() {
    return reinterpret_cast<const SpriteAnim*>(
               &_SpriteAnim_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(SpriteAnim& a, SpriteAnim& b) {
    a.Swap(&b);
  }
  inline void Swap(SpriteAnim* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SpriteAnim* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SpriteAnim* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SpriteAnim>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SpriteAnim& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SpriteAnim& from) {
    SpriteAnim::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SpriteAnim* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "cc.sprites.SpriteAnim";
  }
  protected:
  explicit SpriteAnim(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFramesFieldNumber = 4,
    kNameFieldNumber = 1,
    kIdFieldNumber = 2,
    kLoopFieldNumber = 3,
  };
  // repeated .cc.sprites.AnimFrame frames = 4;
  int frames_size() const;
  private:
  int _internal_frames_size() const;
  public:
  void clear_frames();
  ::cc::sprites::AnimFrame* mutable_frames(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::cc::sprites::AnimFrame >*
      mutable_frames();
  private:
  const ::cc::sprites::AnimFrame& _internal_frames(int index) const;
  ::cc::sprites::AnimFrame* _internal_add_frames();
  public:
  const ::cc::sprites::AnimFrame& frames(int index) const;
  ::cc::sprites::AnimFrame* add_frames();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::cc::sprites::AnimFrame >&
      frames() const;

  // string name = 1;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // int32 id = 2;
  void clear_id();
  int32_t id() const;
  void set_id(int32_t value);
  private:
  int32_t _internal_id() const;
  void _internal_set_id(int32_t value);
  public:

  // bool loop = 3;
  void clear_loop();
  bool loop() const;
  void set_loop(bool value);
  private:
  bool _internal_loop() const;
  void _internal_set_loop(bool value);
  public:

  // @@protoc_insertion_point(class_scope:cc.sprites.SpriteAnim)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::cc::sprites::AnimFrame > frames_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    int32_t id_;
    bool loop_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_spritedata_2eproto;
};
// -------------------------------------------------------------------

class SpriteSheet final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:cc.sprites.SpriteSheet) */ {
 public:
  inline SpriteSheet() : SpriteSheet(nullptr) {}
  ~SpriteSheet() override;
  explicit PROTOBUF_CONSTEXPR SpriteSheet(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SpriteSheet(const SpriteSheet& from);
  SpriteSheet(SpriteSheet&& from) noexcept
    : SpriteSheet() {
    *this = ::std::move(from);
  }

  inline SpriteSheet& operator=(const SpriteSheet& from) {
    CopyFrom(from);
    return *this;
  }
  inline SpriteSheet& operator=(SpriteSheet&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SpriteSheet& default_instance() {
    return *internal_default_instance();
  }
  static inline const SpriteSheet* internal_default_instance() {
    return reinterpret_cast<const SpriteSheet*>(
               &_SpriteSheet_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(SpriteSheet& a, SpriteSheet& b) {
    a.Swap(&b);
  }
  inline void Swap(SpriteSheet* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SpriteSheet* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SpriteSheet* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SpriteSheet>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SpriteSheet& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SpriteSheet& from) {
    SpriteSheet::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SpriteSheet* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "cc.sprites.SpriteSheet";
  }
  protected:
  explicit SpriteSheet(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTexturesFieldNumber = 1,
    kSpritesFieldNumber = 2,
    kGridsFieldNumber = 3,
    kAnimationsFieldNumber = 4,
  };
  // repeated .cc.sprites.SpriteTexture textures = 1;
  int textures_size() const;
  private:
  int _internal_textures_size() const;
  public:
  void clear_textures();
  ::cc::sprites::SpriteTexture* mutable_textures(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::cc::sprites::SpriteTexture >*
      mutable_textures();
  private:
  const ::cc::sprites::SpriteTexture& _internal_textures(int index) const;
  ::cc::sprites::SpriteTexture* _internal_add_textures();
  public:
  const ::cc::sprites::SpriteTexture& textures(int index) const;
  ::cc::sprites::SpriteTexture* add_textures();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::cc::sprites::SpriteTexture >&
      textures() const;

  // repeated .cc.sprites.SpriteDef sprites = 2;
  int sprites_size() const;
  private:
  int _internal_sprites_size() const;
  public:
  void clear_sprites();
  ::cc::sprites::SpriteDef* mutable_sprites(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::cc::sprites::SpriteDef >*
      mutable_sprites();
  private:
  const ::cc::sprites::SpriteDef& _internal_sprites(int index) const;
  ::cc::sprites::SpriteDef* _internal_add_sprites();
  public:
  const ::cc::sprites::SpriteDef& sprites(int index) const;
  ::cc::sprites::SpriteDef* add_sprites();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::cc::sprites::SpriteDef >&
      sprites() const;

  // repeated .cc.sprites.SpriteGrid grids = 3;
  int grids_size() const;
  private:
  int _internal_grids_size() const;
  public:
  void clear_grids();
  ::cc::sprites::SpriteGrid* mutable_grids(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::cc::sprites::SpriteGrid >*
      mutable_grids();
  private:
  const ::cc::sprites::SpriteGrid& _internal_grids(int index) const;
  ::cc::sprites::SpriteGrid* _internal_add_grids();
  public:
  const ::cc::sprites::SpriteGrid& grids(int index) const;
  ::cc::sprites::SpriteGrid* add_grids();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::cc::sprites::SpriteGrid >&
      grids() const;

  // repeated .cc.sprites.SpriteAnim animations = 4;
  int animations_size() const;
  private:
  int _internal_animations_size() const;
  public:
  void clear_animations();
  ::cc::sprites::SpriteAnim* mutable_animations(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::cc::sprites::SpriteAnim >*
      mutable_animations();
  private:
  const ::cc::sprites::SpriteAnim& _internal_animations(int index) const;
  ::cc::sprites::SpriteAnim* _internal_add_animations();
  public:
  const ::cc::sprites::SpriteAnim& animations(int index) const;
  ::cc::sprites::SpriteAnim* add_animations();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::cc::sprites::SpriteAnim >&
      animations() const;

  // @@protoc_insertion_point(class_scope:cc.sprites.SpriteSheet)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::cc::sprites::SpriteTexture > textures_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::cc::sprites::SpriteDef > sprites_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::cc::sprites::SpriteGrid > grids_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::cc::sprites::SpriteAnim > animations_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_spritedata_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SpriteBounds

// int32 left = 1;
inline void SpriteBounds::clear_left() {
  _impl_.left_ = 0;
}
inline int32_t SpriteBounds::_internal_left() const {
  return _impl_.left_;
}
inline int32_t SpriteBounds::left() const {
  // @@protoc_insertion_point(field_get:cc.sprites.SpriteBounds.left)
  return _internal_left();
}
inline void SpriteBounds::_internal_set_left(int32_t value) {
  
  _impl_.left_ = value;
}
inline void SpriteBounds::set_left(int32_t value) {
  _internal_set_left(value);
  // @@protoc_insertion_point(field_set:cc.sprites.SpriteBounds.left)
}

// int32 top = 2;
inline void SpriteBounds::clear_top() {
  _impl_.top_ = 0;
}
inline int32_t SpriteBounds::_internal_top() const {
  return _impl_.top_;
}
inline int32_t SpriteBounds::top() const {
  // @@protoc_insertion_point(field_get:cc.sprites.SpriteBounds.top)
  return _internal_top();
}
inline void SpriteBounds::_internal_set_top(int32_t value) {
  
  _impl_.top_ = value;
}
inline void SpriteBounds::set_top(int32_t value) {
  _internal_set_top(value);
  // @@protoc_insertion_point(field_set:cc.sprites.SpriteBounds.top)
}

// int32 right = 3;
inline void SpriteBounds::clear_right() {
  _impl_.right_ = 0;
}
inline int32_t SpriteBounds::_internal_right() const {
  return _impl_.right_;
}
inline int32_t SpriteBounds::right() const {
  // @@protoc_insertion_point(field_get:cc.sprites.SpriteBounds.right)
  return _internal_right();
}
inline void SpriteBounds::_internal_set_right(int32_t value) {
  
  _impl_.right_ = value;
}
inline void SpriteBounds::set_right(int32_t value) {
  _internal_set_right(value);
  // @@protoc_insertion_point(field_set:cc.sprites.SpriteBounds.right)
}

// int32 bottom = 4;
inline void SpriteBounds::clear_bottom() {
  _impl_.bottom_ = 0;
}
inline int32_t SpriteBounds::_internal_bottom() const {
  return _impl_.bottom_;
}
inline int32_t SpriteBounds::bottom() const {
  // @@protoc_insertion_point(field_get:cc.sprites.SpriteBounds.bottom)
  return _internal_bottom();
}
inline void SpriteBounds::_internal_set_bottom(int32_t value) {
  
  _impl_.bottom_ = value;
}
inline void SpriteBounds::set_bottom(int32_t value) {
  _internal_set_bottom(value);
  // @@protoc_insertion_point(field_set:cc.sprites.SpriteBounds.bottom)
}

// -------------------------------------------------------------------

// SpriteOrigin

// int32 x = 1;
inline void SpriteOrigin::clear_x() {
  _impl_.x_ = 0;
}
inline int32_t SpriteOrigin::_internal_x() const {
  return _impl_.x_;
}
inline int32_t SpriteOrigin::x() const {
  // @@protoc_insertion_point(field_get:cc.sprites.SpriteOrigin.x)
  return _internal_x();
}
inline void SpriteOrigin::_internal_set_x(int32_t value) {
  
  _impl_.x_ = value;
}
inline void SpriteOrigin::set_x(int32_t value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:cc.sprites.SpriteOrigin.x)
}

// int32 y = 2;
inline void SpriteOrigin::clear_y() {
  _impl_.y_ = 0;
}
inline int32_t SpriteOrigin::_internal_y() const {
  return _impl_.y_;
}
inline int32_t SpriteOrigin::y() const {
  // @@protoc_insertion_point(field_get:cc.sprites.SpriteOrigin.y)
  return _internal_y();
}
inline void SpriteOrigin::_internal_set_y(int32_t value) {
  
  _impl_.y_ = value;
}
inline void SpriteOrigin::set_y(int32_t value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:cc.sprites.SpriteOrigin.y)
}

// -------------------------------------------------------------------

// SpriteTexture

// int32 id = 1;
inline void SpriteTexture::clear_id() {
  _impl_.id_ = 0;
}
inline int32_t SpriteTexture::_internal_id() const {
  return _impl_.id_;
}
inline int32_t SpriteTexture::id() const {
  // @@protoc_insertion_point(field_get:cc.sprites.SpriteTexture.id)
  return _internal_id();
}
inline void SpriteTexture::_internal_set_id(int32_t value) {
  
  _impl_.id_ = value;
}
inline void SpriteTexture::set_id(int32_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:cc.sprites.SpriteTexture.id)
}

// string file = 2;
inline void SpriteTexture::clear_file() {
  _impl_.file_.ClearToEmpty();
}
inline const std::string& SpriteTexture::file() const {
  // @@protoc_insertion_point(field_get:cc.sprites.SpriteTexture.file)
  return _internal_file();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SpriteTexture::set_file(ArgT0&& arg0, ArgT... args) {
 
 _impl_.file_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:cc.sprites.SpriteTexture.file)
}
inline std::string* SpriteTexture::mutable_file() {
  std::string* _s = _internal_mutable_file();
  // @@protoc_insertion_point(field_mutable:cc.sprites.SpriteTexture.file)
  return _s;
}
inline const std::string& SpriteTexture::_internal_file() const {
  return _impl_.file_.Get();
}
inline void SpriteTexture::_internal_set_file(const std::string& value) {
  
  _impl_.file_.Set(value, GetArenaForAllocation());
}
inline std::string* SpriteTexture::_internal_mutable_file() {
  
  return _impl_.file_.Mutable(GetArenaForAllocation());
}
inline std::string* SpriteTexture::release_file() {
  // @@protoc_insertion_point(field_release:cc.sprites.SpriteTexture.file)
  return _impl_.file_.Release();
}
inline void SpriteTexture::set_allocated_file(std::string* file) {
  if (file != nullptr) {
    
  } else {
    
  }
  _impl_.file_.SetAllocated(file, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.file_.IsDefault()) {
    _impl_.file_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:cc.sprites.SpriteTexture.file)
}

// int32 width = 3;
inline void SpriteTexture::clear_width() {
  _impl_.width_ = 0;
}
inline int32_t SpriteTexture::_internal_width() const {
  return _impl_.width_;
}
inline int32_t SpriteTexture::width() const {
  // @@protoc_insertion_point(field_get:cc.sprites.SpriteTexture.width)
  return _internal_width();
}
inline void SpriteTexture::_internal_set_width(int32_t value) {
  
  _impl_.width_ = value;
}
inline void SpriteTexture::set_width(int32_t value) {
  _internal_set_width(value);
  // @@protoc_insertion_point(field_set:cc.sprites.SpriteTexture.width)
}

// int32 height = 4;
inline void SpriteTexture::clear_height() {
  _impl_.height_ = 0;
}
inline int32_t SpriteTexture::_internal_height() const {
  return _impl_.height_;
}
inline int32_t SpriteTexture::height() const {
  // @@protoc_insertion_point(field_get:cc.sprites.SpriteTexture.height)
  return _internal_height();
}
inline void SpriteTexture::_internal_set_height(int32_t value) {
  
  _impl_.height_ = value;
}
inline void SpriteTexture::set_height(int32_t value) {
  _internal_set_height(value);
  // @@protoc_insertion_point(field_set:cc.sprites.SpriteTexture.height)
}

// -------------------------------------------------------------------

// SpriteDef

// string name = 1;
inline void SpriteDef::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& SpriteDef::name() const {
  // @@protoc_insertion_point(field_get:cc.sprites.SpriteDef.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SpriteDef::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:cc.sprites.SpriteDef.name)
}
inline std::string* SpriteDef::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:cc.sprites.SpriteDef.name)
  return _s;
}
inline const std::string& SpriteDef::_internal_name() const {
  return _impl_.name_.Get();
}
inline void SpriteDef::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* SpriteDef::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* SpriteDef::release_name() {
  // @@protoc_insertion_point(field_release:cc.sprites.SpriteDef.name)
  return _impl_.name_.Release();
}
inline void SpriteDef::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:cc.sprites.SpriteDef.name)
}

// int32 id = 2;
inline void SpriteDef::clear_id() {
  _impl_.id_ = 0;
}
inline int32_t SpriteDef::_internal_id() const {
  return _impl_.id_;
}
inline int32_t SpriteDef::id() const {
  // @@protoc_insertion_point(field_get:cc.sprites.SpriteDef.id)
  return _internal_id();
}
inline void SpriteDef::_internal_set_id(int32_t value) {
  
  _impl_.id_ = value;
}
inline void SpriteDef::set_id(int32_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:cc.sprites.SpriteDef.id)
}

// int32 texture = 3;
inline void SpriteDef::clear_texture() {
  _impl_.texture_ = 0;
}
inline int32_t SpriteDef::_internal_texture() const {
  return _impl_.texture_;
}
inline int32_t SpriteDef::texture() const {
  // @@protoc_insertion_point(field_get:cc.sprites.SpriteDef.texture)
  return _internal_texture();
}
inline void SpriteDef::_internal_set_texture(int32_t value) {
  
  _impl_.texture_ = value;
}
inline void SpriteDef::set_texture(int32_t value) {
  _internal_set_texture(value);
  // @@protoc_insertion_point(field_set:cc.sprites.SpriteDef.texture)
}

// .cc.sprites.SpriteBounds bounds = 4;
inline bool SpriteDef::_internal_has_bounds() const {
  return this != internal_default_instance() && _impl_.bounds_ != nullptr;
}
inline bool SpriteDef::has_bounds() const {
  return _internal_has_bounds();
}
inline void SpriteDef::clear_bounds() {
  if (GetArenaForAllocation() == nullptr && _impl_.bounds_ != nullptr) {
    delete _impl_.bounds_;
  }
  _impl_.bounds_ = nullptr;
}
inline const ::cc::sprites::SpriteBounds& SpriteDef::_internal_bounds() const {
  const ::cc::sprites::SpriteBounds* p = _impl_.bounds_;
  return p != nullptr ? *p : reinterpret_cast<const ::cc::sprites::SpriteBounds&>(
      ::cc::sprites::_SpriteBounds_default_instance_);
}
inline const ::cc::sprites::SpriteBounds& SpriteDef::bounds() const {
  // @@protoc_insertion_point(field_get:cc.sprites.SpriteDef.bounds)
  return _internal_bounds();
}
inline void SpriteDef::unsafe_arena_set_allocated_bounds(
    ::cc::sprites::SpriteBounds* bounds) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.bounds_);
  }
  _impl_.bounds_ = bounds;
  if (bounds) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:cc.sprites.SpriteDef.bounds)
}
inline ::cc::sprites::SpriteBounds* SpriteDef::release_bounds() {
  
  ::cc::sprites::SpriteBounds* temp = _impl_.bounds_;
  _impl_.bounds_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::cc::sprites::SpriteBounds* SpriteDef::unsafe_arena_release_bounds() {
  // @@protoc_insertion_point(field_release:cc.sprites.SpriteDef.bounds)
  
  ::cc::sprites::SpriteBounds* temp = _impl_.bounds_;
  _impl_.bounds_ = nullptr;
  return temp;
}
inline ::cc::sprites::SpriteBounds* SpriteDef::_internal_mutable_bounds() {
  
  if (_impl_.bounds_ == nullptr) {
    auto* p = CreateMaybeMessage<::cc::sprites::SpriteBounds>(GetArenaForAllocation());
    _impl_.bounds_ = p;
  }
  return _impl_.bounds_;
}
inline ::cc::sprites::SpriteBounds* SpriteDef::mutable_bounds() {
  ::cc::sprites::SpriteBounds* _msg = _internal_mutable_bounds();
  // @@protoc_insertion_point(field_mutable:cc.sprites.SpriteDef.bounds)
  return _msg;
}
inline void SpriteDef::set_allocated_bounds(::cc::sprites::SpriteBounds* bounds) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.bounds_;
  }
  if (bounds) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(bounds);
    if (message_arena != submessage_arena) {
      bounds = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, bounds, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.bounds_ = bounds;
  // @@protoc_insertion_point(field_set_allocated:cc.sprites.SpriteDef.bounds)
}

// .cc.sprites.SpriteOrigin origin = 5;
inline bool SpriteDef::_internal_has_origin() const {
  return this != internal_default_instance() && _impl_.origin_ != nullptr;
}
inline bool SpriteDef::has_origin() const {
  return _internal_has_origin();
}
inline void SpriteDef::clear_origin() {
  if (GetArenaForAllocation() == nullptr && _impl_.origin_ != nullptr) {
    delete _impl_.origin_;
  }
  _impl_.origin_ = nullptr;
}
inline const ::cc::sprites::SpriteOrigin& SpriteDef::_internal_origin() const {
  const ::cc::sprites::SpriteOrigin* p = _impl_.origin_;
  return p != nullptr ? *p : reinterpret_cast<const ::cc::sprites::SpriteOrigin&>(
      ::cc::sprites::_SpriteOrigin_default_instance_);
}
inline const ::cc::sprites::SpriteOrigin& SpriteDef::origin() const {
  // @@protoc_insertion_point(field_get:cc.sprites.SpriteDef.origin)
  return _internal_origin();
}
inline void SpriteDef::unsafe_arena_set_allocated_origin(
    ::cc::sprites::SpriteOrigin* origin) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.origin_);
  }
  _impl_.origin_ = origin;
  if (origin) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:cc.sprites.SpriteDef.origin)
}
inline ::cc::sprites::SpriteOrigin* SpriteDef::release_origin() {
  
  ::cc::sprites::SpriteOrigin* temp = _impl_.origin_;
  _impl_.origin_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::cc::sprites::SpriteOrigin* SpriteDef::unsafe_arena_release_origin() {
  // @@protoc_insertion_point(field_release:cc.sprites.SpriteDef.origin)
  
  ::cc::sprites::SpriteOrigin* temp = _impl_.origin_;
  _impl_.origin_ = nullptr;
  return temp;
}
inline ::cc::sprites::SpriteOrigin* SpriteDef::_internal_mutable_origin() {
  
  if (_impl_.origin_ == nullptr) {
    auto* p = CreateMaybeMessage<::cc::sprites::SpriteOrigin>(GetArenaForAllocation());
    _impl_.origin_ = p;
  }
  return _impl_.origin_;
}
inline ::cc::sprites::SpriteOrigin* SpriteDef::mutable_origin() {
  ::cc::sprites::SpriteOrigin* _msg = _internal_mutable_origin();
  // @@protoc_insertion_point(field_mutable:cc.sprites.SpriteDef.origin)
  return _msg;
}
inline void SpriteDef::set_allocated_origin(::cc::sprites::SpriteOrigin* origin) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.origin_;
  }
  if (origin) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(origin);
    if (message_arena != submessage_arena) {
      origin = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, origin, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.origin_ = origin;
  // @@protoc_insertion_point(field_set_allocated:cc.sprites.SpriteDef.origin)
}

// int32 mask_sprite = 6;
inline void SpriteDef::clear_mask_sprite() {
  _impl_.mask_sprite_ = 0;
}
inline int32_t SpriteDef::_internal_mask_sprite() const {
  return _impl_.mask_sprite_;
}
inline int32_t SpriteDef::mask_sprite() const {
  // @@protoc_insertion_point(field_get:cc.sprites.SpriteDef.mask_sprite)
  return _internal_mask_sprite();
}
inline void SpriteDef::_internal_set_mask_sprite(int32_t value) {
  
  _impl_.mask_sprite_ = value;
}
inline void SpriteDef::set_mask_sprite(int32_t value) {
  _internal_set_mask_sprite(value);
  // @@protoc_insertion_point(field_set:cc.sprites.SpriteDef.mask_sprite)
}

// -------------------------------------------------------------------

// SpriteGrid

// int32 texture = 1;
inline void SpriteGrid::clear_texture() {
  _impl_.texture_ = 0;
}
inline int32_t SpriteGrid::_internal_texture() const {
  return _impl_.texture_;
}
inline int32_t SpriteGrid::texture() const {
  // @@protoc_insertion_point(field_get:cc.sprites.SpriteGrid.texture)
  return _internal_texture();
}
inline void SpriteGrid::_internal_set_texture(int32_t value) {
  
  _impl_.texture_ = value;
}
inline void SpriteGrid::set_texture(int32_t value) {
  _internal_set_texture(value);
  // @@protoc_insertion_point(field_set:cc.sprites.SpriteGrid.texture)
}

// string prefix = 2;
inline void SpriteGrid::clear_prefix() {
  _impl_.prefix_.ClearToEmpty();
}
inline const std::string& SpriteGrid::prefix() const {
  // @@protoc_insertion_point(field_get:cc.sprites.SpriteGrid.prefix)
  return _internal_prefix();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SpriteGrid::set_prefix(ArgT0&& arg0, ArgT... args) {
 
 _impl_.prefix_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:cc.sprites.SpriteGrid.prefix)
}
inline std::string* SpriteGrid::mutable_prefix() {
  std::string* _s = _internal_mutable_prefix();
  // @@protoc_insertion_point(field_mutable:cc.sprites.SpriteGrid.prefix)
  return _s;
}
inline const std::string& SpriteGrid::_internal_prefix() const {
  return _impl_.prefix_.Get();
}
inline void SpriteGrid::_internal_set_prefix(const std::string& value) {
  
  _impl_.prefix_.Set(value, GetArenaForAllocation());
}
inline std::string* SpriteGrid::_internal_mutable_prefix() {
  
  return _impl_.prefix_.Mutable(GetArenaForAllocation());
}
inline std::string* SpriteGrid::release_prefix() {
  // @@protoc_insertion_point(field_release:cc.sprites.SpriteGrid.prefix)
  return _impl_.prefix_.Release();
}
inline void SpriteGrid::set_allocated_prefix(std::string* prefix) {
  if (prefix != nullptr) {
    
  } else {
    
  }
  _impl_.prefix_.SetAllocated(prefix, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.prefix_.IsDefault()) {
    _impl_.prefix_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:cc.sprites.SpriteGrid.prefix)
}

// int32 start_id = 3;
inline void SpriteGrid::clear_start_id() {
  _impl_.start_id_ = 0;
}
inline int32_t SpriteGrid::_internal_start_id() const {
  return _impl_.start_id_;
}
inline int32_t SpriteGrid::start_id() const {
  // @@protoc_insertion_point(field_get:cc.sprites.SpriteGrid.start_id)
  return _internal_start_id();
}
inline void SpriteGrid::_internal_set_start_id(int32_t value) {
  
  _impl_.start_id_ = value;
}
inline void SpriteGrid::set_start_id(int32_t value) {
  _internal_set_start_id(value);
  // @@protoc_insertion_point(field_set:cc.sprites.SpriteGrid.start_id)
}

// int32 rows = 4;
inline void SpriteGrid::clear_rows() {
  _impl_.rows_ = 0;
}
inline int32_t SpriteGrid::_internal_rows() const {
  return _impl_.rows_;
}
inline int32_t SpriteGrid::rows() const {
  // @@protoc_insertion_point(field_get:cc.sprites.SpriteGrid.rows)
  return _internal_rows();
}
inline void SpriteGrid::_internal_set_rows(int32_t value) {
  
  _impl_.rows_ = value;
}
inline void SpriteGrid::set_rows(int32_t value) {
  _internal_set_rows(value);
  // @@protoc_insertion_point(field_set:cc.sprites.SpriteGrid.rows)
}

// int32 cols = 5;
inline void SpriteGrid::clear_cols() {
  _impl_.cols_ = 0;
}
inline int32_t SpriteGrid::_internal_cols() const {
  return _impl_.cols_;
}
inline int32_t SpriteGrid::cols() const {
  // @@protoc_insertion_point(field_get:cc.sprites.SpriteGrid.cols)
  return _internal_cols();
}
inline void SpriteGrid::_internal_set_cols(int32_t value) {
  
  _impl_.cols_ = value;
}
inline void SpriteGrid::set_cols(int32_t value) {
  _internal_set_cols(value);
  // @@protoc_insertion_point(field_set:cc.sprites.SpriteGrid.cols)
}

// int32 cell_w = 6;
inline void SpriteGrid::clear_cell_w() {
  _impl_.cell_w_ = 0;
}
inline int32_t SpriteGrid::_internal_cell_w() const {
  return _impl_.cell_w_;
}
inline int32_t SpriteGrid::cell_w() const {
  // @@protoc_insertion_point(field_get:cc.sprites.SpriteGrid.cell_w)
  return _internal_cell_w();
}
inline void SpriteGrid::_internal_set_cell_w(int32_t value) {
  
  _impl_.cell_w_ = value;
}
inline void SpriteGrid::set_cell_w(int32_t value) {
  _internal_set_cell_w(value);
  // @@protoc_insertion_point(field_set:cc.sprites.SpriteGrid.cell_w)
}

// int32 cell_h = 7;
inline void SpriteGrid::clear_cell_h() {
  _impl_.cell_h_ = 0;
}
inline int32_t SpriteGrid::_internal_cell_h() const {
  return _impl_.cell_h_;
}
inline int32_t SpriteGrid::cell_h() const {
  // @@protoc_insertion_point(field_get:cc.sprites.SpriteGrid.cell_h)
  return _internal_cell_h();
}
inline void SpriteGrid::_internal_set_cell_h(int32_t value) {
  
  _impl_.cell_h_ = value;
}
inline void SpriteGrid::set_cell_h(int32_t value) {
  _internal_set_cell_h(value);
  // @@protoc_insertion_point(field_set:cc.sprites.SpriteGrid.cell_h)
}

// .cc.sprites.SpriteOrigin origin = 8;
inline bool SpriteGrid::_internal_has_origin() const {
  return this != internal_default_instance() && _impl_.origin_ != nullptr;
}
inline bool SpriteGrid::has_origin() const {
  return _internal_has_origin();
}
inline void SpriteGrid::clear_origin() {
  if (GetArenaForAllocation() == nullptr && _impl_.origin_ != nullptr) {
    delete _impl_.origin_;
  }
  _impl_.origin_ = nullptr;
}
inline const ::cc::sprites::SpriteOrigin& SpriteGrid::_internal_origin() const {
  const ::cc::sprites::SpriteOrigin* p = _impl_.origin_;
  return p != nullptr ? *p : reinterpret_cast<const ::cc::sprites::SpriteOrigin&>(
      ::cc::sprites::_SpriteOrigin_default_instance_);
}
inline const ::cc::sprites::SpriteOrigin& SpriteGrid::origin() const {
  // @@protoc_insertion_point(field_get:cc.sprites.SpriteGrid.origin)
  return _internal_origin();
}
inline void SpriteGrid::unsafe_arena_set_allocated_origin(
    ::cc::sprites::SpriteOrigin* origin) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.origin_);
  }
  _impl_.origin_ = origin;
  if (origin) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:cc.sprites.SpriteGrid.origin)
}
inline ::cc::sprites::SpriteOrigin* SpriteGrid::release_origin() {
  
  ::cc::sprites::SpriteOrigin* temp = _impl_.origin_;
  _impl_.origin_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::cc::sprites::SpriteOrigin* SpriteGrid::unsafe_arena_release_origin() {
  // @@protoc_insertion_point(field_release:cc.sprites.SpriteGrid.origin)
  
  ::cc::sprites::SpriteOrigin* temp = _impl_.origin_;
  _impl_.origin_ = nullptr;
  return temp;
}
inline ::cc::sprites::SpriteOrigin* SpriteGrid::_internal_mutable_origin() {
  
  if (_impl_.origin_ == nullptr) {
    auto* p = CreateMaybeMessage<::cc::sprites::SpriteOrigin>(GetArenaForAllocation());
    _impl_.origin_ = p;
  }
  return _impl_.origin_;
}
inline ::cc::sprites::SpriteOrigin* SpriteGrid::mutable_origin() {
  ::cc::sprites::SpriteOrigin* _msg = _internal_mutable_origin();
  // @@protoc_insertion_point(field_mutable:cc.sprites.SpriteGrid.origin)
  return _msg;
}
inline void SpriteGrid::set_allocated_origin(::cc::sprites::SpriteOrigin* origin) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.origin_;
  }
  if (origin) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(origin);
    if (message_arena != submessage_arena) {
      origin = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, origin, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.origin_ = origin;
  // @@protoc_insertion_point(field_set_allocated:cc.sprites.SpriteGrid.origin)
}

// int32 mask_grid_start_id = 9;
inline void SpriteGrid::clear_mask_grid_start_id() {
  _impl_.mask_grid_start_id_ = 0;
}
inline int32_t SpriteGrid::_internal_mask_grid_start_id() const {
  return _impl_.mask_grid_start_id_;
}
inline int32_t SpriteGrid::mask_grid_start_id() const {
  // @@protoc_insertion_point(field_get:cc.sprites.SpriteGrid.mask_grid_start_id)
  return _internal_mask_grid_start_id();
}
inline void SpriteGrid::_internal_set_mask_grid_start_id(int32_t value) {
  
  _impl_.mask_grid_start_id_ = value;
}
inline void SpriteGrid::set_mask_grid_start_id(int32_t value) {
  _internal_set_mask_grid_start_id(value);
  // @@protoc_insertion_point(field_set:cc.sprites.SpriteGrid.mask_grid_start_id)
}

// -------------------------------------------------------------------

// AnimFrame

// int32 sprite = 1;
inline void AnimFrame::clear_sprite() {
  _impl_.sprite_ = 0;
}
inline int32_t AnimFrame::_internal_sprite() const {
  return _impl_.sprite_;
}
inline int32_t AnimFrame::sprite() const {
  // @@protoc_insertion_point(field_get:cc.sprites.AnimFrame.sprite)
  return _internal_sprite();
}
inline void AnimFrame::_internal_set_sprite(int32_t value) {
  
  _impl_.sprite_ = value;
}
inline void AnimFrame::set_sprite(int32_t value) {
  _internal_set_sprite(value);
  // @@protoc_insertion_point(field_set:cc.sprites.AnimFrame.sprite)
}

// int32 duration_ms = 2;
inline void AnimFrame::clear_duration_ms() {
  _impl_.duration_ms_ = 0;
}
inline int32_t AnimFrame::_internal_duration_ms() const {
  return _impl_.duration_ms_;
}
inline int32_t AnimFrame::duration_ms() const {
  // @@protoc_insertion_point(field_get:cc.sprites.AnimFrame.duration_ms)
  return _internal_duration_ms();
}
inline void AnimFrame::_internal_set_duration_ms(int32_t value) {
  
  _impl_.duration_ms_ = value;
}
inline void AnimFrame::set_duration_ms(int32_t value) {
  _internal_set_duration_ms(value);
  // @@protoc_insertion_point(field_set:cc.sprites.AnimFrame.duration_ms)
}

// -------------------------------------------------------------------

// SpriteAnim

// string name = 1;
inline void SpriteAnim::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& SpriteAnim::name() const {
  // @@protoc_insertion_point(field_get:cc.sprites.SpriteAnim.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SpriteAnim::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:cc.sprites.SpriteAnim.name)
}
inline std::string* SpriteAnim::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:cc.sprites.SpriteAnim.name)
  return _s;
}
inline const std::string& SpriteAnim::_internal_name() const {
  return _impl_.name_.Get();
}
inline void SpriteAnim::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* SpriteAnim::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* SpriteAnim::release_name() {
  // @@protoc_insertion_point(field_release:cc.sprites.SpriteAnim.name)
  return _impl_.name_.Release();
}
inline void SpriteAnim::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:cc.sprites.SpriteAnim.name)
}

// int32 id = 2;
inline void SpriteAnim::clear_id() {
  _impl_.id_ = 0;
}
inline int32_t SpriteAnim::_internal_id() const {
  return _impl_.id_;
}
inline int32_t SpriteAnim::id() const {
  // @@protoc_insertion_point(field_get:cc.sprites.SpriteAnim.id)
  return _internal_id();
}
inline void SpriteAnim::_internal_set_id(int32_t value) {
  
  _impl_.id_ = value;
}
inline void SpriteAnim::set_id(int32_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:cc.sprites.SpriteAnim.id)
}

// bool loop = 3;
inline void SpriteAnim::clear_loop() {
  _impl_.loop_ = false;
}
inline bool SpriteAnim::_internal_loop() const {
  return _impl_.loop_;
}
inline bool SpriteAnim::loop() const {
  // @@protoc_insertion_point(field_get:cc.sprites.SpriteAnim.loop)
  return _internal_loop();
}
inline void SpriteAnim::_internal_set_loop(bool value) {
  
  _impl_.loop_ = value;
}
inline void SpriteAnim::set_loop(bool value) {
  _internal_set_loop(value);
  // @@protoc_insertion_point(field_set:cc.sprites.SpriteAnim.loop)
}

// repeated .cc.sprites.AnimFrame frames = 4;
inline int SpriteAnim::_internal_frames_size() const {
  return _impl_.frames_.size();
}
inline int SpriteAnim::frames_size() const {
  return _internal_frames_size();
}
inline void SpriteAnim::clear_frames() {
  _impl_.frames_.Clear();
}
inline ::cc::sprites::AnimFrame* SpriteAnim::mutable_frames(int index) {
  // @@protoc_insertion_point(field_mutable:cc.sprites.SpriteAnim.frames)
  return _impl_.frames_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::cc::sprites::AnimFrame >*
SpriteAnim::mutable_frames() {
  // @@protoc_insertion_point(field_mutable_list:cc.sprites.SpriteAnim.frames)
  return &_impl_.frames_;
}
inline const ::cc::sprites::AnimFrame& SpriteAnim::_internal_frames(int index) const {
  return _impl_.frames_.Get(index);
}
inline const ::cc::sprites::AnimFrame& SpriteAnim::frames(int index) const {
  // @@protoc_insertion_point(field_get:cc.sprites.SpriteAnim.frames)
  return _internal_frames(index);
}
inline ::cc::sprites::AnimFrame* SpriteAnim::_internal_add_frames() {
  return _impl_.frames_.Add();
}
inline ::cc::sprites::AnimFrame* SpriteAnim::add_frames() {
  ::cc::sprites::AnimFrame* _add = _internal_add_frames();
  // @@protoc_insertion_point(field_add:cc.sprites.SpriteAnim.frames)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::cc::sprites::AnimFrame >&
SpriteAnim::frames() const {
  // @@protoc_insertion_point(field_list:cc.sprites.SpriteAnim.frames)
  return _impl_.frames_;
}

// -------------------------------------------------------------------

// SpriteSheet

// repeated .cc.sprites.SpriteTexture textures = 1;
inline int SpriteSheet::_internal_textures_size() const {
  return _impl_.textures_.size();
}
inline int SpriteSheet::textures_size() const {
  return _internal_textures_size();
}
inline void SpriteSheet::clear_textures() {
  _impl_.textures_.Clear();
}
inline ::cc::sprites::SpriteTexture* SpriteSheet::mutable_textures(int index) {
  // @@protoc_insertion_point(field_mutable:cc.sprites.SpriteSheet.textures)
  return _impl_.textures_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::cc::sprites::SpriteTexture >*
SpriteSheet::mutable_textures() {
  // @@protoc_insertion_point(field_mutable_list:cc.sprites.SpriteSheet.textures)
  return &_impl_.textures_;
}
inline const ::cc::sprites::SpriteTexture& SpriteSheet::_internal_textures(int index) const {
  return _impl_.textures_.Get(index);
}
inline const ::cc::sprites::SpriteTexture& SpriteSheet::textures(int index) const {
  // @@protoc_insertion_point(field_get:cc.sprites.SpriteSheet.textures)
  return _internal_textures(index);
}
inline ::cc::sprites::SpriteTexture* SpriteSheet::_internal_add_textures() {
  return _impl_.textures_.Add();
}
inline ::cc::sprites::SpriteTexture* SpriteSheet::add_textures() {
  ::cc::sprites::SpriteTexture* _add = _internal_add_textures();
  // @@protoc_insertion_point(field_add:cc.sprites.SpriteSheet.textures)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::cc::sprites::SpriteTexture >&
SpriteSheet::textures() const {
  // @@protoc_insertion_point(field_list:cc.sprites.SpriteSheet.textures)
  return _impl_.textures_;
}

// repeated .cc.sprites.SpriteDef sprites = 2;
inline int SpriteSheet::_internal_sprites_size() const {
  return _impl_.sprites_.size();
}
inline int SpriteSheet::sprites_size() const {
  return _internal_sprites_size();
}
inline void SpriteSheet::clear_sprites() {
  _impl_.sprites_.Clear();
}
inline ::cc::sprites::SpriteDef* SpriteSheet::mutable_sprites(int index) {
  // @@protoc_insertion_point(field_mutable:cc.sprites.SpriteSheet.sprites)
  return _impl_.sprites_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::cc::sprites::SpriteDef >*
SpriteSheet::mutable_sprites() {
  // @@protoc_insertion_point(field_mutable_list:cc.sprites.SpriteSheet.sprites)
  return &_impl_.sprites_;
}
inline const ::cc::sprites::SpriteDef& SpriteSheet::_internal_sprites(int index) const {
  return _impl_.sprites_.Get(index);
}
inline const ::cc::sprites::SpriteDef& SpriteSheet::sprites(int index) const {
  // @@protoc_insertion_point(field_get:cc.sprites.SpriteSheet.sprites)
  return _internal_sprites(index);
}
inline ::cc::sprites::SpriteDef* SpriteSheet::_internal_add_sprites() {
  return _impl_.sprites_.Add();
}
inline ::cc::sprites::SpriteDef* SpriteSheet::add_sprites() {
  ::cc::sprites::SpriteDef* _add = _internal_add_sprites();
  // @@protoc_insertion_point(field_add:cc.sprites.SpriteSheet.sprites)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::cc::sprites::SpriteDef >&
SpriteSheet::sprites() const {
  // @@protoc_insertion_point(field_list:cc.sprites.SpriteSheet.sprites)
  return _impl_.sprites_;
}

// repeated .cc.sprites.SpriteGrid grids = 3;
inline int SpriteSheet::_internal_grids_size() const {
  return _impl_.grids_.size();
}
inline int SpriteSheet::grids_size() const {
  return _internal_grids_size();
}
inline void SpriteSheet::clear_grids() {
  _impl_.grids_.Clear();
}
inline ::cc::sprites::SpriteGrid* SpriteSheet::mutable_grids(int index) {
  // @@protoc_insertion_point(field_mutable:cc.sprites.SpriteSheet.grids)
  return _impl_.grids_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::cc::sprites::SpriteGrid >*
SpriteSheet::mutable_grids() {
  // @@protoc_insertion_point(field_mutable_list:cc.sprites.SpriteSheet.grids)
  return &_impl_.grids_;
}
inline const ::cc::sprites::SpriteGrid& SpriteSheet::_internal_grids(int index) const {
  return _impl_.grids_.Get(index);
}
inline const ::cc::sprites::SpriteGrid& SpriteSheet::grids(int index) const {
  // @@protoc_insertion_point(field_get:cc.sprites.SpriteSheet.grids)
  return _internal_grids(index);
}
inline ::cc::sprites::SpriteGrid* SpriteSheet::_internal_add_grids() {
  return _impl_.grids_.Add();
}
inline ::cc::sprites::SpriteGrid* SpriteSheet::add_grids() {
  ::cc::sprites::SpriteGrid* _add = _internal_add_grids();
  // @@protoc_insertion_point(field_add:cc.sprites.SpriteSheet.grids)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::cc::sprites::SpriteGrid >&
SpriteSheet::grids() const {
  // @@protoc_insertion_point(field_list:cc.sprites.SpriteSheet.grids)
  return _impl_.grids_;
}

// repeated .cc.sprites.SpriteAnim animations = 4;
inline int SpriteSheet::_internal_animations_size() const {
  return _impl_.animations_.size();
}
inline int SpriteSheet::animations_size() const {
  return _internal_animations_size();
}
inline void SpriteSheet::clear_animations() {
  _impl_.animations_.Clear();
}
inline ::cc::sprites::SpriteAnim* SpriteSheet::mutable_animations(int index) {
  // @@protoc_insertion_point(field_mutable:cc.sprites.SpriteSheet.animations)
  return _impl_.animations_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::cc::sprites::SpriteAnim >*
SpriteSheet::mutable_animations() {
  // @@protoc_insertion_point(field_mutable_list:cc.sprites.SpriteSheet.animations)
  return &_impl_.animations_;
}
inline const ::cc::sprites::SpriteAnim& SpriteSheet::_internal_animations(int index) const {
  return _impl_.animations_.Get(index);
}
inline const ::cc::sprites::SpriteAnim& SpriteSheet::animations(int index) const {
  // @@protoc_insertion_point(field_get:cc.sprites.SpriteSheet.animations)
  return _internal_animations(index);
}
inline ::cc::sprites::SpriteAnim* SpriteSheet::_internal_add_animations() {
  return _impl_.animations_.Add();
}
inline ::cc::sprites::SpriteAnim* SpriteSheet::add_animations() {
  ::cc::sprites::SpriteAnim* _add = _internal_add_animations();
  // @@protoc_insertion_point(field_add:cc.sprites.SpriteSheet.animations)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::cc::sprites::SpriteAnim >&
SpriteSheet::animations() const {
  // @@protoc_insertion_point(field_list:cc.sprites.SpriteSheet.animations)
  return _impl_.animations_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace sprites
}  // namespace cc

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_spritedata_2eproto
