// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: unitconfig.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_unitconfig_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_unitconfig_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_unitconfig_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_unitconfig_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_unitconfig_2eproto;
namespace cc {
namespace unitconfig {
class UnitArtConfig;
struct UnitArtConfigDefaultTypeInternal;
extern UnitArtConfigDefaultTypeInternal _UnitArtConfig_default_instance_;
class UnitCollisionConfig;
struct UnitCollisionConfigDefaultTypeInternal;
extern UnitCollisionConfigDefaultTypeInternal _UnitCollisionConfig_default_instance_;
class UnitConfig;
struct UnitConfigDefaultTypeInternal;
extern UnitConfigDefaultTypeInternal _UnitConfig_default_instance_;
class UnitStatsConfig;
struct UnitStatsConfigDefaultTypeInternal;
extern UnitStatsConfigDefaultTypeInternal _UnitStatsConfig_default_instance_;
}  // namespace unitconfig
}  // namespace cc
PROTOBUF_NAMESPACE_OPEN
template<> ::cc::unitconfig::UnitArtConfig* Arena::CreateMaybeMessage<::cc::unitconfig::UnitArtConfig>(Arena*);
template<> ::cc::unitconfig::UnitCollisionConfig* Arena::CreateMaybeMessage<::cc::unitconfig::UnitCollisionConfig>(Arena*);
template<> ::cc::unitconfig::UnitConfig* Arena::CreateMaybeMessage<::cc::unitconfig::UnitConfig>(Arena*);
template<> ::cc::unitconfig::UnitStatsConfig* Arena::CreateMaybeMessage<::cc::unitconfig::UnitStatsConfig>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace cc {
namespace unitconfig {

// ===================================================================

class UnitStatsConfig final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:cc.unitconfig.UnitStatsConfig) */ {
 public:
  inline UnitStatsConfig() : UnitStatsConfig(nullptr) {}
  ~UnitStatsConfig() override;
  explicit PROTOBUF_CONSTEXPR UnitStatsConfig(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  UnitStatsConfig(const UnitStatsConfig& from);
  UnitStatsConfig(UnitStatsConfig&& from) noexcept
    : UnitStatsConfig() {
    *this = ::std::move(from);
  }

  inline UnitStatsConfig& operator=(const UnitStatsConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline UnitStatsConfig& operator=(UnitStatsConfig&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const UnitStatsConfig& default_instance() {
    return *internal_default_instance();
  }
  static inline const UnitStatsConfig* internal_default_instance() {
    return reinterpret_cast<const UnitStatsConfig*>(
               &_UnitStatsConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(UnitStatsConfig& a, UnitStatsConfig& b) {
    a.Swap(&b);
  }
  inline void Swap(UnitStatsConfig* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UnitStatsConfig* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  UnitStatsConfig* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<UnitStatsConfig>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const UnitStatsConfig& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const UnitStatsConfig& from) {
    UnitStatsConfig::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UnitStatsConfig* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "cc.unitconfig.UnitStatsConfig";
  }
  protected:
  explicit UnitStatsConfig(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kArmorTypeFieldNumber = 2,
    kDamageTypeFieldNumber = 3,
    kHealthFieldNumber = 1,
    kAttackPowerFieldNumber = 4,
    kAttackRangeFieldNumber = 5,
    kCooldownTimeFieldNumber = 6,
    kSpeedFieldNumber = 7,
    kSightRangeFieldNumber = 8,
  };
  // string armor_type = 2;
  void clear_armor_type();
  const std::string& armor_type() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_armor_type(ArgT0&& arg0, ArgT... args);
  std::string* mutable_armor_type();
  PROTOBUF_NODISCARD std::string* release_armor_type();
  void set_allocated_armor_type(std::string* armor_type);
  private:
  const std::string& _internal_armor_type() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_armor_type(const std::string& value);
  std::string* _internal_mutable_armor_type();
  public:

  // string damage_type = 3;
  void clear_damage_type();
  const std::string& damage_type() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_damage_type(ArgT0&& arg0, ArgT... args);
  std::string* mutable_damage_type();
  PROTOBUF_NODISCARD std::string* release_damage_type();
  void set_allocated_damage_type(std::string* damage_type);
  private:
  const std::string& _internal_damage_type() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_damage_type(const std::string& value);
  std::string* _internal_mutable_damage_type();
  public:

  // optional float health = 1;
  bool has_health() const;
  private:
  bool _internal_has_health() const;
  public:
  void clear_health();
  float health() const;
  void set_health(float value);
  private:
  float _internal_health() const;
  void _internal_set_health(float value);
  public:

  // optional int32 attack_power = 4;
  bool has_attack_power() const;
  private:
  bool _internal_has_attack_power() const;
  public:
  void clear_attack_power();
  int32_t attack_power() const;
  void set_attack_power(int32_t value);
  private:
  int32_t _internal_attack_power() const;
  void _internal_set_attack_power(int32_t value);
  public:

  // optional int32 attack_range = 5;
  bool has_attack_range() const;
  private:
  bool _internal_has_attack_range() const;
  public:
  void clear_attack_range();
  int32_t attack_range() const;
  void set_attack_range(int32_t value);
  private:
  int32_t _internal_attack_range() const;
  void _internal_set_attack_range(int32_t value);
  public:

  // optional float cooldown_time = 6;
  bool has_cooldown_time() const;
  private:
  bool _internal_has_cooldown_time() const;
  public:
  void clear_cooldown_time();
  float cooldown_time() const;
  void set_cooldown_time(float value);
  private:
  float _internal_cooldown_time() const;
  void _internal_set_cooldown_time(float value);
  public:

  // optional float speed = 7;
  bool has_speed() const;
  private:
  bool _internal_has_speed() const;
  public:
  void clear_speed();
  float speed() const;
  void set_speed(float value);
  private:
  float _internal_speed() const;
  void _internal_set_speed(float value);
  public:

  // optional float sight_range = 8;
  bool has_sight_range() const;
  private:
  bool _internal_has_sight_range() const;
  public:
  void clear_sight_range();
  float sight_range() const;
  void set_sight_range(float value);
  private:
  float _internal_sight_range() const;
  void _internal_set_sight_range(float value);
  public:

  // @@protoc_insertion_point(class_scope:cc.unitconfig.UnitStatsConfig)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr armor_type_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr damage_type_;
    float health_;
    int32_t attack_power_;
    int32_t attack_range_;
    float cooldown_time_;
    float speed_;
    float sight_range_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_unitconfig_2eproto;
};
// -------------------------------------------------------------------

class UnitCollisionConfig final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:cc.unitconfig.UnitCollisionConfig) */ {
 public:
  inline UnitCollisionConfig() : UnitCollisionConfig(nullptr) {}
  ~UnitCollisionConfig() override;
  explicit PROTOBUF_CONSTEXPR UnitCollisionConfig(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  UnitCollisionConfig(const UnitCollisionConfig& from);
  UnitCollisionConfig(UnitCollisionConfig&& from) noexcept
    : UnitCollisionConfig() {
    *this = ::std::move(from);
  }

  inline UnitCollisionConfig& operator=(const UnitCollisionConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline UnitCollisionConfig& operator=(UnitCollisionConfig&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const UnitCollisionConfig& default_instance() {
    return *internal_default_instance();
  }
  static inline const UnitCollisionConfig* internal_default_instance() {
    return reinterpret_cast<const UnitCollisionConfig*>(
               &_UnitCollisionConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(UnitCollisionConfig& a, UnitCollisionConfig& b) {
    a.Swap(&b);
  }
  inline void Swap(UnitCollisionConfig* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UnitCollisionConfig* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  UnitCollisionConfig* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<UnitCollisionConfig>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const UnitCollisionConfig& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const UnitCollisionConfig& from) {
    UnitCollisionConfig::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UnitCollisionConfig* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "cc.unitconfig.UnitCollisionConfig";
  }
  protected:
  explicit UnitCollisionConfig(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFootprintWidthFieldNumber = 1,
    kFootprintHeightFieldNumber = 2,
  };
  // int32 footprint_width = 1;
  void clear_footprint_width();
  int32_t footprint_width() const;
  void set_footprint_width(int32_t value);
  private:
  int32_t _internal_footprint_width() const;
  void _internal_set_footprint_width(int32_t value);
  public:

  // int32 footprint_height = 2;
  void clear_footprint_height();
  int32_t footprint_height() const;
  void set_footprint_height(int32_t value);
  private:
  int32_t _internal_footprint_height() const;
  void _internal_set_footprint_height(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:cc.unitconfig.UnitCollisionConfig)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t footprint_width_;
    int32_t footprint_height_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_unitconfig_2eproto;
};
// -------------------------------------------------------------------

class UnitArtConfig final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:cc.unitconfig.UnitArtConfig) */ {
 public:
  inline UnitArtConfig() : UnitArtConfig(nullptr) {}
  ~UnitArtConfig() override;
  explicit PROTOBUF_CONSTEXPR UnitArtConfig(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  UnitArtConfig(const UnitArtConfig& from);
  UnitArtConfig(UnitArtConfig&& from) noexcept
    : UnitArtConfig() {
    *this = ::std::move(from);
  }

  inline UnitArtConfig& operator=(const UnitArtConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline UnitArtConfig& operator=(UnitArtConfig&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const UnitArtConfig& default_instance() {
    return *internal_default_instance();
  }
  static inline const UnitArtConfig* internal_default_instance() {
    return reinterpret_cast<const UnitArtConfig*>(
               &_UnitArtConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(UnitArtConfig& a, UnitArtConfig& b) {
    a.Swap(&b);
  }
  inline void Swap(UnitArtConfig* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UnitArtConfig* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  UnitArtConfig* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<UnitArtConfig>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const UnitArtConfig& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const UnitArtConfig& from) {
    UnitArtConfig::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UnitArtConfig* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "cc.unitconfig.UnitArtConfig";
  }
  protected:
  explicit UnitArtConfig(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSpritePrefixFieldNumber = 1,
    kAtlasIdlePrefixFieldNumber = 2,
    kAtlasWalkPrefixFieldNumber = 3,
  };
  // string sprite_prefix = 1;
  void clear_sprite_prefix();
  const std::string& sprite_prefix() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_sprite_prefix(ArgT0&& arg0, ArgT... args);
  std::string* mutable_sprite_prefix();
  PROTOBUF_NODISCARD std::string* release_sprite_prefix();
  void set_allocated_sprite_prefix(std::string* sprite_prefix);
  private:
  const std::string& _internal_sprite_prefix() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_sprite_prefix(const std::string& value);
  std::string* _internal_mutable_sprite_prefix();
  public:

  // string atlas_idle_prefix = 2;
  void clear_atlas_idle_prefix();
  const std::string& atlas_idle_prefix() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_atlas_idle_prefix(ArgT0&& arg0, ArgT... args);
  std::string* mutable_atlas_idle_prefix();
  PROTOBUF_NODISCARD std::string* release_atlas_idle_prefix();
  void set_allocated_atlas_idle_prefix(std::string* atlas_idle_prefix);
  private:
  const std::string& _internal_atlas_idle_prefix() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_atlas_idle_prefix(const std::string& value);
  std::string* _internal_mutable_atlas_idle_prefix();
  public:

  // string atlas_walk_prefix = 3;
  void clear_atlas_walk_prefix();
  const std::string& atlas_walk_prefix() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_atlas_walk_prefix(ArgT0&& arg0, ArgT... args);
  std::string* mutable_atlas_walk_prefix();
  PROTOBUF_NODISCARD std::string* release_atlas_walk_prefix();
  void set_allocated_atlas_walk_prefix(std::string* atlas_walk_prefix);
  private:
  const std::string& _internal_atlas_walk_prefix() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_atlas_walk_prefix(const std::string& value);
  std::string* _internal_mutable_atlas_walk_prefix();
  public:

  // @@protoc_insertion_point(class_scope:cc.unitconfig.UnitArtConfig)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr sprite_prefix_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr atlas_idle_prefix_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr atlas_walk_prefix_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_unitconfig_2eproto;
};
// -------------------------------------------------------------------

class UnitConfig final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:cc.unitconfig.UnitConfig) */ {
 public:
  inline UnitConfig() : UnitConfig(nullptr) {}
  ~UnitConfig() override;
  explicit PROTOBUF_CONSTEXPR UnitConfig(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  UnitConfig(const UnitConfig& from);
  UnitConfig(UnitConfig&& from) noexcept
    : UnitConfig() {
    *this = ::std::move(from);
  }

  inline UnitConfig& operator=(const UnitConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline UnitConfig& operator=(UnitConfig&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const UnitConfig& default_instance() {
    return *internal_default_instance();
  }
  static inline const UnitConfig* internal_default_instance() {
    return reinterpret_cast<const UnitConfig*>(
               &_UnitConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(UnitConfig& a, UnitConfig& b) {
    a.Swap(&b);
  }
  inline void Swap(UnitConfig* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UnitConfig* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  UnitConfig* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<UnitConfig>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const UnitConfig& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const UnitConfig& from) {
    UnitConfig::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UnitConfig* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "cc.unitconfig.UnitConfig";
  }
  protected:
  explicit UnitConfig(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTypeFieldNumber = 1,
    kStatsFieldNumber = 2,
    kCollisionFieldNumber = 3,
    kArtFieldNumber = 4,
  };
  // string type = 1;
  void clear_type();
  const std::string& type() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_type(ArgT0&& arg0, ArgT... args);
  std::string* mutable_type();
  PROTOBUF_NODISCARD std::string* release_type();
  void set_allocated_type(std::string* type);
  private:
  const std::string& _internal_type() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_type(const std::string& value);
  std::string* _internal_mutable_type();
  public:

  // .cc.unitconfig.UnitStatsConfig stats = 2;
  bool has_stats() const;
  private:
  bool _internal_has_stats() const;
  public:
  void clear_stats();
  const ::cc::unitconfig::UnitStatsConfig& stats() const;
  PROTOBUF_NODISCARD ::cc::unitconfig::UnitStatsConfig* release_stats();
  ::cc::unitconfig::UnitStatsConfig* mutable_stats();
  void set_allocated_stats(::cc::unitconfig::UnitStatsConfig* stats);
  private:
  const ::cc::unitconfig::UnitStatsConfig& _internal_stats() const;
  ::cc::unitconfig::UnitStatsConfig* _internal_mutable_stats();
  public:
  void unsafe_arena_set_allocated_stats(
      ::cc::unitconfig::UnitStatsConfig* stats);
  ::cc::unitconfig::UnitStatsConfig* unsafe_arena_release_stats();

  // .cc.unitconfig.UnitCollisionConfig collision = 3;
  bool has_collision() const;
  private:
  bool _internal_has_collision() const;
  public:
  void clear_collision();
  const ::cc::unitconfig::UnitCollisionConfig& collision() const;
  PROTOBUF_NODISCARD ::cc::unitconfig::UnitCollisionConfig* release_collision();
  ::cc::unitconfig::UnitCollisionConfig* mutable_collision();
  void set_allocated_collision(::cc::unitconfig::UnitCollisionConfig* collision);
  private:
  const ::cc::unitconfig::UnitCollisionConfig& _internal_collision() const;
  ::cc::unitconfig::UnitCollisionConfig* _internal_mutable_collision();
  public:
  void unsafe_arena_set_allocated_collision(
      ::cc::unitconfig::UnitCollisionConfig* collision);
  ::cc::unitconfig::UnitCollisionConfig* unsafe_arena_release_collision();

  // .cc.unitconfig.UnitArtConfig art = 4;
  bool has_art() const;
  private:
  bool _internal_has_art() const;
  public:
  void clear_art();
  const ::cc::unitconfig::UnitArtConfig& art() const;
  PROTOBUF_NODISCARD ::cc::unitconfig::UnitArtConfig* release_art();
  ::cc::unitconfig::UnitArtConfig* mutable_art();
  void set_allocated_art(::cc::unitconfig::UnitArtConfig* art);
  private:
  const ::cc::unitconfig::UnitArtConfig& _internal_art() const;
  ::cc::unitconfig::UnitArtConfig* _internal_mutable_art();
  public:
  void unsafe_arena_set_allocated_art(
      ::cc::unitconfig::UnitArtConfig* art);
  ::cc::unitconfig::UnitArtConfig* unsafe_arena_release_art();

  // @@protoc_insertion_point(class_scope:cc.unitconfig.UnitConfig)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr type_;
    ::cc::unitconfig::UnitStatsConfig* stats_;
    ::cc::unitconfig::UnitCollisionConfig* collision_;
    ::cc::unitconfig::UnitArtConfig* art_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_unitconfig_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// UnitStatsConfig

// optional float health = 1;
inline bool UnitStatsConfig::_internal_has_health() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool UnitStatsConfig::has_health() const {
  return _internal_has_health();
}
inline void UnitStatsConfig::clear_health() {
  _impl_.health_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline float UnitStatsConfig::_internal_health() const {
  return _impl_.health_;
}
inline float UnitStatsConfig::health() const {
  // @@protoc_insertion_point(field_get:cc.unitconfig.UnitStatsConfig.health)
  return _internal_health();
}
inline void UnitStatsConfig::_internal_set_health(float value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.health_ = value;
}
inline void UnitStatsConfig::set_health(float value) {
  _internal_set_health(value);
  // @@protoc_insertion_point(field_set:cc.unitconfig.UnitStatsConfig.health)
}

// string armor_type = 2;
inline void UnitStatsConfig::clear_armor_type() {
  _impl_.armor_type_.ClearToEmpty();
}
inline const std::string& UnitStatsConfig::armor_type() const {
  // @@protoc_insertion_point(field_get:cc.unitconfig.UnitStatsConfig.armor_type)
  return _internal_armor_type();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void UnitStatsConfig::set_armor_type(ArgT0&& arg0, ArgT... args) {
 
 _impl_.armor_type_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:cc.unitconfig.UnitStatsConfig.armor_type)
}
inline std::string* UnitStatsConfig::mutable_armor_type() {
  std::string* _s = _internal_mutable_armor_type();
  // @@protoc_insertion_point(field_mutable:cc.unitconfig.UnitStatsConfig.armor_type)
  return _s;
}
inline const std::string& UnitStatsConfig::_internal_armor_type() const {
  return _impl_.armor_type_.Get();
}
inline void UnitStatsConfig::_internal_set_armor_type(const std::string& value) {
  
  _impl_.armor_type_.Set(value, GetArenaForAllocation());
}
inline std::string* UnitStatsConfig::_internal_mutable_armor_type() {
  
  return _impl_.armor_type_.Mutable(GetArenaForAllocation());
}
inline std::string* UnitStatsConfig::release_armor_type() {
  // @@protoc_insertion_point(field_release:cc.unitconfig.UnitStatsConfig.armor_type)
  return _impl_.armor_type_.Release();
}
inline void UnitStatsConfig::set_allocated_armor_type(std::string* armor_type) {
  if (armor_type != nullptr) {
    
  } else {
    
  }
  _impl_.armor_type_.SetAllocated(armor_type, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.armor_type_.IsDefault()) {
    _impl_.armor_type_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:cc.unitconfig.UnitStatsConfig.armor_type)
}

// string damage_type = 3;
inline void UnitStatsConfig::clear_damage_type() {
  _impl_.damage_type_.ClearToEmpty();
}
inline const std::string& UnitStatsConfig::damage_type() const {
  // @@protoc_insertion_point(field_get:cc.unitconfig.UnitStatsConfig.damage_type)
  return _internal_damage_type();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void UnitStatsConfig::set_damage_type(ArgT0&& arg0, ArgT... args) {
 
 _impl_.damage_type_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:cc.unitconfig.UnitStatsConfig.damage_type)
}
inline std::string* UnitStatsConfig::mutable_damage_type() {
  std::string* _s = _internal_mutable_damage_type();
  // @@protoc_insertion_point(field_mutable:cc.unitconfig.UnitStatsConfig.damage_type)
  return _s;
}
inline const std::string& UnitStatsConfig::_internal_damage_type() const {
  return _impl_.damage_type_.Get();
}
inline void UnitStatsConfig::_internal_set_damage_type(const std::string& value) {
  
  _impl_.damage_type_.Set(value, GetArenaForAllocation());
}
inline std::string* UnitStatsConfig::_internal_mutable_damage_type() {
  
  return _impl_.damage_type_.Mutable(GetArenaForAllocation());
}
inline std::string* UnitStatsConfig::release_damage_type() {
  // @@protoc_insertion_point(field_release:cc.unitconfig.UnitStatsConfig.damage_type)
  return _impl_.damage_type_.Release();
}
inline void UnitStatsConfig::set_allocated_damage_type(std::string* damage_type) {
  if (damage_type != nullptr) {
    
  } else {
    
  }
  _impl_.damage_type_.SetAllocated(damage_type, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.damage_type_.IsDefault()) {
    _impl_.damage_type_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:cc.unitconfig.UnitStatsConfig.damage_type)
}

// optional int32 attack_power = 4;
inline bool UnitStatsConfig::_internal_has_attack_power() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool UnitStatsConfig::has_attack_power() const {
  return _internal_has_attack_power();
}
inline void UnitStatsConfig::clear_attack_power() {
  _impl_.attack_power_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline int32_t UnitStatsConfig::_internal_attack_power() const {
  return _impl_.attack_power_;
}
inline int32_t UnitStatsConfig::attack_power() const {
  // @@protoc_insertion_point(field_get:cc.unitconfig.UnitStatsConfig.attack_power)
  return _internal_attack_power();
}
inline void UnitStatsConfig::_internal_set_attack_power(int32_t value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.attack_power_ = value;
}
inline void UnitStatsConfig::set_attack_power(int32_t value) {
  _internal_set_attack_power(value);
  // @@protoc_insertion_point(field_set:cc.unitconfig.UnitStatsConfig.attack_power)
}

// optional int32 attack_range = 5;
inline bool UnitStatsConfig::_internal_has_attack_range() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool UnitStatsConfig::has_attack_range() const {
  return _internal_has_attack_range();
}
inline void UnitStatsConfig::clear_attack_range() {
  _impl_.attack_range_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline int32_t UnitStatsConfig::_internal_attack_range() const {
  return _impl_.attack_range_;
}
inline int32_t UnitStatsConfig::attack_range() const {
  // @@protoc_insertion_point(field_get:cc.unitconfig.UnitStatsConfig.attack_range)
  return _internal_attack_range();
}
inline void UnitStatsConfig::_internal_set_attack_range(int32_t value) {
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.attack_range_ = value;
}
inline void UnitStatsConfig::set_attack_range(int32_t value) {
  _internal_set_attack_range(value);
  // @@protoc_insertion_point(field_set:cc.unitconfig.UnitStatsConfig.attack_range)
}

// optional float cooldown_time = 6;
inline bool UnitStatsConfig::_internal_has_cooldown_time() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool UnitStatsConfig::has_cooldown_time() const {
  return _internal_has_cooldown_time();
}
inline void UnitStatsConfig::clear_cooldown_time() {
  _impl_.cooldown_time_ = 0;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline float UnitStatsConfig::_internal_cooldown_time() const {
  return _impl_.cooldown_time_;
}
inline float UnitStatsConfig::cooldown_time() const {
  // @@protoc_insertion_point(field_get:cc.unitconfig.UnitStatsConfig.cooldown_time)
  return _internal_cooldown_time();
}
inline void UnitStatsConfig::_internal_set_cooldown_time(float value) {
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.cooldown_time_ = value;
}
inline void UnitStatsConfig::set_cooldown_time(float value) {
  _internal_set_cooldown_time(value);
  // @@protoc_insertion_point(field_set:cc.unitconfig.UnitStatsConfig.cooldown_time)
}

// optional float speed = 7;
inline bool UnitStatsConfig::_internal_has_speed() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool UnitStatsConfig::has_speed() const {
  return _internal_has_speed();
}
inline void UnitStatsConfig::clear_speed() {
  _impl_.speed_ = 0;
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline float UnitStatsConfig::_internal_speed() const {
  return _impl_.speed_;
}
inline float UnitStatsConfig::speed() const {
  // @@protoc_insertion_point(field_get:cc.unitconfig.UnitStatsConfig.speed)
  return _internal_speed();
}
inline void UnitStatsConfig::_internal_set_speed(float value) {
  _impl_._has_bits_[0] |= 0x00000010u;
  _impl_.speed_ = value;
}
inline void UnitStatsConfig::set_speed(float value) {
  _internal_set_speed(value);
  // @@protoc_insertion_point(field_set:cc.unitconfig.UnitStatsConfig.speed)
}

// optional float sight_range = 8;
inline bool UnitStatsConfig::_internal_has_sight_range() const {
  bool value = (_impl_._has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool UnitStatsConfig::has_sight_range() const {
  return _internal_has_sight_range();
}
inline void UnitStatsConfig::clear_sight_range() {
  _impl_.sight_range_ = 0;
  _impl_._has_bits_[0] &= ~0x00000020u;
}
inline float UnitStatsConfig::_internal_sight_range() const {
  return _impl_.sight_range_;
}
inline float UnitStatsConfig::sight_range() const {
  // @@protoc_insertion_point(field_get:cc.unitconfig.UnitStatsConfig.sight_range)
  return _internal_sight_range();
}
inline void UnitStatsConfig::_internal_set_sight_range(float value) {
  _impl_._has_bits_[0] |= 0x00000020u;
  _impl_.sight_range_ = value;
}
inline void UnitStatsConfig::set_sight_range(float value) {
  _internal_set_sight_range(value);
  // @@protoc_insertion_point(field_set:cc.unitconfig.UnitStatsConfig.sight_range)
}

// -------------------------------------------------------------------

// UnitCollisionConfig

// int32 footprint_width = 1;
inline void UnitCollisionConfig::clear_footprint_width() {
  _impl_.footprint_width_ = 0;
}
inline int32_t UnitCollisionConfig::_internal_footprint_width() const {
  return _impl_.footprint_width_;
}
inline int32_t UnitCollisionConfig::footprint_width() const {
  // @@protoc_insertion_point(field_get:cc.unitconfig.UnitCollisionConfig.footprint_width)
  return _internal_footprint_width();
}
inline void UnitCollisionConfig::_internal_set_footprint_width(int32_t value) {
  
  _impl_.footprint_width_ = value;
}
inline void UnitCollisionConfig::set_footprint_width(int32_t value) {
  _internal_set_footprint_width(value);
  // @@protoc_insertion_point(field_set:cc.unitconfig.UnitCollisionConfig.footprint_width)
}

// int32 footprint_height = 2;
inline void UnitCollisionConfig::clear_footprint_height() {
  _impl_.footprint_height_ = 0;
}
inline int32_t UnitCollisionConfig::_internal_footprint_height() const {
  return _impl_.footprint_height_;
}
inline int32_t UnitCollisionConfig::footprint_height() const {
  // @@protoc_insertion_point(field_get:cc.unitconfig.UnitCollisionConfig.footprint_height)
  return _internal_footprint_height();
}
inline void UnitCollisionConfig::_internal_set_footprint_height(int32_t value) {
  
  _impl_.footprint_height_ = value;
}
inline void UnitCollisionConfig::set_footprint_height(int32_t value) {
  _internal_set_footprint_height(value);
  // @@protoc_insertion_point(field_set:cc.unitconfig.UnitCollisionConfig.footprint_height)
}

// -------------------------------------------------------------------

// UnitArtConfig

// string sprite_prefix = 1;
inline void UnitArtConfig::clear_sprite_prefix() {
  _impl_.sprite_prefix_.ClearToEmpty();
}
inline const std::string& UnitArtConfig::sprite_prefix() const {
  // @@protoc_insertion_point(field_get:cc.unitconfig.UnitArtConfig.sprite_prefix)
  return _internal_sprite_prefix();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void UnitArtConfig::set_sprite_prefix(ArgT0&& arg0, ArgT... args) {
 
 _impl_.sprite_prefix_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:cc.unitconfig.UnitArtConfig.sprite_prefix)
}
inline std::string* UnitArtConfig::mutable_sprite_prefix() {
  std::string* _s = _internal_mutable_sprite_prefix();
  // @@protoc_insertion_point(field_mutable:cc.unitconfig.UnitArtConfig.sprite_prefix)
  return _s;
}
inline const std::string& UnitArtConfig::_internal_sprite_prefix() const {
  return _impl_.sprite_prefix_.Get();
}
inline void UnitArtConfig::_internal_set_sprite_prefix(const std::string& value) {
  
  _impl_.sprite_prefix_.Set(value, GetArenaForAllocation());
}
inline std::string* UnitArtConfig::_internal_mutable_sprite_prefix() {
  
  return _impl_.sprite_prefix_.Mutable(GetArenaForAllocation());
}
inline std::string* UnitArtConfig::release_sprite_prefix() {
  // @@protoc_insertion_point(field_release:cc.unitconfig.UnitArtConfig.sprite_prefix)
  return _impl_.sprite_prefix_.Release();
}
inline void UnitArtConfig::set_allocated_sprite_prefix(std::string* sprite_prefix) {
  if (sprite_prefix != nullptr) {
    
  } else {
    
  }
  _impl_.sprite_prefix_.SetAllocated(sprite_prefix, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.sprite_prefix_.IsDefault()) {
    _impl_.sprite_prefix_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:cc.unitconfig.UnitArtConfig.sprite_prefix)
}

// string atlas_idle_prefix = 2;
inline void UnitArtConfig::clear_atlas_idle_prefix() {
  _impl_.atlas_idle_prefix_.ClearToEmpty();
}
inline const std::string& UnitArtConfig::atlas_idle_prefix() const {
  // @@protoc_insertion_point(field_get:cc.unitconfig.UnitArtConfig.atlas_idle_prefix)
  return _internal_atlas_idle_prefix();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void UnitArtConfig::set_atlas_idle_prefix(ArgT0&& arg0, ArgT... args) {
 
 _impl_.atlas_idle_prefix_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:cc.unitconfig.UnitArtConfig.atlas_idle_prefix)
}
inline std::string* UnitArtConfig::mutable_atlas_idle_prefix() {
  std::string* _s = _internal_mutable_atlas_idle_prefix();
  // @@protoc_insertion_point(field_mutable:cc.unitconfig.UnitArtConfig.atlas_idle_prefix)
  return _s;
}
inline const std::string& UnitArtConfig::_internal_atlas_idle_prefix() const {
  return _impl_.atlas_idle_prefix_.Get();
}
inline void UnitArtConfig::_internal_set_atlas_idle_prefix(const std::string& value) {
  
  _impl_.atlas_idle_prefix_.Set(value, GetArenaForAllocation());
}
inline std::string* UnitArtConfig::_internal_mutable_atlas_idle_prefix() {
  
  return _impl_.atlas_idle_prefix_.Mutable(GetArenaForAllocation());
}
inline std::string* UnitArtConfig::release_atlas_idle_prefix() {
  // @@protoc_insertion_point(field_release:cc.unitconfig.UnitArtConfig.atlas_idle_prefix)
  return _impl_.atlas_idle_prefix_.Release();
}
inline void UnitArtConfig::set_allocated_atlas_idle_prefix(std::string* atlas_idle_prefix) {
  if (atlas_idle_prefix != nullptr) {
    
  } else {
    
  }
  _impl_.atlas_idle_prefix_.SetAllocated(atlas_idle_prefix, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.atlas_idle_prefix_.IsDefault()) {
    _impl_.atlas_idle_prefix_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:cc.unitconfig.UnitArtConfig.atlas_idle_prefix)
}

// string atlas_walk_prefix = 3;
inline void UnitArtConfig::clear_atlas_walk_prefix() {
  _impl_.atlas_walk_prefix_.ClearToEmpty();
}
inline const std::string& UnitArtConfig::atlas_walk_prefix() const {
  // @@protoc_insertion_point(field_get:cc.unitconfig.UnitArtConfig.atlas_walk_prefix)
  return _internal_atlas_walk_prefix();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void UnitArtConfig::set_atlas_walk_prefix(ArgT0&& arg0, ArgT... args) {
 
 _impl_.atlas_walk_prefix_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:cc.unitconfig.UnitArtConfig.atlas_walk_prefix)
}
inline std::string* UnitArtConfig::mutable_atlas_walk_prefix() {
  std::string* _s = _internal_mutable_atlas_walk_prefix();
  // @@protoc_insertion_point(field_mutable:cc.unitconfig.UnitArtConfig.atlas_walk_prefix)
  return _s;
}
inline const std::string& UnitArtConfig::_internal_atlas_walk_prefix() const {
  return _impl_.atlas_walk_prefix_.Get();
}
inline void UnitArtConfig::_internal_set_atlas_walk_prefix(const std::string& value) {
  
  _impl_.atlas_walk_prefix_.Set(value, GetArenaForAllocation());
}
inline std::string* UnitArtConfig::_internal_mutable_atlas_walk_prefix() {
  
  return _impl_.atlas_walk_prefix_.Mutable(GetArenaForAllocation());
}
inline std::string* UnitArtConfig::release_atlas_walk_prefix() {
  // @@protoc_insertion_point(field_release:cc.unitconfig.UnitArtConfig.atlas_walk_prefix)
  return _impl_.atlas_walk_prefix_.Release();
}
inline void UnitArtConfig::set_allocated_atlas_walk_prefix(std::string* atlas_walk_prefix) {
  if (atlas_walk_prefix != nullptr) {
    
  } else {
    
  }
  _impl_.atlas_walk_prefix_.SetAllocated(atlas_walk_prefix, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.atlas_walk_prefix_.IsDefault()) {
    _impl_.atlas_walk_prefix_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:cc.unitconfig.UnitArtConfig.atlas_walk_prefix)
}

// -------------------------------------------------------------------

// UnitConfig

// string type = 1;
inline void UnitConfig::clear_type() {
  _impl_.type_.ClearToEmpty();
}
inline const std::string& UnitConfig::type() const {
  // @@protoc_insertion_point(field_get:cc.unitconfig.UnitConfig.type)
  return _internal_type();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void UnitConfig::set_type(ArgT0&& arg0, ArgT... args) {
 
 _impl_.type_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:cc.unitconfig.UnitConfig.type)
}
inline std::string* UnitConfig::mutable_type() {
  std::string* _s = _internal_mutable_type();
  // @@protoc_insertion_point(field_mutable:cc.unitconfig.UnitConfig.type)
  return _s;
}
inline const std::string& UnitConfig::_internal_type() const {
  return _impl_.type_.Get();
}
inline void UnitConfig::_internal_set_type(const std::string& value) {
  
  _impl_.type_.Set(value, GetArenaForAllocation());
}
inline std::string* UnitConfig::_internal_mutable_type() {
  
  return _impl_.type_.Mutable(GetArenaForAllocation());
}
inline std::string* UnitConfig::release_type() {
  // @@protoc_insertion_point(field_release:cc.unitconfig.UnitConfig.type)
  return _impl_.type_.Release();
}
inline void UnitConfig::set_allocated_type(std::string* type) {
  if (type != nullptr) {
    
  } else {
    
  }
  _impl_.type_.SetAllocated(type, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.type_.IsDefault()) {
    _impl_.type_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:cc.unitconfig.UnitConfig.type)
}

// .cc.unitconfig.UnitStatsConfig stats = 2;
inline bool UnitConfig::_internal_has_stats() const {
  return this != internal_default_instance() && _impl_.stats_ != nullptr;
}
inline bool UnitConfig::has_stats() const {
  return _internal_has_stats();
}
inline void UnitConfig::clear_stats() {
  if (GetArenaForAllocation() == nullptr && _impl_.stats_ != nullptr) {
    delete _impl_.stats_;
  }
  _impl_.stats_ = nullptr;
}
inline const ::cc::unitconfig::UnitStatsConfig& UnitConfig::_internal_stats() const {
  const ::cc::unitconfig::UnitStatsConfig* p = _impl_.stats_;
  return p != nullptr ? *p : reinterpret_cast<const ::cc::unitconfig::UnitStatsConfig&>(
      ::cc::unitconfig::_UnitStatsConfig_default_instance_);
}
inline const ::cc::unitconfig::UnitStatsConfig& UnitConfig::stats() const {
  // @@protoc_insertion_point(field_get:cc.unitconfig.UnitConfig.stats)
  return _internal_stats();
}
inline void UnitConfig::unsafe_arena_set_allocated_stats(
    ::cc::unitconfig::UnitStatsConfig* stats) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.stats_);
  }
  _impl_.stats_ = stats;
  if (stats) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:cc.unitconfig.UnitConfig.stats)
}
inline ::cc::unitconfig::UnitStatsConfig* UnitConfig::release_stats() {
  
  ::cc::unitconfig::UnitStatsConfig* temp = _impl_.stats_;
  _impl_.stats_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::cc::unitconfig::UnitStatsConfig* UnitConfig::unsafe_arena_release_stats() {
  // @@protoc_insertion_point(field_release:cc.unitconfig.UnitConfig.stats)
  
  ::cc::unitconfig::UnitStatsConfig* temp = _impl_.stats_;
  _impl_.stats_ = nullptr;
  return temp;
}
inline ::cc::unitconfig::UnitStatsConfig* UnitConfig::_internal_mutable_stats() {
  
  if (_impl_.stats_ == nullptr) {
    auto* p = CreateMaybeMessage<::cc::unitconfig::UnitStatsConfig>(GetArenaForAllocation());
    _impl_.stats_ = p;
  }
  return _impl_.stats_;
}
inline ::cc::unitconfig::UnitStatsConfig* UnitConfig::mutable_stats() {
  ::cc::unitconfig::UnitStatsConfig* _msg = _internal_mutable_stats();
  // @@protoc_insertion_point(field_mutable:cc.unitconfig.UnitConfig.stats)
  return _msg;
}
inline void UnitConfig::set_allocated_stats(::cc::unitconfig::UnitStatsConfig* stats) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.stats_;
  }
  if (stats) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(stats);
    if (message_arena != submessage_arena) {
      stats = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, stats, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.stats_ = stats;
  // @@protoc_insertion_point(field_set_allocated:cc.unitconfig.UnitConfig.stats)
}

// .cc.unitconfig.UnitCollisionConfig collision = 3;
inline bool UnitConfig::_internal_has_collision() const {
  return this != internal_default_instance() && _impl_.collision_ != nullptr;
}
inline bool UnitConfig::has_collision() const {
  return _internal_has_collision();
}
inline void UnitConfig::clear_collision() {
  if (GetArenaForAllocation() == nullptr && _impl_.collision_ != nullptr) {
    delete _impl_.collision_;
  }
  _impl_.collision_ = nullptr;
}
inline const ::cc::unitconfig::UnitCollisionConfig& UnitConfig::_internal_collision() const {
  const ::cc::unitconfig::UnitCollisionConfig* p = _impl_.collision_;
  return p != nullptr ? *p : reinterpret_cast<const ::cc::unitconfig::UnitCollisionConfig&>(
      ::cc::unitconfig::_UnitCollisionConfig_default_instance_);
}
inline const ::cc::unitconfig::UnitCollisionConfig& UnitConfig::collision() const {
  // @@protoc_insertion_point(field_get:cc.unitconfig.UnitConfig.collision)
  return _internal_collision();
}
inline void UnitConfig::unsafe_arena_set_allocated_collision(
    ::cc::unitconfig::UnitCollisionConfig* collision) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.collision_);
  }
  _impl_.collision_ = collision;
  if (collision) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:cc.unitconfig.UnitConfig.collision)
}
inline ::cc::unitconfig::UnitCollisionConfig* UnitConfig::release_collision() {
  
  ::cc::unitconfig::UnitCollisionConfig* temp = _impl_.collision_;
  _impl_.collision_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::cc::unitconfig::UnitCollisionConfig* UnitConfig::unsafe_arena_release_collision() {
  // @@protoc_insertion_point(field_release:cc.unitconfig.UnitConfig.collision)
  
  ::cc::unitconfig::UnitCollisionConfig* temp = _impl_.collision_;
  _impl_.collision_ = nullptr;
  return temp;
}
inline ::cc::unitconfig::UnitCollisionConfig* UnitConfig::_internal_mutable_collision() {
  
  if (_impl_.collision_ == nullptr) {
    auto* p = CreateMaybeMessage<::cc::unitconfig::UnitCollisionConfig>(GetArenaForAllocation());
    _impl_.collision_ = p;
  }
  return _impl_.collision_;
}
inline ::cc::unitconfig::UnitCollisionConfig* UnitConfig::mutable_collision() {
  ::cc::unitconfig::UnitCollisionConfig* _msg = _internal_mutable_collision();
  // @@protoc_insertion_point(field_mutable:cc.unitconfig.UnitConfig.collision)
  return _msg;
}
inline void UnitConfig::set_allocated_collision(::cc::unitconfig::UnitCollisionConfig* collision) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.collision_;
  }
  if (collision) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(collision);
    if (message_arena != submessage_arena) {
      collision = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, collision, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.collision_ = collision;
  // @@protoc_insertion_point(field_set_allocated:cc.unitconfig.UnitConfig.collision)
}

// .cc.unitconfig.UnitArtConfig art = 4;
inline bool UnitConfig::_internal_has_art() const {
  return this != internal_default_instance() && _impl_.art_ != nullptr;
}
inline bool UnitConfig::has_art() const {
  return _internal_has_art();
}
inline void UnitConfig::clear_art() {
  if (GetArenaForAllocation() == nullptr && _impl_.art_ != nullptr) {
    delete _impl_.art_;
  }
  _impl_.art_ = nullptr;
}
inline const ::cc::unitconfig::UnitArtConfig& UnitConfig::_internal_art() const {
  const ::cc::unitconfig::UnitArtConfig* p = _impl_.art_;
  return p != nullptr ? *p : reinterpret_cast<const ::cc::unitconfig::UnitArtConfig&>(
      ::cc::unitconfig::_UnitArtConfig_default_instance_);
}
inline const ::cc::unitconfig::UnitArtConfig& UnitConfig::art() const {
  // @@protoc_insertion_point(field_get:cc.unitconfig.UnitConfig.art)
  return _internal_art();
}
inline void UnitConfig::unsafe_arena_set_allocated_art(
    ::cc::unitconfig::UnitArtConfig* art) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.art_);
  }
  _impl_.art_ = art;
  if (art) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:cc.unitconfig.UnitConfig.art)
}
inline ::cc::unitconfig::UnitArtConfig* UnitConfig::release_art() {
  
  ::cc::unitconfig::UnitArtConfig* temp = _impl_.art_;
  _impl_.art_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::cc::unitconfig::UnitArtConfig* UnitConfig::unsafe_arena_release_art() {
  // @@protoc_insertion_point(field_release:cc.unitconfig.UnitConfig.art)
  
  ::cc::unitconfig::UnitArtConfig* temp = _impl_.art_;
  _impl_.art_ = nullptr;
  return temp;
}
inline ::cc::unitconfig::UnitArtConfig* UnitConfig::_internal_mutable_art() {
  
  if (_impl_.art_ == nullptr) {
    auto* p = CreateMaybeMessage<::cc::unitconfig::UnitArtConfig>(GetArenaForAllocation());
    _impl_.art_ = p;
  }
  return _impl_.art_;
}
inline ::cc::unitconfig::UnitArtConfig* UnitConfig::mutable_art() {
  ::cc::unitconfig::UnitArtConfig* _msg = _internal_mutable_art();
  // @@protoc_insertion_point(field_mutable:cc.unitconfig.UnitConfig.art)
  return _msg;
}
inline void UnitConfig::set_allocated_art(::cc::unitconfig::UnitArtConfig* art) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.art_;
  }
  if (art) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(art);
    if (message_arena != submessage_arena) {
      art = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, art, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.art_ = art;
  // @@protoc_insertion_point(field_set_allocated:cc.unitconfig.UnitConfig.art)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace unitconfig
}  // namespace cc

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_unitconfig_2eproto
