// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: unitconfig.proto

#include "unitconfig.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace cc {
namespace unitconfig {
PROTOBUF_CONSTEXPR UnitStatsConfig::UnitStatsConfig(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.armor_type_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.damage_type_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.health_)*/0
  , /*decltype(_impl_.attack_power_)*/0
  , /*decltype(_impl_.attack_range_)*/0
  , /*decltype(_impl_.cooldown_time_)*/0
  , /*decltype(_impl_.speed_)*/0
  , /*decltype(_impl_.sight_range_)*/0} {}
struct UnitStatsConfigDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UnitStatsConfigDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~UnitStatsConfigDefaultTypeInternal() {}
  union {
    UnitStatsConfig _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UnitStatsConfigDefaultTypeInternal _UnitStatsConfig_default_instance_;
PROTOBUF_CONSTEXPR UnitCollisionConfig::UnitCollisionConfig(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.footprint_width_)*/0
  , /*decltype(_impl_.footprint_height_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct UnitCollisionConfigDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UnitCollisionConfigDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~UnitCollisionConfigDefaultTypeInternal() {}
  union {
    UnitCollisionConfig _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UnitCollisionConfigDefaultTypeInternal _UnitCollisionConfig_default_instance_;
PROTOBUF_CONSTEXPR UnitArtConfig::UnitArtConfig(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.sprite_prefix_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.atlas_idle_prefix_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.atlas_walk_prefix_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct UnitArtConfigDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UnitArtConfigDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~UnitArtConfigDefaultTypeInternal() {}
  union {
    UnitArtConfig _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UnitArtConfigDefaultTypeInternal _UnitArtConfig_default_instance_;
PROTOBUF_CONSTEXPR UnitConfig::UnitConfig(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.type_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.stats_)*/nullptr
  , /*decltype(_impl_.collision_)*/nullptr
  , /*decltype(_impl_.art_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct UnitConfigDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UnitConfigDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~UnitConfigDefaultTypeInternal() {}
  union {
    UnitConfig _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UnitConfigDefaultTypeInternal _UnitConfig_default_instance_;
}  // namespace unitconfig
}  // namespace cc
static ::_pb::Metadata file_level_metadata_unitconfig_2eproto[4];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_unitconfig_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_unitconfig_2eproto = nullptr;

const uint32_t TableStruct_unitconfig_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::cc::unitconfig::UnitStatsConfig, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::cc::unitconfig::UnitStatsConfig, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::cc::unitconfig::UnitStatsConfig, _impl_.health_),
  PROTOBUF_FIELD_OFFSET(::cc::unitconfig::UnitStatsConfig, _impl_.armor_type_),
  PROTOBUF_FIELD_OFFSET(::cc::unitconfig::UnitStatsConfig, _impl_.damage_type_),
  PROTOBUF_FIELD_OFFSET(::cc::unitconfig::UnitStatsConfig, _impl_.attack_power_),
  PROTOBUF_FIELD_OFFSET(::cc::unitconfig::UnitStatsConfig, _impl_.attack_range_),
  PROTOBUF_FIELD_OFFSET(::cc::unitconfig::UnitStatsConfig, _impl_.cooldown_time_),
  PROTOBUF_FIELD_OFFSET(::cc::unitconfig::UnitStatsConfig, _impl_.speed_),
  PROTOBUF_FIELD_OFFSET(::cc::unitconfig::UnitStatsConfig, _impl_.sight_range_),
  0,
  ~0u,
  ~0u,
  1,
  2,
  3,
  4,
  5,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::cc::unitconfig::UnitCollisionConfig, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::cc::unitconfig::UnitCollisionConfig, _impl_.footprint_width_),
  PROTOBUF_FIELD_OFFSET(::cc::unitconfig::UnitCollisionConfig, _impl_.footprint_height_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::cc::unitconfig::UnitArtConfig, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::cc::unitconfig::UnitArtConfig, _impl_.sprite_prefix_),
  PROTOBUF_FIELD_OFFSET(::cc::unitconfig::UnitArtConfig, _impl_.atlas_idle_prefix_),
  PROTOBUF_FIELD_OFFSET(::cc::unitconfig::UnitArtConfig, _impl_.atlas_walk_prefix_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::cc::unitconfig::UnitConfig, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::cc::unitconfig::UnitConfig, _impl_.type_),
  PROTOBUF_FIELD_OFFSET(::cc::unitconfig::UnitConfig, _impl_.stats_),
  PROTOBUF_FIELD_OFFSET(::cc::unitconfig::UnitConfig, _impl_.collision_),
  PROTOBUF_FIELD_OFFSET(::cc::unitconfig::UnitConfig, _impl_.art_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 14, -1, sizeof(::cc::unitconfig::UnitStatsConfig)},
  { 22, -1, -1, sizeof(::cc::unitconfig::UnitCollisionConfig)},
  { 30, -1, -1, sizeof(::cc::unitconfig::UnitArtConfig)},
  { 39, -1, -1, sizeof(::cc::unitconfig::UnitConfig)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::cc::unitconfig::_UnitStatsConfig_default_instance_._instance,
  &::cc::unitconfig::_UnitCollisionConfig_default_instance_._instance,
  &::cc::unitconfig::_UnitArtConfig_default_instance_._instance,
  &::cc::unitconfig::_UnitConfig_default_instance_._instance,
};

const char descriptor_table_protodef_unitconfig_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\020unitconfig.proto\022\rcc.unitconfig\"\250\002\n\017Un"
  "itStatsConfig\022\023\n\006health\030\001 \001(\002H\000\210\001\001\022\022\n\nar"
  "mor_type\030\002 \001(\t\022\023\n\013damage_type\030\003 \001(\t\022\031\n\014a"
  "ttack_power\030\004 \001(\005H\001\210\001\001\022\031\n\014attack_range\030\005"
  " \001(\005H\002\210\001\001\022\032\n\rcooldown_time\030\006 \001(\002H\003\210\001\001\022\022\n"
  "\005speed\030\007 \001(\002H\004\210\001\001\022\030\n\013sight_range\030\010 \001(\002H\005"
  "\210\001\001B\t\n\007_healthB\017\n\r_attack_powerB\017\n\r_atta"
  "ck_rangeB\020\n\016_cooldown_timeB\010\n\006_speedB\016\n\014"
  "_sight_range\"H\n\023UnitCollisionConfig\022\027\n\017f"
  "ootprint_width\030\001 \001(\005\022\030\n\020footprint_height"
  "\030\002 \001(\005\"\\\n\rUnitArtConfig\022\025\n\rsprite_prefix"
  "\030\001 \001(\t\022\031\n\021atlas_idle_prefix\030\002 \001(\t\022\031\n\021atl"
  "as_walk_prefix\030\003 \001(\t\"\253\001\n\nUnitConfig\022\014\n\004t"
  "ype\030\001 \001(\t\022-\n\005stats\030\002 \001(\0132\036.cc.unitconfig"
  ".UnitStatsConfig\0225\n\tcollision\030\003 \001(\0132\".cc"
  ".unitconfig.UnitCollisionConfig\022)\n\003art\030\004"
  " \001(\0132\034.cc.unitconfig.UnitArtConfigb\006prot"
  "o3"
  ;
static ::_pbi::once_flag descriptor_table_unitconfig_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_unitconfig_2eproto = {
    false, false, 682, descriptor_table_protodef_unitconfig_2eproto,
    "unitconfig.proto",
    &descriptor_table_unitconfig_2eproto_once, nullptr, 0, 4,
    schemas, file_default_instances, TableStruct_unitconfig_2eproto::offsets,
    file_level_metadata_unitconfig_2eproto, file_level_enum_descriptors_unitconfig_2eproto,
    file_level_service_descriptors_unitconfig_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_unitconfig_2eproto_getter() {
  return &descriptor_table_unitconfig_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_unitconfig_2eproto(&descriptor_table_unitconfig_2eproto);
namespace cc {
namespace unitconfig {

// ===================================================================

class UnitStatsConfig::_Internal {
 public:
  using HasBits = decltype(std::declval<UnitStatsConfig>()._impl_._has_bits_);
  static void set_has_health(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_attack_power(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_attack_range(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_cooldown_time(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static void set_has_speed(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
  static void set_has_sight_range(HasBits* has_bits) {
    (*has_bits)[0] |= 32u;
  }
};

UnitStatsConfig::UnitStatsConfig(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:cc.unitconfig.UnitStatsConfig)
}
UnitStatsConfig::UnitStatsConfig(const UnitStatsConfig& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  UnitStatsConfig* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.armor_type_){}
    , decltype(_impl_.damage_type_){}
    , decltype(_impl_.health_){}
    , decltype(_impl_.attack_power_){}
    , decltype(_impl_.attack_range_){}
    , decltype(_impl_.cooldown_time_){}
    , decltype(_impl_.speed_){}
    , decltype(_impl_.sight_range_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.armor_type_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.armor_type_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_armor_type().empty()) {
    _this->_impl_.armor_type_.Set(from._internal_armor_type(), 
      _this->GetArenaForAllocation());
  }
  _impl_.damage_type_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.damage_type_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_damage_type().empty()) {
    _this->_impl_.damage_type_.Set(from._internal_damage_type(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.health_, &from._impl_.health_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.sight_range_) -
    reinterpret_cast<char*>(&_impl_.health_)) + sizeof(_impl_.sight_range_));
  // @@protoc_insertion_point(copy_constructor:cc.unitconfig.UnitStatsConfig)
}

inline void UnitStatsConfig::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.armor_type_){}
    , decltype(_impl_.damage_type_){}
    , decltype(_impl_.health_){0}
    , decltype(_impl_.attack_power_){0}
    , decltype(_impl_.attack_range_){0}
    , decltype(_impl_.cooldown_time_){0}
    , decltype(_impl_.speed_){0}
    , decltype(_impl_.sight_range_){0}
  };
  _impl_.armor_type_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.armor_type_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.damage_type_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.damage_type_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

UnitStatsConfig::~UnitStatsConfig() {
  // @@protoc_insertion_point(destructor:cc.unitconfig.UnitStatsConfig)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void UnitStatsConfig::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.armor_type_.Destroy();
  _impl_.damage_type_.Destroy();
}

void UnitStatsConfig::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void UnitStatsConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:cc.unitconfig.UnitStatsConfig)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.armor_type_.ClearToEmpty();
  _impl_.damage_type_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000003fu) {
    ::memset(&_impl_.health_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&_impl_.sight_range_) -
        reinterpret_cast<char*>(&_impl_.health_)) + sizeof(_impl_.sight_range_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* UnitStatsConfig::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional float health = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 13)) {
          _Internal::set_has_health(&has_bits);
          _impl_.health_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // string armor_type = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_armor_type();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "cc.unitconfig.UnitStatsConfig.armor_type"));
        } else
          goto handle_unusual;
        continue;
      // string damage_type = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_damage_type();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "cc.unitconfig.UnitStatsConfig.damage_type"));
        } else
          goto handle_unusual;
        continue;
      // optional int32 attack_power = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _Internal::set_has_attack_power(&has_bits);
          _impl_.attack_power_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional int32 attack_range = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _Internal::set_has_attack_range(&has_bits);
          _impl_.attack_range_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional float cooldown_time = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 53)) {
          _Internal::set_has_cooldown_time(&has_bits);
          _impl_.cooldown_time_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // optional float speed = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 61)) {
          _Internal::set_has_speed(&has_bits);
          _impl_.speed_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // optional float sight_range = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 69)) {
          _Internal::set_has_sight_range(&has_bits);
          _impl_.sight_range_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* UnitStatsConfig::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:cc.unitconfig.UnitStatsConfig)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // optional float health = 1;
  if (_internal_has_health()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(1, this->_internal_health(), target);
  }

  // string armor_type = 2;
  if (!this->_internal_armor_type().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_armor_type().data(), static_cast<int>(this->_internal_armor_type().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "cc.unitconfig.UnitStatsConfig.armor_type");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_armor_type(), target);
  }

  // string damage_type = 3;
  if (!this->_internal_damage_type().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_damage_type().data(), static_cast<int>(this->_internal_damage_type().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "cc.unitconfig.UnitStatsConfig.damage_type");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_damage_type(), target);
  }

  // optional int32 attack_power = 4;
  if (_internal_has_attack_power()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(4, this->_internal_attack_power(), target);
  }

  // optional int32 attack_range = 5;
  if (_internal_has_attack_range()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(5, this->_internal_attack_range(), target);
  }

  // optional float cooldown_time = 6;
  if (_internal_has_cooldown_time()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(6, this->_internal_cooldown_time(), target);
  }

  // optional float speed = 7;
  if (_internal_has_speed()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(7, this->_internal_speed(), target);
  }

  // optional float sight_range = 8;
  if (_internal_has_sight_range()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(8, this->_internal_sight_range(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cc.unitconfig.UnitStatsConfig)
  return target;
}

size_t UnitStatsConfig::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:cc.unitconfig.UnitStatsConfig)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string armor_type = 2;
  if (!this->_internal_armor_type().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_armor_type());
  }

  // string damage_type = 3;
  if (!this->_internal_damage_type().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_damage_type());
  }

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000003fu) {
    // optional float health = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 + 4;
    }

    // optional int32 attack_power = 4;
    if (cached_has_bits & 0x00000002u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_attack_power());
    }

    // optional int32 attack_range = 5;
    if (cached_has_bits & 0x00000004u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_attack_range());
    }

    // optional float cooldown_time = 6;
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 + 4;
    }

    // optional float speed = 7;
    if (cached_has_bits & 0x00000010u) {
      total_size += 1 + 4;
    }

    // optional float sight_range = 8;
    if (cached_has_bits & 0x00000020u) {
      total_size += 1 + 4;
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData UnitStatsConfig::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    UnitStatsConfig::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*UnitStatsConfig::GetClassData() const { return &_class_data_; }


void UnitStatsConfig::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<UnitStatsConfig*>(&to_msg);
  auto& from = static_cast<const UnitStatsConfig&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:cc.unitconfig.UnitStatsConfig)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_armor_type().empty()) {
    _this->_internal_set_armor_type(from._internal_armor_type());
  }
  if (!from._internal_damage_type().empty()) {
    _this->_internal_set_damage_type(from._internal_damage_type());
  }
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000003fu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.health_ = from._impl_.health_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.attack_power_ = from._impl_.attack_power_;
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.attack_range_ = from._impl_.attack_range_;
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_impl_.cooldown_time_ = from._impl_.cooldown_time_;
    }
    if (cached_has_bits & 0x00000010u) {
      _this->_impl_.speed_ = from._impl_.speed_;
    }
    if (cached_has_bits & 0x00000020u) {
      _this->_impl_.sight_range_ = from._impl_.sight_range_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void UnitStatsConfig::CopyFrom(const UnitStatsConfig& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cc.unitconfig.UnitStatsConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UnitStatsConfig::IsInitialized() const {
  return true;
}

void UnitStatsConfig::InternalSwap(UnitStatsConfig* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.armor_type_, lhs_arena,
      &other->_impl_.armor_type_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.damage_type_, lhs_arena,
      &other->_impl_.damage_type_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(UnitStatsConfig, _impl_.sight_range_)
      + sizeof(UnitStatsConfig::_impl_.sight_range_)
      - PROTOBUF_FIELD_OFFSET(UnitStatsConfig, _impl_.health_)>(
          reinterpret_cast<char*>(&_impl_.health_),
          reinterpret_cast<char*>(&other->_impl_.health_));
}

::PROTOBUF_NAMESPACE_ID::Metadata UnitStatsConfig::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_unitconfig_2eproto_getter, &descriptor_table_unitconfig_2eproto_once,
      file_level_metadata_unitconfig_2eproto[0]);
}

// ===================================================================

class UnitCollisionConfig::_Internal {
 public:
};

UnitCollisionConfig::UnitCollisionConfig(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:cc.unitconfig.UnitCollisionConfig)
}
UnitCollisionConfig::UnitCollisionConfig(const UnitCollisionConfig& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  UnitCollisionConfig* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.footprint_width_){}
    , decltype(_impl_.footprint_height_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.footprint_width_, &from._impl_.footprint_width_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.footprint_height_) -
    reinterpret_cast<char*>(&_impl_.footprint_width_)) + sizeof(_impl_.footprint_height_));
  // @@protoc_insertion_point(copy_constructor:cc.unitconfig.UnitCollisionConfig)
}

inline void UnitCollisionConfig::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.footprint_width_){0}
    , decltype(_impl_.footprint_height_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

UnitCollisionConfig::~UnitCollisionConfig() {
  // @@protoc_insertion_point(destructor:cc.unitconfig.UnitCollisionConfig)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void UnitCollisionConfig::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void UnitCollisionConfig::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void UnitCollisionConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:cc.unitconfig.UnitCollisionConfig)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.footprint_width_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.footprint_height_) -
      reinterpret_cast<char*>(&_impl_.footprint_width_)) + sizeof(_impl_.footprint_height_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* UnitCollisionConfig::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 footprint_width = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.footprint_width_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 footprint_height = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.footprint_height_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* UnitCollisionConfig::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:cc.unitconfig.UnitCollisionConfig)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 footprint_width = 1;
  if (this->_internal_footprint_width() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_footprint_width(), target);
  }

  // int32 footprint_height = 2;
  if (this->_internal_footprint_height() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_footprint_height(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cc.unitconfig.UnitCollisionConfig)
  return target;
}

size_t UnitCollisionConfig::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:cc.unitconfig.UnitCollisionConfig)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 footprint_width = 1;
  if (this->_internal_footprint_width() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_footprint_width());
  }

  // int32 footprint_height = 2;
  if (this->_internal_footprint_height() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_footprint_height());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData UnitCollisionConfig::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    UnitCollisionConfig::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*UnitCollisionConfig::GetClassData() const { return &_class_data_; }


void UnitCollisionConfig::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<UnitCollisionConfig*>(&to_msg);
  auto& from = static_cast<const UnitCollisionConfig&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:cc.unitconfig.UnitCollisionConfig)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_footprint_width() != 0) {
    _this->_internal_set_footprint_width(from._internal_footprint_width());
  }
  if (from._internal_footprint_height() != 0) {
    _this->_internal_set_footprint_height(from._internal_footprint_height());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void UnitCollisionConfig::CopyFrom(const UnitCollisionConfig& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cc.unitconfig.UnitCollisionConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UnitCollisionConfig::IsInitialized() const {
  return true;
}

void UnitCollisionConfig::InternalSwap(UnitCollisionConfig* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(UnitCollisionConfig, _impl_.footprint_height_)
      + sizeof(UnitCollisionConfig::_impl_.footprint_height_)
      - PROTOBUF_FIELD_OFFSET(UnitCollisionConfig, _impl_.footprint_width_)>(
          reinterpret_cast<char*>(&_impl_.footprint_width_),
          reinterpret_cast<char*>(&other->_impl_.footprint_width_));
}

::PROTOBUF_NAMESPACE_ID::Metadata UnitCollisionConfig::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_unitconfig_2eproto_getter, &descriptor_table_unitconfig_2eproto_once,
      file_level_metadata_unitconfig_2eproto[1]);
}

// ===================================================================

class UnitArtConfig::_Internal {
 public:
};

UnitArtConfig::UnitArtConfig(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:cc.unitconfig.UnitArtConfig)
}
UnitArtConfig::UnitArtConfig(const UnitArtConfig& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  UnitArtConfig* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.sprite_prefix_){}
    , decltype(_impl_.atlas_idle_prefix_){}
    , decltype(_impl_.atlas_walk_prefix_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.sprite_prefix_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.sprite_prefix_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_sprite_prefix().empty()) {
    _this->_impl_.sprite_prefix_.Set(from._internal_sprite_prefix(), 
      _this->GetArenaForAllocation());
  }
  _impl_.atlas_idle_prefix_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.atlas_idle_prefix_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_atlas_idle_prefix().empty()) {
    _this->_impl_.atlas_idle_prefix_.Set(from._internal_atlas_idle_prefix(), 
      _this->GetArenaForAllocation());
  }
  _impl_.atlas_walk_prefix_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.atlas_walk_prefix_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_atlas_walk_prefix().empty()) {
    _this->_impl_.atlas_walk_prefix_.Set(from._internal_atlas_walk_prefix(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:cc.unitconfig.UnitArtConfig)
}

inline void UnitArtConfig::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.sprite_prefix_){}
    , decltype(_impl_.atlas_idle_prefix_){}
    , decltype(_impl_.atlas_walk_prefix_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.sprite_prefix_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.sprite_prefix_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.atlas_idle_prefix_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.atlas_idle_prefix_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.atlas_walk_prefix_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.atlas_walk_prefix_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

UnitArtConfig::~UnitArtConfig() {
  // @@protoc_insertion_point(destructor:cc.unitconfig.UnitArtConfig)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void UnitArtConfig::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.sprite_prefix_.Destroy();
  _impl_.atlas_idle_prefix_.Destroy();
  _impl_.atlas_walk_prefix_.Destroy();
}

void UnitArtConfig::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void UnitArtConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:cc.unitconfig.UnitArtConfig)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.sprite_prefix_.ClearToEmpty();
  _impl_.atlas_idle_prefix_.ClearToEmpty();
  _impl_.atlas_walk_prefix_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* UnitArtConfig::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string sprite_prefix = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_sprite_prefix();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "cc.unitconfig.UnitArtConfig.sprite_prefix"));
        } else
          goto handle_unusual;
        continue;
      // string atlas_idle_prefix = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_atlas_idle_prefix();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "cc.unitconfig.UnitArtConfig.atlas_idle_prefix"));
        } else
          goto handle_unusual;
        continue;
      // string atlas_walk_prefix = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_atlas_walk_prefix();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "cc.unitconfig.UnitArtConfig.atlas_walk_prefix"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* UnitArtConfig::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:cc.unitconfig.UnitArtConfig)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string sprite_prefix = 1;
  if (!this->_internal_sprite_prefix().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_sprite_prefix().data(), static_cast<int>(this->_internal_sprite_prefix().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "cc.unitconfig.UnitArtConfig.sprite_prefix");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_sprite_prefix(), target);
  }

  // string atlas_idle_prefix = 2;
  if (!this->_internal_atlas_idle_prefix().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_atlas_idle_prefix().data(), static_cast<int>(this->_internal_atlas_idle_prefix().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "cc.unitconfig.UnitArtConfig.atlas_idle_prefix");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_atlas_idle_prefix(), target);
  }

  // string atlas_walk_prefix = 3;
  if (!this->_internal_atlas_walk_prefix().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_atlas_walk_prefix().data(), static_cast<int>(this->_internal_atlas_walk_prefix().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "cc.unitconfig.UnitArtConfig.atlas_walk_prefix");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_atlas_walk_prefix(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cc.unitconfig.UnitArtConfig)
  return target;
}

size_t UnitArtConfig::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:cc.unitconfig.UnitArtConfig)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string sprite_prefix = 1;
  if (!this->_internal_sprite_prefix().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_sprite_prefix());
  }

  // string atlas_idle_prefix = 2;
  if (!this->_internal_atlas_idle_prefix().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_atlas_idle_prefix());
  }

  // string atlas_walk_prefix = 3;
  if (!this->_internal_atlas_walk_prefix().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_atlas_walk_prefix());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData UnitArtConfig::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    UnitArtConfig::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*UnitArtConfig::GetClassData() const { return &_class_data_; }


void UnitArtConfig::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<UnitArtConfig*>(&to_msg);
  auto& from = static_cast<const UnitArtConfig&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:cc.unitconfig.UnitArtConfig)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_sprite_prefix().empty()) {
    _this->_internal_set_sprite_prefix(from._internal_sprite_prefix());
  }
  if (!from._internal_atlas_idle_prefix().empty()) {
    _this->_internal_set_atlas_idle_prefix(from._internal_atlas_idle_prefix());
  }
  if (!from._internal_atlas_walk_prefix().empty()) {
    _this->_internal_set_atlas_walk_prefix(from._internal_atlas_walk_prefix());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void UnitArtConfig::CopyFrom(const UnitArtConfig& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cc.unitconfig.UnitArtConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UnitArtConfig::IsInitialized() const {
  return true;
}

void UnitArtConfig::InternalSwap(UnitArtConfig* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.sprite_prefix_, lhs_arena,
      &other->_impl_.sprite_prefix_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.atlas_idle_prefix_, lhs_arena,
      &other->_impl_.atlas_idle_prefix_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.atlas_walk_prefix_, lhs_arena,
      &other->_impl_.atlas_walk_prefix_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata UnitArtConfig::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_unitconfig_2eproto_getter, &descriptor_table_unitconfig_2eproto_once,
      file_level_metadata_unitconfig_2eproto[2]);
}

// ===================================================================

class UnitConfig::_Internal {
 public:
  static const ::cc::unitconfig::UnitStatsConfig& stats(const UnitConfig* msg);
  static const ::cc::unitconfig::UnitCollisionConfig& collision(const UnitConfig* msg);
  static const ::cc::unitconfig::UnitArtConfig& art(const UnitConfig* msg);
};

const ::cc::unitconfig::UnitStatsConfig&
UnitConfig::_Internal::stats(const UnitConfig* msg) {
  return *msg->_impl_.stats_;
}
const ::cc::unitconfig::UnitCollisionConfig&
UnitConfig::_Internal::collision(const UnitConfig* msg) {
  return *msg->_impl_.collision_;
}
const ::cc::unitconfig::UnitArtConfig&
UnitConfig::_Internal::art(const UnitConfig* msg) {
  return *msg->_impl_.art_;
}
UnitConfig::UnitConfig(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:cc.unitconfig.UnitConfig)
}
UnitConfig::UnitConfig(const UnitConfig& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  UnitConfig* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.type_){}
    , decltype(_impl_.stats_){nullptr}
    , decltype(_impl_.collision_){nullptr}
    , decltype(_impl_.art_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.type_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.type_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_type().empty()) {
    _this->_impl_.type_.Set(from._internal_type(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_stats()) {
    _this->_impl_.stats_ = new ::cc::unitconfig::UnitStatsConfig(*from._impl_.stats_);
  }
  if (from._internal_has_collision()) {
    _this->_impl_.collision_ = new ::cc::unitconfig::UnitCollisionConfig(*from._impl_.collision_);
  }
  if (from._internal_has_art()) {
    _this->_impl_.art_ = new ::cc::unitconfig::UnitArtConfig(*from._impl_.art_);
  }
  // @@protoc_insertion_point(copy_constructor:cc.unitconfig.UnitConfig)
}

inline void UnitConfig::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.type_){}
    , decltype(_impl_.stats_){nullptr}
    , decltype(_impl_.collision_){nullptr}
    , decltype(_impl_.art_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.type_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.type_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

UnitConfig::~UnitConfig() {
  // @@protoc_insertion_point(destructor:cc.unitconfig.UnitConfig)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void UnitConfig::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.type_.Destroy();
  if (this != internal_default_instance()) delete _impl_.stats_;
  if (this != internal_default_instance()) delete _impl_.collision_;
  if (this != internal_default_instance()) delete _impl_.art_;
}

void UnitConfig::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void UnitConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:cc.unitconfig.UnitConfig)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.type_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && _impl_.stats_ != nullptr) {
    delete _impl_.stats_;
  }
  _impl_.stats_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.collision_ != nullptr) {
    delete _impl_.collision_;
  }
  _impl_.collision_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.art_ != nullptr) {
    delete _impl_.art_;
  }
  _impl_.art_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* UnitConfig::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_type();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "cc.unitconfig.UnitConfig.type"));
        } else
          goto handle_unusual;
        continue;
      // .cc.unitconfig.UnitStatsConfig stats = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_stats(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .cc.unitconfig.UnitCollisionConfig collision = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_collision(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .cc.unitconfig.UnitArtConfig art = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_art(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* UnitConfig::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:cc.unitconfig.UnitConfig)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string type = 1;
  if (!this->_internal_type().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_type().data(), static_cast<int>(this->_internal_type().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "cc.unitconfig.UnitConfig.type");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_type(), target);
  }

  // .cc.unitconfig.UnitStatsConfig stats = 2;
  if (this->_internal_has_stats()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::stats(this),
        _Internal::stats(this).GetCachedSize(), target, stream);
  }

  // .cc.unitconfig.UnitCollisionConfig collision = 3;
  if (this->_internal_has_collision()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::collision(this),
        _Internal::collision(this).GetCachedSize(), target, stream);
  }

  // .cc.unitconfig.UnitArtConfig art = 4;
  if (this->_internal_has_art()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, _Internal::art(this),
        _Internal::art(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cc.unitconfig.UnitConfig)
  return target;
}

size_t UnitConfig::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:cc.unitconfig.UnitConfig)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string type = 1;
  if (!this->_internal_type().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_type());
  }

  // .cc.unitconfig.UnitStatsConfig stats = 2;
  if (this->_internal_has_stats()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.stats_);
  }

  // .cc.unitconfig.UnitCollisionConfig collision = 3;
  if (this->_internal_has_collision()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.collision_);
  }

  // .cc.unitconfig.UnitArtConfig art = 4;
  if (this->_internal_has_art()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.art_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData UnitConfig::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    UnitConfig::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*UnitConfig::GetClassData() const { return &_class_data_; }


void UnitConfig::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<UnitConfig*>(&to_msg);
  auto& from = static_cast<const UnitConfig&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:cc.unitconfig.UnitConfig)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_type().empty()) {
    _this->_internal_set_type(from._internal_type());
  }
  if (from._internal_has_stats()) {
    _this->_internal_mutable_stats()->::cc::unitconfig::UnitStatsConfig::MergeFrom(
        from._internal_stats());
  }
  if (from._internal_has_collision()) {
    _this->_internal_mutable_collision()->::cc::unitconfig::UnitCollisionConfig::MergeFrom(
        from._internal_collision());
  }
  if (from._internal_has_art()) {
    _this->_internal_mutable_art()->::cc::unitconfig::UnitArtConfig::MergeFrom(
        from._internal_art());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void UnitConfig::CopyFrom(const UnitConfig& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cc.unitconfig.UnitConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UnitConfig::IsInitialized() const {
  return true;
}

void UnitConfig::InternalSwap(UnitConfig* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.type_, lhs_arena,
      &other->_impl_.type_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(UnitConfig, _impl_.art_)
      + sizeof(UnitConfig::_impl_.art_)
      - PROTOBUF_FIELD_OFFSET(UnitConfig, _impl_.stats_)>(
          reinterpret_cast<char*>(&_impl_.stats_),
          reinterpret_cast<char*>(&other->_impl_.stats_));
}

::PROTOBUF_NAMESPACE_ID::Metadata UnitConfig::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_unitconfig_2eproto_getter, &descriptor_table_unitconfig_2eproto_once,
      file_level_metadata_unitconfig_2eproto[3]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace unitconfig
}  // namespace cc
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::cc::unitconfig::UnitStatsConfig*
Arena::CreateMaybeMessage< ::cc::unitconfig::UnitStatsConfig >(Arena* arena) {
  return Arena::CreateMessageInternal< ::cc::unitconfig::UnitStatsConfig >(arena);
}
template<> PROTOBUF_NOINLINE ::cc::unitconfig::UnitCollisionConfig*
Arena::CreateMaybeMessage< ::cc::unitconfig::UnitCollisionConfig >(Arena* arena) {
  return Arena::CreateMessageInternal< ::cc::unitconfig::UnitCollisionConfig >(arena);
}
template<> PROTOBUF_NOINLINE ::cc::unitconfig::UnitArtConfig*
Arena::CreateMaybeMessage< ::cc::unitconfig::UnitArtConfig >(Arena* arena) {
  return Arena::CreateMessageInternal< ::cc::unitconfig::UnitArtConfig >(arena);
}
template<> PROTOBUF_NOINLINE ::cc::unitconfig::UnitConfig*
Arena::CreateMaybeMessage< ::cc::unitconfig::UnitConfig >(Arena* arena) {
  return Arena::CreateMessageInternal< ::cc::unitconfig::UnitConfig >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
